/**
 * Strings of the game controller (namespace "game"): inbox letters, notices, blockers,
 * news facts handed to the narrators, press fallbacks, save errors. Turkish first.
 */
import { registerStrings } from '../core/i18n';

const tr: Record<string, string> = {
  // errors
  'err.noState': 'Yüklü bir kariyer yok.',
  'err.blocked': 'Haftayı ilerletmeden önce halletmen gereken işler var.',
  'err.noEvent': 'Olay bulunamadı.',
  'err.noOffer': 'Teklif bulunamadı.',
  'err.offerClosed': 'Bu teklif artık masada değil.',
  'err.noPress': 'Basın toplantısı bulunamadı.',
  'err.noQuestion': 'Soru bulunamadı.',
  'err.noFixture': 'Maç bulunamadı.',
  'err.alreadyPlayed': 'Bu maç zaten oynandı.',
  'err.invalid_json': 'Kayıt dosyası okunamadı (geçersiz JSON).',
  'err.invalid': 'Kayıt dosyası bozuk ya da tanınmıyor.',
  'err.newer': 'Bu kayıt oyunun daha yeni bir sürümüyle oluşturulmuş.',
  'err.missing': 'Bu yuvada kayıt yok.',

  // advance blockers
  'block.retired': 'Kariyerin sona erdi.',
  'block.chooseClub': 'Önce deneme davetlerinden birini kabul edip kulübünü seç.',
  'block.playMatch': '{opp} maçını oyna ({comp})',
  'block.event': 'Karar bekleyen olay: {title}',
  'block.mustRetire': 'Vücudun artık izin vermiyor — jübile vakti geldi.',

  // save slots
  'meta.retired': 'Emekli',
  'meta.freeAgent': 'Serbest oyuncu',

  // facts for the narrators (terse, factual)
  'facts.newTalent': '{town} doğumlu {age} yaşındaki {pos} {name}, profesyonel futbola adım atıyor. Deneme davetleri: {clubs}.',
  'facts.noClub': 'kulüpsüz',
  'facts.sponsor': '{name}, {brand} ile sponsorluk anlaşması imzaladı.',
  'facts.trial': '{name} denemeyi geçti ve {to} ile ilk profesyonel sözleşmesini imzaladı ({years} yıl, haftalık {wage}).',
  'facts.loan': '{name}, {from} kulübünden {to} takımına kiralık olarak katıldı.',
  'facts.free': '{name}, bonservissiz olarak {to} ile {years} yıllık sözleşme imzaladı (haftalık {wage}).',
  'facts.transfer': '{name}, {fee} bonservis bedeliyle {from} kulübünden {to} takımına transfer oldu. Sözleşme: {years} yıl, haftalık {wage}.',
  'facts.renewal': '{name}, {to} ile sözleşmesini uzattı ({years} yıl, haftalık {wage}).',
  'facts.injury': '{name} sakatlandı; yaklaşık {weeks} hafta sahalardan uzak kalacak.',
  'facts.milestone': '{name}, profesyonel kariyerindeki {n}. golünü attı.',
  'facts.match': '{comp}: {home} {hg}-{ag} {away}. {team} açısından sonuç: {result}.',
  'facts.res.W': 'galibiyet',
  'facts.res.D': 'beraberlik',
  'facts.res.L': 'mağlubiyet',
  'facts.userLine': '{name}: {goals} gol, {assists} asist, maç puanı {rating}.',
  'facts.unused': '{name} bu maçta forma giymedi.',
  'facts.motm': 'Maçın adamı seçildi.',
  'facts.derby': 'Maç bir derbiydi.',
  'facts.vsRival': 'Karşı tarafta ezeli rakibi {rival} vardı.',
  'facts.award': '{name}, {season} sezonunda {award} ödülünü kazandı.',
  'facts.trophy': '{name}, {team} formasıyla {season} sezonunda {trophy} kupasını kaldırdı.',
  'facts.champion': '{comp} şampiyonu: {team}.',
  'facts.rumour': '{club}, {name} için yaklaşık {fee} değerinde resmi teklif yaptı.',
  'facts.firstCallup': '{name}, kariyerinde ilk kez {team} kadrosuna davet edildi.',
  'facts.callup': '{name}, {team} kadrosuna yeniden davet edildi.',

  // welcome letters
  'welcome.scoutFrom': 'İsimsiz bir gözlemci',
  'welcome.scoutSubject': 'Kısa bir not: Gözüm üzerinde',
  'welcome.scoutBody': 'Otuz yıldır tribün kenarlarında dolaşırım; hangi çocuğun neye dönüşeceğini çoğu zaman bilirim. Senin için tek bir şey söyleyeceğim:\n\n“{hint}”\n\nGerisini sen yazacaksın.',
  'welcome.familySubject.father': 'Babandan',
  'welcome.familySubject.mother': 'Annenden',
  'welcome.familySubject.sibling': 'Kardeşinden',
  'welcome.familyBody': 'Canım {first},\n\nMahalledeki o tozlu sahalardan bugünlere geldin, inanabiliyor musun? Bütün {town} senin için dua ediyor. Hep söylediğin sözü unutma: “{motto}”\n\nHayalin belli: {dream} Her maçında tribünde — olmadı televizyonun başında — olacağız. Yemeğini düzgün ye, uykunu al, kimseye kafa tutma.\n\nSeni çok seviyoruz.',
  'welcome.agentSubject': 'Hoş geldin {first} — işe koyuluyoruz',
  'welcome.agentBody': '{first}, ben {agent}. Bundan sonra sözleşmelerin, tekliflerin ve basınla ilişkilerin bende.\n\nMasada {n} kulübün deneme daveti var: {clubs}. Gelen kutundaki davetleri incele ve birini kabul et; gerisini sahada konuşturacaksın.\n\nKüçük bir tavsiye: ilk kulüp son durak değildir. Bu yaşta forma süresi her şeyden kıymetli.',

  // offers
  'offer.terms': 'Haftalık {wage} · {years} yıl · Rol: {role}',
  'offer.fee': 'Bonservis: {fee}',
  'offer.bonus': 'İmza parası: {bonus}',
  'offer.subject.transfer': '{club} seni kadrosunda görmek istiyor',
  'offer.subject.loan': '{club} kiralık teklif yaptı',
  'offer.subject.free': '{club} sözleşme önerdi',
  'offer.subject.renewal': '{club} sözleşmeni uzatmak istiyor',
  'offer.subject.trial': '{club} seni denemeye çağırıyor',
  'offers.note': '{n} yeni transfer teklifi geldi',
  'offers.expired': 'Süresi dolan teklif: {n}',

  // toasts
  'notice.sponsorSigned': '{brand} ile anlaşma tamam!',
  'notice.signed': 'Yeni kulübün: {club}!',
  'notice.renewed': '{club} ile sözleşme uzatıldı',
  'notice.injury': 'Sakatlık: {weeks} hafta yoksun',
  'notice.milestone': 'Kariyer golü #{n}!',
  'notice.goal': 'Hedef tamam: {goal}',
  'notice.trophy': 'Kupa! {trophy}',
  'notice.award': 'Ödül: {award}',
  'notice.seasonEnd': '{season} sezonu sona erdi',
  'notice.newSeason': '{season} sezonu başlıyor!',
  'notice.callup': 'Milli davet: {team}!',
  'notice.offer': '{n} yeni teklif var',
  'notice.sponsor': '{brand} sponsorluk teklif etti',
  'notice.retired': 'Kramponları duvara astın. Efsane bitti, hikâye kaldı.',

  // press
  'press.facts.pre_match': '{name} ({club}), {comp} kapsamındaki {opp} maçı öncesinde basının karşısında.',
  'press.facts.post_match': '{name} ({club}), {opp} maçının ({gf}-{ga}) ardından konuşuyor. Kişisel istatistik: {goals} gol, {assists} asist, puan {rating}.',
  'press.facts.transfer': '{name} ({club}) hakkında transfer söylentileri dolaşıyor. İlgilenen kulüpler: {clubs}. Transfer listesinde: {listed}.',
  'press.facts.unveiling': '{name}, {club} formasıyla basına tanıtılıyor.',
  'press.facts.scandal': '{name} ({club}), saha dışındaki tartışmalı gelişmeler ({kind}) hakkında soruları yanıtlıyor.',
  'press.facts.milestone': '{name} ({club}) kariyerinde önemli bir eşiği geçti: {apps} maç, {goals} gol.',
  'press.facts.generic': '{name} ({club}) basın toplantısında.',
  'press.headline.humble': '{name}: “Önce takım gelir”',
  'press.headline.confident': 'İddialı konuştu: {name} “En iyisi olacağım” dedi',
  'press.headline.provocative': 'Olay sözler! {name} ortalığı karıştırdı',
  'press.headline.diplomatic': '{name} dengeli konuştu, kimseyi kırmadı',
  'press.headline.emotional': 'Duygusal anlar: {name} içini döktü',
  'press.headline.deflect': '{name} soruları geçiştirdi',
  'press.feedback.humble': 'Mütevazı tavrın taraftarın ve takım arkadaşlarının hoşuna gitti.',
  'press.feedback.confident': 'Özgüvenin tribünleri coşturdu; şimdi sıra sahada kanıtlamakta.',
  'press.feedback.provocative': 'Manşetlere çıktın ama soyunma odası ve hocan bundan pek hoşlanmadı.',
  'press.feedback.diplomatic': 'Kimseyi kırmadın; basın da teknik direktör de memnun.',
  'press.feedback.emotional': 'Samimiyetin taraftarın kalbine dokundu.',
  'press.feedback.deflect': 'Gazeteciler kaçamak cevaplarından pek hoşlanmadı.',
  'press.articleBody': '{journalist} sordu: “{question}”\n\n{name} yanıtladı: “{answer}”\n\n{feedback}',
  'press.fallback.journalist1': 'Selin Akdoğan',
  'press.fallback.journalist2': 'Volkan Erenler',
  'press.fallback.journalist3': 'Burcu Tanrıverdi',
  'press.fallback.q1.match': 'Son haftalardaki performansını nasıl değerlendiriyorsun?',
  'press.fallback.q1.transfer': 'Transfer söylentileri hakkında ne söylemek istersin?',
  'press.fallback.q2.match': 'Hocanla aran nasıl, aldığın süreden memnun musun?',
  'press.fallback.q2.transfer': 'Kariyerinin bu noktasında senin için en önemlisi ne: para mı, forma mı, kupalar mı?',
  'press.fallback.q3.match': 'Saha dışında hayat nasıl gidiyor, ailen bu yükselişe ne diyor?',
  'press.fallback.q3.transfer': 'Taraftarlara bir mesajın var mı?',
  'press.fallback.a.humble': 'Ben sadece çalışmaya devam ediyorum. Takım kazansın, gerisi teferruat.',
  'press.fallback.a.confident': 'Neler yapabileceğimi biliyorum. Daha en iyi hâlimi görmediniz.',
  'press.fallback.a.provocative': 'Bazıları benim hakkımda çok konuşuyor. Cevabımı sahada veririm, hem de en sert şekilde.',
  'press.fallback.a.diplomatic': 'Herkese saygım var. Hocamın kararlarına güveniyorum; odağım bir sonraki maç.',
  'press.fallback.a.emotional': 'Bu formayı giymek benim için bir rüya. Ailemi ve beni büyüten mahalleyi düşünüyorum.',
  'press.fallback.a.deflect': 'Bu konuda yorum yapmak istemiyorum. Sıradaki soru lütfen.',

  // chat personas
  'persona.agent': 'Menajerin',
  'persona.manager': 'Teknik direktör',
  'persona.mentor': 'Takımın ağabeyi',
  'persona.partner': 'Sevgilin',
  'persona.family': 'Ailen',
  'persona.rival': 'Rakibin',
  'chat.fallback': '{name} şu an meşgul, sonra dönecek.',

  // signing
  'sign.welcomeSubject': '{club} ailesine hoş geldin!',
  'sign.trialBody': 'Tebrikler {first}! Denemedeki performansın hepimizi ikna etti; artık resmen {club} oyuncususun.\n\nBurada kimse sana bir şey hediye etmeyecek, her dakikayı antrenmanda kazanacaksın. {city} futbolu yaşar; “{nick}” formasını gururla taşı.\n\nPazartesi sabah dokuzda tesislerdeyiz. Sakın geç kalma.',
  'sign.welcomeBody': '{first}, aramıza hoş geldin. Seni neden aldığımızı biliyorsun; şimdi bunu her hafta sahada göstermeni bekliyorum.\n\n{city} futbolu yaşar ve taraftar “{nick}” formasını terleten oyuncuyu sever. Kapım her zaman açık.',
  'sign.renewSubject': '{club} ile imzalar atıldı',
  'sign.renewBody': 'Yönetim yeni sözleşmeni onayladı: {years} yıl, haftalık {wage}. Sana güveniyoruz, {name}.',

  // negotiation
  'neg.opening': '{club} masaya ilk teklifini koydu.',
  'neg.agent.low': '{agent}: “Bu rakam düşük. Senin seviyendeki bir oyuncu haftada {fair} civarı kazanır. Bastır.”',
  'neg.agent.fair': '{agent}: “Makul bir teklif, piyasa {fair} civarında. Biraz artış isteyebiliriz ama ipi fazla germeyelim.”',
  'neg.agent.generous': '{agent}: “Açık konuşayım, bu cömert bir teklif — piyasa {fair} civarında. Fazla nazlanırsak masadan kalkarlar.”',
  'neg.playerAsk': 'Haftalık {wage}, {years} yıl ve “{role}” rolü istiyorum.',
  'neg.club.open': '{club}: “Talebini değerlendirdik. Yeni teklifimiz bu.”',
  'neg.club.agreed': '{club}: “Anlaştık! Kalemini hazırla.”',
  'neg.club.collapsed': '{club}: “Bu şartlarla devam edemeyiz. Görüşmeler burada biter.”',
  'neg.agreed': 'Şartlarda uzlaşıldı. İmzalamak için onayla.',
  'neg.collapsed': '{club} ile görüşmeler çöktü.',
  'neg.collapsedSubject': '{club} masadan kalktı',
  'neg.collapsedBody': '{club} yöneticileri taleplerini fazla buldu ve teklifi geri çekti. Belki başka bir kapı açılır.',
  'neg.finalOffer': 'Bu, kulübün son teklifi. Ya kabul et ya da masadan kalk.',

  // goals, trophies, awards
  'goal.from': 'Kariyer Hedefleri',
  'goal.subject': 'Hedef tamamlandı!',
  'goal.body': 'Kendine koyduğun hedeflerden birini gerçekleştirdin:\n\n— {goal}\n\nHikâyen büyümeye devam ediyor.',
  'goal.note': 'Hedef tamamlandı: {goal}',
  'trophy.subject': 'Şampiyon! {trophy}',
  'trophy.body': '{season} sezonunda {trophy} kupasını kaldırdınız. Çocukken hayalini kurduğun an tam olarak buydu. Tadını çıkar.',
  'award.subject': 'Ödül: {award}',
  'award.body': '{season} sezonunun {award} ödülü senin! {detail}',

  // season
  'season.from': 'Sezon Raporu',
  'season.summarySubject': '{season} sezon karnesi',
  'season.summaryBody': '{season} sezonu tamamlandı.\n\nKulüp: {club} (lig sırası: {pos})\nMaç: {apps} · Gol: {goals} · Asist: {assists}\nOrtalama puan: {avg}\nGenel güç: {ovr}\n\nYaz dönemi başladı: transfer penceresi açık, dinlenmeyi de ihmal etme.',
  'season.summaryNoRecord': '{season} sezonu sona erdi. Bu sezon resmi maçta forma giyemedin; yeni sezon, yeni fırsat demek.',
  'season.ended': '{season} sezonu tamamlandı',
  'season.newSubject': '{season} sezonu başlıyor',
  'season.newBody': 'Yeni sezon, yeni sayfa {first}. {age} yaşındasın ve {season} sezonu seni bekliyor. Hazırlık kampı başladı; formunu koru, hocana kendini göster.',
  'season.started': '{season} sezonu başladı',

  // retirement
  'retire.forcedSubject': 'Vedalaşma vakti',
  'retire.forcedBody': '{first}, açık konuşacağım: vücudun artık bu tempoyu kaldırmıyor, doktorlar da aynı fikirde. Kariyer ekranından jübileni planlayalım — büyük oyuncular sahneyi zamanında terk eder.',
  'retire.hintSubject': 'Gelecek üzerine bir sohbet',
  'retire.hintBody': '{first}, uzun yıllardır birlikteyiz. Hâlâ oynayabilirsin ama artık istediğin an jübile yapma hakkın var. Karar senin; ne seçersen seç arkandayım.',
  'retire.newsHeadline': 'Bir devir kapandı: {name} futbolu bıraktı',
  'retire.newsBody': '{name} profesyonel futbolu bıraktığını açıkladı. Kariyerini {apps} maç, {goals} gol ve {trophies} kupayla noktaladı. Tribünler onu uzun süre özleyecek.',
  'retire.inboxSubject': 'Son düdük',
  'retire.inboxBody': '{first}, bugün kramponları duvara astın. Bunca yıl yanında olmak bir onurdu. Belgeselin hazır — Miras ekranından hikâyeni baştan sona izleyebilirsin.',
  'retire.bioFallback': 'Bir futbol hayatı, rakamlarla:\n\n{facts}',

  // week report
  'report.pens': 'pen. {h}-{a}',

  // national team
  'callup.subject': 'Milli takım daveti: {team}',
  'callup.firstBody': '{first}, teknik heyet olarak seni {team} kadrosuna davet ediyoruz. Bu, kariyerindeki ilk milli davet — formayı onurla taşı. {tournament}',
  'callup.body': '{first}, performansın gözümüzden kaçmadı. Önümüzdeki milli maçlar için {team} kadrosundasın. {tournament}',
  'callup.tournament': 'Büyük turnuva kapıda; bütün ülke bu kadroya bakıyor.',
  'callup.note': '{team} kadrosuna davet edildin',

  // sponsors
  'sponsor.subject': '{brand} sponsorluk teklifi',
  'sponsor.body': '{brand} seni yeni yüzü yapmak istiyor ({category}).\n\nHaftalık ödeme: {weekly}\nSüre: {until} yazına kadar{req}\n\nTeklifi bu mesajdan kabul edebilir ya da reddedebilirsin.',
  'sponsor.req': '\nKoşul: {req}',
  'sponsor.note': '{brand} sponsorluk teklif etti',

  // biography facts
  'bio.none': 'yok',
  'bio.header': '{name} — {nation}, {pos}. Profesyonel kariyer: {from}–{to}.',
  'bio.clubs': 'Kulüpler: {clubs}',
  'bio.totals': 'Kulüp kariyeri: {apps} maç, {goals} gol, {assists} asist.',
  'bio.trophies': 'Kupalar: {list}',
  'bio.awards': 'Bireysel ödüller: {list}',
  'bio.intl': 'Milli takım: {caps} maç, {goals} gol.',
  'bio.peak': 'Zirve: genel güç {ovr}, piyasa değeri {value}.',
  'bio.origin': 'Memleketi: {town}. Çocukluk hayali: {dream}',
  'bio.rival': 'Ezeli rakibi: {rival} ({goals} kariyer golü).',
  'bio.goals': 'Gerçekleşen hedefler: {list}',
  'bio.hof': 'Efsane puanı: {score}',

  // misc
  'events.note': 'Kararını bekleyen yeni olay: {n}',
  'inbox.eventFrom': 'Gündem',
  'outlet.default': 'Tribün Postası',

  // genesis fallbacks
  'genesis.unknownTown': 'küçük bir kasaba',
  'genesis.parentName': 'Ahmet',
  'genesis.backstory': '{first}, {town} kenar mahallelerinde, okul çıkışı sokak lambaları yanana kadar top koşturarak büyüdü. Mahallenin en küçüğüydü ama top ayağına geldiğinde herkes susardı. Yerel amatör kulüpte {pos} olarak parladı ve gözlemcilerin dikkatini çekmesi uzun sürmedi. Şimdi önünde tek bir soru var: Bu yetenek nereye kadar gidecek?',
  'genesis.motto': 'Ter, yetenekten önce gelir.',
  'genesis.dream': 'Bir gün tıklım tıklım bir stadyumda final golünü atmak.',
  'genesis.destiny': 'Gözlerinde nadir görülen bir ateş var; doğru ellerde parlak bir yıldıza dönüşebilir.',
  'genesis.fatherPersonality': 'sabırlı, gururlu, az konuşan',
  'genesis.motherName': 'Ayşe',
  'genesis.motherPersonality': 'şefkatli, dirençli, hep arayan',
  'genesis.motherBio': 'Her maçtan önce arar; izleyemez, sonucu mutfakta dua ederek bekler.',
  'genesis.fatherBio': 'Hayatı boyunca gece vardiyasında çalıştı; çocuğunun tek bir maçını kaçırmamak için izinlerini biriktirdi.',
  'genesis.agentPersonality': 'kurnaz, sadık, telefonu hiç susmayan',
  'genesis.agentBio': 'Alt liglerde pişmiş eski bir futbolcu; şimdi genç yetenekleri doğru kulüplere taşımayı iş edinmiş.',
  'genesis.agentFallbackName': 'Kemal Aydıner',
  'genesis.rivalBlurb': '{rival} ({club}) — aynı yaştasınız, aynı mevkide oynuyorsunuz ve gazeteler sizi şimdiden kıyaslamaya başladı.',
};

const en: Record<string, string> = {
  'err.noState': 'No career is loaded.',
  'err.blocked': 'You have things to sort out before advancing the week.',
  'err.noEvent': 'Event not found.',
  'err.noOffer': 'Offer not found.',
  'err.offerClosed': 'This offer is no longer on the table.',
  'err.noPress': 'Press conference not found.',
  'err.noQuestion': 'Question not found.',
  'err.noFixture': 'Fixture not found.',
  'err.alreadyPlayed': 'This match has already been played.',
  'err.invalid_json': 'Could not read the save file (invalid JSON).',
  'err.invalid': 'The save file is corrupt or not recognised.',
  'err.newer': 'This save was made with a newer version of the game.',
  'err.missing': 'There is no save in this slot.',

  'block.retired': 'Your career is over.',
  'block.chooseClub': 'Accept one of the trial invitations to choose your club first.',
  'block.playMatch': 'Play your match vs {opp} ({comp})',
  'block.event': 'Decision pending: {title}',
  'block.mustRetire': 'Your body has had enough — it is time to retire.',

  'meta.retired': 'Retired',
  'meta.freeAgent': 'Free agent',

  'facts.newTalent': '{age}-year-old {pos} {name} from {town} is starting a professional career. Trial invitations: {clubs}.',
  'facts.noClub': 'without a club',
  'facts.sponsor': '{name} signed a sponsorship deal with {brand}.',
  'facts.trial': '{name} passed the trial and signed a first professional contract with {to} ({years} years, {wage} a week).',
  'facts.loan': '{name} joined {to} on loan from {from}.',
  'facts.free': '{name} joined {to} on a free transfer, signing a {years}-year deal ({wage} a week).',
  'facts.transfer': '{name} completed a {fee} move from {from} to {to}. Contract: {years} years, {wage} a week.',
  'facts.renewal': '{name} extended the contract with {to} ({years} years, {wage} a week).',
  'facts.injury': '{name} picked up an injury and faces around {weeks} weeks out.',
  'facts.milestone': '{name} scored professional career goal number {n}.',
  'facts.match': '{comp}: {home} {hg}-{ag} {away}. Result for {team}: {result}.',
  'facts.res.W': 'win',
  'facts.res.D': 'draw',
  'facts.res.L': 'defeat',
  'facts.userLine': '{name}: {goals} goals, {assists} assists, match rating {rating}.',
  'facts.unused': '{name} did not get on the pitch.',
  'facts.motm': 'Named man of the match.',
  'facts.derby': 'It was a derby.',
  'facts.vsRival': 'Long-time rival {rival} lined up for the opposition.',
  'facts.award': '{name} won the {award} for the {season} season.',
  'facts.trophy': '{name} lifted the {trophy} with {team} in {season}.',
  'facts.champion': '{comp} champions: {team}.',
  'facts.rumour': '{club} have made a formal offer worth around {fee} for {name}.',
  'facts.firstCallup': '{name} has been called up by {team} for the first time.',
  'facts.callup': '{name} has been called up by {team} again.',

  'welcome.scoutFrom': 'An anonymous scout',
  'welcome.scoutSubject': 'A short note: I have my eye on you',
  'welcome.scoutBody': 'I have haunted touchlines for thirty years; I can usually tell what a kid will become. About you, I will say just one thing:\n\n“{hint}”\n\nThe rest is yours to write.',
  'welcome.familySubject.father': 'From your dad',
  'welcome.familySubject.mother': 'From your mum',
  'welcome.familySubject.sibling': 'From your sibling',
  'welcome.familyBody': 'Dear {first},\n\nFrom those dusty pitches round the corner to this — can you believe it? All of {town} is behind you. Remember what you always say: “{motto}”\n\nYour dream is clear: {dream} We will be there for every match — in the stands, or glued to the TV. Eat properly, get your sleep, and don\'t pick fights with anyone.\n\nWe love you.',
  'welcome.agentSubject': 'Welcome, {first} — let\'s get to work',
  'welcome.agentBody': '{first}, {agent} here. From now on your contracts, your offers and your dealings with the press go through me.\n\n{n} clubs have invited you for a trial: {clubs}. Look through the invitations in your inbox and accept one; then let your football do the talking.\n\nA word of advice: your first club is not your last stop. At your age, minutes matter more than anything.',

  'offer.terms': '{wage}/week · {years} yrs · Role: {role}',
  'offer.fee': 'Fee: {fee}',
  'offer.bonus': 'Signing bonus: {bonus}',
  'offer.subject.transfer': '{club} want to sign you',
  'offer.subject.loan': 'Loan offer from {club}',
  'offer.subject.free': '{club} offer you a contract',
  'offer.subject.renewal': '{club} want to extend your contract',
  'offer.subject.trial': 'Trial invitation from {club}',
  'offers.note': 'New transfer offers: {n}',
  'offers.expired': 'Offers expired: {n}',

  'notice.sponsorSigned': 'Deal signed with {brand}!',
  'notice.signed': 'You have joined {club}!',
  'notice.renewed': 'Contract extended with {club}',
  'notice.injury': 'Injured: out for {weeks} weeks',
  'notice.milestone': 'Career goal #{n}!',
  'notice.goal': 'Goal achieved: {goal}',
  'notice.trophy': 'Silverware! {trophy}',
  'notice.award': 'Award: {award}',
  'notice.seasonEnd': 'The {season} season is over',
  'notice.newSeason': 'The {season} season begins!',
  'notice.callup': 'National team call-up: {team}!',
  'notice.offer': 'New offers: {n}',
  'notice.sponsor': '{brand} want to sponsor you',
  'notice.retired': 'You have hung up your boots. The playing days are over; the story remains.',

  'press.facts.pre_match': '{name} ({club}) faces the press before the {comp} match against {opp}.',
  'press.facts.post_match': '{name} ({club}) speaks after the match against {opp} ({gf}-{ga}). Personal stats: {goals} goals, {assists} assists, rating {rating}.',
  'press.facts.transfer': 'Transfer rumours surround {name} ({club}). Interested clubs: {clubs}. Transfer-listed: {listed}.',
  'press.facts.unveiling': '{name} is being unveiled to the press as a {club} player.',
  'press.facts.scandal': '{name} ({club}) answers questions about controversy off the pitch ({kind}).',
  'press.facts.milestone': '{name} ({club}) has passed a career landmark: {apps} appearances, {goals} goals.',
  'press.facts.generic': '{name} ({club}) at a press conference.',
  'press.headline.humble': '{name}: “The team comes first”',
  'press.headline.confident': 'Bold {name}: “I will be the best”',
  'press.headline.provocative': '{name} stirs the pot with explosive remarks',
  'press.headline.diplomatic': '{name} keeps it diplomatic',
  'press.headline.emotional': 'An emotional {name} opens up',
  'press.headline.deflect': '{name} dodges the questions',
  'press.feedback.humble': 'Your humility went down well with the fans and your teammates.',
  'press.feedback.confident': 'Your confidence fired up the fans — now back it up on the pitch.',
  'press.feedback.provocative': 'You made the headlines, but the dressing room and your manager were not amused.',
  'press.feedback.diplomatic': 'You offended nobody; the press and the manager are content.',
  'press.feedback.emotional': 'Your honesty touched the fans\' hearts.',
  'press.feedback.deflect': 'The journalists did not appreciate the dodge.',
  'press.articleBody': '{journalist} asked: “{question}”\n\n{name} replied: “{answer}”\n\n{feedback}',
  'press.fallback.journalist1': 'Sally Brookfield',
  'press.fallback.journalist2': 'Martin Oakes',
  'press.fallback.journalist3': 'Elena Varga',
  'press.fallback.q1.match': 'How would you assess your performances over the last few weeks?',
  'press.fallback.q1.transfer': 'What would you like to say about the transfer rumours?',
  'press.fallback.q2.match': 'How are things with the manager — are you happy with your minutes?',
  'press.fallback.q2.transfer': 'At this stage of your career, what matters most: money, minutes or trophies?',
  'press.fallback.q3.match': 'How is life off the pitch — what does your family make of this rise?',
  'press.fallback.q3.transfer': 'Do you have a message for the fans?',
  'press.fallback.a.humble': 'I just keep working. As long as the team wins, nothing else matters.',
  'press.fallback.a.confident': 'I know what I can do. You haven\'t seen the best of me yet.',
  'press.fallback.a.provocative': 'Some people talk a lot about me. I will answer on the pitch — loudly.',
  'press.fallback.a.diplomatic': 'I respect everyone. I trust the coach\'s decisions; my focus is the next game.',
  'press.fallback.a.emotional': 'Wearing this shirt is a dream. I think of my family and the streets that raised me.',
  'press.fallback.a.deflect': 'No comment on that. Next question, please.',

  'persona.agent': 'Your agent',
  'persona.manager': 'The manager',
  'persona.mentor': 'Your mentor',
  'persona.partner': 'Your partner',
  'persona.family': 'Your family',
  'persona.rival': 'Your rival',
  'chat.fallback': '{name} is busy right now and will get back to you.',

  'sign.welcomeSubject': 'Welcome to {club}!',
  'sign.trialBody': 'Congratulations, {first}! Your trial convinced all of us — you are officially a {club} player.\n\nNobody will hand you anything here; you will earn every minute on the training ground. {city} lives for football, so wear the “{nick}” shirt with pride.\n\nNine o\'clock Monday morning at the training ground. Don\'t be late.',
  'sign.welcomeBody': '{first}, welcome aboard. You know why we signed you; now I expect you to show it on the pitch every week.\n\n{city} lives for football, and the fans love a player who sweats for the “{nick}” shirt. My door is always open.',
  'sign.renewSubject': 'Pen to paper with {club}',
  'sign.renewBody': 'The board has approved your new deal: {years} years, {wage} a week. We believe in you, {name}.',

  'neg.opening': '{club} have put their opening offer on the table.',
  'neg.agent.low': '{agent}: “That is low. A player of your level earns around {fair} a week. Push them.”',
  'neg.agent.fair': '{agent}: “A reasonable offer — the market rate is about {fair}. We can ask for a bit more, but let\'s not overplay it.”',
  'neg.agent.generous': '{agent}: “Honestly, that is a generous offer — the market rate is about {fair}. Play hard to get and they will walk.”',
  'neg.playerAsk': 'I\'m asking for {wage} a week, {years} years and a “{role}” role.',
  'neg.club.open': '{club}: “We have considered your request. Here is our revised offer.”',
  'neg.club.agreed': '{club}: “We have a deal. Get your pen ready.”',
  'neg.club.collapsed': '{club}: “We cannot continue on these terms. Talks are over.”',
  'neg.agreed': 'Terms agreed. Confirm to sign.',
  'neg.collapsed': 'Talks with {club} have collapsed.',
  'neg.collapsedSubject': '{club} walk away',
  'neg.collapsedBody': 'The directors of {club} found your demands too steep and withdrew the offer. Another door may open.',
  'neg.finalOffer': 'This is the club\'s final offer. Take it or walk away.',

  'goal.from': 'Career Goals',
  'goal.subject': 'Goal achieved!',
  'goal.body': 'You have achieved one of the goals you set yourself:\n\n— {goal}\n\nYour story keeps growing.',
  'goal.note': 'Goal achieved: {goal}',
  'trophy.subject': 'Champions! {trophy}',
  'trophy.body': 'You lifted the {trophy} in {season}. This is exactly the moment you dreamt of as a kid. Savour it.',
  'award.subject': 'Award: {award}',
  'award.body': 'The {award} for the {season} season is yours! {detail}',

  'season.from': 'Season Report',
  'season.summarySubject': '{season} season report card',
  'season.summaryBody': 'The {season} season is complete.\n\nClub: {club} (league position: {pos})\nApps: {apps} · Goals: {goals} · Assists: {assists}\nAverage rating: {avg}\nOverall: {ovr}\n\nSummer is here: the transfer window is open — and don\'t forget to rest.',
  'season.summaryNoRecord': 'The {season} season is over. You did not play an official match this season; a new season means a new chance.',
  'season.ended': '{season} season complete',
  'season.newSubject': 'The {season} season begins',
  'season.newBody': 'New season, new page, {first}. You are {age} and the {season} season is waiting. Pre-season camp has started — stay sharp and show the manager what you can do.',
  'season.started': 'The {season} season has started',

  'retire.forcedSubject': 'Time to say goodbye',
  'retire.forcedBody': '{first}, I will be straight with you: your body can no longer handle this pace, and the doctors agree. Let\'s plan your farewell from the Career screen — the greats leave the stage at the right time.',
  'retire.hintSubject': 'A conversation about the future',
  'retire.hintBody': '{first}, we have been together a long time. You can still play, but from now on you may retire whenever you choose. It is your call — whatever you decide, I have your back.',
  'retire.newsHeadline': 'End of an era: {name} retires',
  'retire.newsBody': '{name} has announced retirement from professional football, closing a career of {apps} appearances, {goals} goals and {trophies} trophies. The stands will miss this one for a long time.',
  'retire.inboxSubject': 'The final whistle',
  'retire.inboxBody': '{first}, today you hung up your boots. Being at your side all these years was an honour. Your documentary is ready — relive the whole story on the Legacy screen.',
  'retire.bioFallback': 'A football life, in numbers:\n\n{facts}',

  'report.pens': 'pens {h}-{a}',

  'callup.subject': 'National team call-up: {team}',
  'callup.firstBody': '{first}, on behalf of the coaching staff, we are calling you up to the {team} squad. It is the first international call-up of your career — wear the shirt with honour. {tournament}',
  'callup.body': '{first}, your form has not gone unnoticed. You are in the {team} squad for the upcoming internationals. {tournament}',
  'callup.tournament': 'A major tournament is around the corner — the whole nation is watching this squad.',
  'callup.note': 'Called up by {team}',

  'sponsor.subject': 'Sponsorship offer from {brand}',
  'sponsor.body': '{brand} want you as the new face of the brand ({category}).\n\nWeekly fee: {weekly}\nDuration: until the summer of {until}{req}\n\nAccept or decline the offer from this message.',
  'sponsor.req': '\nCondition: {req}',
  'sponsor.note': 'Sponsorship offer from {brand}',

  'bio.none': 'none',
  'bio.header': '{name} — {nation}, {pos}. Professional career: {from}–{to}.',
  'bio.clubs': 'Clubs: {clubs}',
  'bio.totals': 'Club career: {apps} appearances, {goals} goals, {assists} assists.',
  'bio.trophies': 'Trophies: {list}',
  'bio.awards': 'Individual awards: {list}',
  'bio.intl': 'International: {caps} caps, {goals} goals.',
  'bio.peak': 'Peak: overall {ovr}, market value {value}.',
  'bio.origin': 'Hometown: {town}. Childhood dream: {dream}',
  'bio.rival': 'Great rival: {rival} ({goals} career goals).',
  'bio.goals': 'Goals achieved: {list}',
  'bio.hof': 'Legend score: {score}',

  'events.note': 'New decisions waiting: {n}',
  'inbox.eventFrom': 'Life',
  'outlet.default': 'The Terrace Post',

  'genesis.unknownTown': 'a small town',
  'genesis.parentName': 'Daniel',
  'genesis.backstory': '{first} grew up on the edges of {town}, chasing a ball after school until the streetlights came on. The youngest on the block — but when the ball arrived, everyone went quiet. A standout {pos} at the local amateur club, it did not take long for the scouts to notice. Now there is only one question: how far can this talent go?',
  'genesis.motto': 'Sweat beats talent.',
  'genesis.dream': 'To score the winner in a final one day, in front of a packed stadium.',
  'genesis.destiny': 'There is a rare fire in those eyes — in the right hands, a very bright star.',
  'genesis.fatherPersonality': 'patient, proud, a man of few words',
  'genesis.motherName': 'Maria',
  'genesis.motherPersonality': 'warm, resilient, always calling',
  'genesis.motherBio': 'Calls before every match; cannot bear to watch, so she waits in the kitchen and prays.',
  'genesis.fatherBio': 'Worked night shifts all his life and saved up his days off so he would never miss a single match.',
  'genesis.agentPersonality': 'shrewd, loyal, phone never stops ringing',
  'genesis.agentBio': 'A former lower-league pro who now makes a living steering young talent to the right clubs.',
  'genesis.agentFallbackName': 'Frank Dorsey',
  'genesis.rivalBlurb': '{rival} ({club}) — same age, same position, and the papers are already comparing the two of you.',
};

registerStrings('game', { tr, en });
