export const career = {
  tr: {
    'career.title': 'Kariyer',
    'career.subtitle': 'Rakamlar, kupalar ve hikâyen',
    'career.tab.overview': 'Genel',
    'career.tab.seasons': 'Sezonlar',
    'career.tab.trophies': 'Kupalar',
    'career.tab.matches': 'Maçlar',
    'career.age': '{n} yaş',
    'career.stat.apps': 'Maç',
    'career.stat.goals': 'Gol',
    'career.stat.assists': 'Asist',
    'career.stat.rating': 'Maç Ortalaması',
    'career.stat.trophies': 'Kupa',
    'career.stat.caps': 'Milli Maç',
    'career.stat.capsSub': '{n} gol',
    'career.stat.value': 'Piyasa Değeri',
    'career.stat.peakSub': 'zirve {v}',
    'career.stat.seasons': 'Sezon',
    'career.stat.motm': 'Maçın Adamı',
    'career.radar': 'Oyuncu Haritası',
    'career.radarHint': 'Teknik, fiziksel ve zihinsel özelliklerin tek bakışta.',
    'career.chart.overall': 'Genel Güç',
    'career.chart.value': 'Piyasa Değeri',
    'career.chart.title': 'Gelişim Çizgisi',
    'career.chart.empty': 'İlk sezonun tamamlanınca çizgi oluşacak.',
    'career.chart.now': 'Şimdi',
    'career.traits': 'Karakter Özellikleri',
    'career.traitsEmpty': 'Henüz belirgin bir özelliğin yok.',
    'career.goals': 'Kariyer Hedefleri',
    'career.goalsEmpty': 'Henüz hedef belirlenmedi.',
    'career.goalDone': 'Tamamlandı · {a}/{b}',
    'career.table.season': 'Sezon',
    'career.table.club': 'Kulüp',
    'career.table.league': 'Lig',
    'career.table.pos': 'Sıra',
    'career.table.apps': 'Maç',
    'career.table.goals': 'Gol',
    'career.table.assists': 'Asist',
    'career.table.avg': 'Ort.',
    'career.table.ovr': 'Güç',
    'career.table.value': 'Değer',
    'career.table.trophies': 'Kupa',
    'career.table.current': 'devam ediyor',
    'career.table.empty': 'Henüz tamamlanmış bir sezonun yok. İlk sezonun bitince burada görünecek.',
    'career.cabinet': 'Kupa Dolabı',
    'career.cabinetEmpty': 'Dolap şimdilik boş. İlk kupa için daha çok çalış.',
    'career.awards': 'Ödüller',
    'career.awardsEmpty': 'Henüz bireysel ödülün yok.',
    'career.matchLog': 'Son Maçlar',
    'career.matchEmpty': 'Henüz maç oynamadın.',
    'career.matchHome': 'İç saha',
    'career.matchAway': 'Deplasman',
    'career.motm': 'Maçın adamı',
    'career.form10': 'Son 10 maç',
    'career.min': "{n} dk",
    'career.award.golden_ball': 'Altın Top',
    'career.award.league_top_scorer': 'Gol Kralı',
    'career.award.young_player': 'Yılın Genç Oyuncusu',
    'career.award.league_mvp': 'Ligin En Değerli Oyuncusu',
    'career.award.team_of_season': 'Sezonun 11\'i',
    'career.setPieces': 'Duran Top',
    'career.sp.freeKicks': 'Serbest vuruş',
    'career.sp.penalties': 'Penaltı',
    'career.sp.corners': 'Korner',
    'career.theme': 'Bu kariyerin teması',
    'career.motto': 'Sloganın',
  },
  en: {
    'career.title': 'Career',
    'career.subtitle': 'The numbers, the silverware and your story',
    'career.tab.overview': 'Overview',
    'career.tab.seasons': 'Seasons',
    'career.tab.trophies': 'Trophies',
    'career.tab.matches': 'Matches',
    'career.age': 'Age {n}',
    'career.stat.apps': 'Apps',
    'career.stat.goals': 'Goals',
    'career.stat.assists': 'Assists',
    'career.stat.rating': 'Avg Rating',
    'career.stat.trophies': 'Trophies',
    'career.stat.caps': 'Caps',
    'career.stat.capsSub': '{n} goals',
    'career.stat.value': 'Market Value',
    'career.stat.peakSub': 'peak {v}',
    'career.stat.seasons': 'Seasons',
    'career.stat.motm': 'Man of the Match',
    'career.radar': 'Player Map',
    'career.radarHint': 'Technical, physical and mental attributes at a glance.',
    'career.chart.overall': 'Overall',
    'career.chart.value': 'Market Value',
    'career.chart.title': 'Development Curve',
    'career.chart.empty': 'The curve appears once your first season is complete.',
    'career.chart.now': 'Now',
    'career.traits': 'Traits',
    'career.traitsEmpty': 'No standout traits yet.',
    'career.goals': 'Career Goals',
    'career.goalsEmpty': 'No goals set yet.',
    'career.goalDone': 'Completed · {a}/{b}',
    'career.table.season': 'Season',
    'career.table.club': 'Club',
    'career.table.league': 'League',
    'career.table.pos': 'Pos',
    'career.table.apps': 'Apps',
    'career.table.goals': 'Goals',
    'career.table.assists': 'Ast',
    'career.table.avg': 'Avg',
    'career.table.ovr': 'OVR',
    'career.table.value': 'Value',
    'career.table.trophies': 'Trophies',
    'career.table.current': 'in progress',
    'career.table.empty': 'No completed seasons yet. They will appear here once your first season ends.',
    'career.cabinet': 'Trophy Cabinet',
    'career.cabinetEmpty': 'The cabinet is empty for now. Work harder for that first trophy.',
    'career.awards': 'Awards',
    'career.awardsEmpty': 'No individual awards yet.',
    'career.matchLog': 'Recent Matches',
    'career.matchEmpty': "You haven't played yet.",
    'career.matchHome': 'Home',
    'career.matchAway': 'Away',
    'career.motm': 'Man of the match',
    'career.form10': 'Last 10 matches',
    'career.min': "{n} min",
    'career.award.golden_ball': 'Golden Ball',
    'career.award.league_top_scorer': 'Top Scorer',
    'career.award.young_player': 'Young Player of the Year',
    'career.award.league_mvp': 'League MVP',
    'career.award.team_of_season': 'Team of the Season',
    'career.setPieces': 'Set Pieces',
    'career.sp.freeKicks': 'Free kicks',
    'career.sp.penalties': 'Penalties',
    'career.sp.corners': 'Corners',
    'career.theme': 'Theme of this career',
    'career.motto': 'Your motto',
  },
};
