export const club = {
  tr: {
    'club.title': 'Kulüp',
    'club.subtitle': 'Kadro, teknik direktör ve kulüp tarihi',
    'club.viewing': 'Başka bir kulübü inceliyorsun',
    'club.backToMine': 'Kulübüne dön',
    'club.noClub.title': 'Şu an bir kulübün yok',
    'club.noClub.text': 'Bir takımla anlaştığında kadroyu, hocanı ve kulübün tarihini burada göreceksin.',
    'club.noClub.cta': 'Transferlere Git',
    'club.founded': 'Kuruluş {y}',
    'club.capacity': '{n} kişilik',
    'club.rank': 'Lig Sırası',
    'club.rankN': '{n}.',
    'club.points': '{n} puan',
    'club.record': '{w}G {d}B {l}M',
    'club.noTable': 'Sezon henüz başlamadı',
    'club.reputation': 'Prestij',
    'club.facilities': 'Tesisler',
    'club.youth': 'Altyapı',
    'club.budget': 'Transfer Bütçesi',
    'club.wageBudget': 'Haftalık Maaş Bütçesi',
    'club.formation': 'Diziliş',
    'club.style': 'Oyun Stili',
    'club.manager': 'Teknik Direktör',
    'club.managerAge': '{n} yaşında',
    'club.managerTrust': 'Gençlere Güven',
    'club.managerRep': 'Saygınlık',
    'club.managerRel': 'Seninle İlişkisi',
    'club.temper.calm': 'Soğukkanlı, odasında bağırmaz; planına güvenir.',
    'club.temper.fiery': 'Devre arasında kapıları çarpar; tutkusu sınır tanımaz.',
    'club.temper.demanding': 'Her antrenmanda en iyisini bekler, kolay övgü dağıtmaz.',
    'club.temper.mentor': 'Genç oyuncuların elinden tutar, hatalarını öğretiye çevirir.',
    'club.temper.pragmatic': 'Güzel oyundan çok sonuca bakar; işe yarayanı oynatır.',
    'club.squad': 'Kadro',
    'club.squadSize': '{n} oyuncu',
    'club.avgOvr': 'Ort. Güç',
    'club.avgAge': 'Ort. Yaş',
    'club.totalValue': 'Kadro Değeri',
    'club.injured': 'Sakat',
    'club.col.player': 'Oyuncu',
    'club.col.ovr': 'Güç',
    'club.col.form': 'Form',
    'club.col.value': 'Değer',
    'club.you': 'SEN',
    'club.injuredFor': '{n} hf. sakat',
    'club.age': '{n} yaş',
    'club.yourRank': 'Kadro sıran: {n}/{total}',
    'club.derbies': 'Derbi Rakipleri',
    'club.noDerbies': 'Bu kulübün belirgin bir derbi rakibi yok.',
    'club.derbyTag': 'DERBİ',
    'club.honours': 'Şampiyonluklar',
    'club.noHonours': 'Henüz kayıtlı bir şampiyonluk yok. Bu belki de senin çağın olur.',
    'club.titles': '{n} kez',
    'club.openClub': 'Kulübü incele',
  },
  en: {
    'club.title': 'Club',
    'club.subtitle': 'Squad, manager and club history',
    'club.viewing': 'You are looking at another club',
    'club.backToMine': 'Back to my club',
    'club.noClub.title': 'You have no club right now',
    'club.noClub.text': 'Once you sign for a team, its squad, manager and history will show up here.',
    'club.noClub.cta': 'Go to Transfers',
    'club.founded': 'Founded {y}',
    'club.capacity': '{n} seats',
    'club.rank': 'League Position',
    'club.rankN': '{n}',
    'club.points': '{n} pts',
    'club.record': '{w}W {d}D {l}L',
    'club.noTable': 'Season not started yet',
    'club.reputation': 'Prestige',
    'club.facilities': 'Facilities',
    'club.youth': 'Academy',
    'club.budget': 'Transfer Budget',
    'club.wageBudget': 'Weekly Wage Budget',
    'club.formation': 'Formation',
    'club.style': 'Playing Style',
    'club.manager': 'Manager',
    'club.managerAge': 'Aged {n}',
    'club.managerTrust': 'Trust in Youth',
    'club.managerRep': 'Reputation',
    'club.managerRel': 'Relationship with You',
    'club.temper.calm': 'Keeps cool in the dressing room and trusts the plan.',
    'club.temper.fiery': 'Slams doors at half-time; his passion knows no limits.',
    'club.temper.demanding': 'Expects your best every session and rarely hands out praise.',
    'club.temper.mentor': 'Takes young players by the hand and turns mistakes into lessons.',
    'club.temper.pragmatic': 'Cares more about results than beauty; plays whatever works.',
    'club.squad': 'Squad',
    'club.squadSize': '{n} players',
    'club.avgOvr': 'Avg. Rating',
    'club.avgAge': 'Avg. Age',
    'club.totalValue': 'Squad Value',
    'club.injured': 'Injured',
    'club.col.player': 'Player',
    'club.col.ovr': 'OVR',
    'club.col.form': 'Form',
    'club.col.value': 'Value',
    'club.you': 'YOU',
    'club.injuredFor': 'Out {n} wk',
    'club.age': 'Age {n}',
    'club.yourRank': 'Your squad rank: {n}/{total}',
    'club.derbies': 'Derby Rivals',
    'club.noDerbies': 'This club has no notable derby rival.',
    'club.derbyTag': 'DERBY',
    'club.honours': 'Honours',
    'club.noHonours': 'No recorded titles yet. Perhaps this will be your era.',
    'club.titles': '{n}×',
    'club.openClub': 'View club',
  },
};
