export const common = {
  tr: {
    'noCareer.title': 'Aktif bir kariyer yok',
    'noCareer.text': 'Bu ekran için önce bir kariyer başlat ya da kayıtlı bir kariyeri yükle.',
    'noCareer.cta': 'Ana Menü',
    'unavailable.title': 'Şu an yüklenemedi',
    'unavailable.text': 'Bu bölümün verisi henüz hazır değil. Birazdan tekrar dene.',
    'free': 'Bedelsiz',
    'noClub': 'Kulüpsüz',
    'seeAll': 'Tümünü gör',
    'close': 'Kapat',
    'weekShort': 'H{n}',
    'season': '{a}/{b}',
    'ratingShort': 'Ort.',
    'effect.money': 'Para',
    'effect.fame': 'Şöhret',
    'effect.followers': 'Takipçi',
    'effect.energy': 'Enerji',
    'effect.morale': 'Moral',
    'effect.form': 'Form',
    'effect.injury': 'Sakatlık',
    'perk.energyRegen': 'Enerji yenilenmesi',
    'perk.trainingBoost': 'Antrenman gelişimi',
    'perk.fameWeekly': 'Haftalık şöhret',
    'perk.morale': 'Moral',
    'perk.injuryResist': 'Sakatlık direnci',
    'style.possession': 'Topa Sahip Olma', 'style.counter': 'Kontra Atak', 'style.direct': 'Direkt Oyun', 'style.pressing': 'Yüksek Pres', 'style.balanced': 'Dengeli', 'style.defensive': 'Savunma Ağırlıklı',
    'temper.calm': 'Sakin', 'temper.fiery': 'Ateşli', 'temper.demanding': 'Talepkar', 'temper.mentor': 'Akıl Hocası', 'temper.pragmatic': 'Pragmatik',
    'pos.GK': 'Kaleci', 'pos.DEF': 'Defans', 'pos.MID': 'Orta Saha', 'pos.ATT': 'Forvet',
  },
  en: {
    'noCareer.title': 'No active career',
    'noCareer.text': 'Start a new career or load a saved one to use this screen.',
    'noCareer.cta': 'Main Menu',
    'unavailable.title': 'Could not load right now',
    'unavailable.text': 'The data for this section is not ready yet. Try again in a moment.',
    'free': 'Free',
    'noClub': 'No club',
    'seeAll': 'See all',
    'close': 'Close',
    'weekShort': 'W{n}',
    'season': '{a}/{b}',
    'ratingShort': 'Avg',
    'effect.money': 'Money',
    'effect.fame': 'Fame',
    'effect.followers': 'Followers',
    'effect.energy': 'Energy',
    'effect.morale': 'Morale',
    'effect.form': 'Form',
    'effect.injury': 'Injury',
    'perk.energyRegen': 'Energy recovery',
    'perk.trainingBoost': 'Training gains',
    'perk.fameWeekly': 'Weekly fame',
    'perk.morale': 'Morale',
    'perk.injuryResist': 'Injury resistance',
    'style.possession': 'Possession', 'style.counter': 'Counter-attack', 'style.direct': 'Direct', 'style.pressing': 'High Press', 'style.balanced': 'Balanced', 'style.defensive': 'Defensive',
    'temper.calm': 'Calm', 'temper.fiery': 'Fiery', 'temper.demanding': 'Demanding', 'temper.mentor': 'Mentor', 'temper.pragmatic': 'Pragmatic',
    'pos.GK': 'Goalkeepers', 'pos.DEF': 'Defenders', 'pos.MID': 'Midfielders', 'pos.ATT': 'Forwards',
  },
};
