export const competitions = {
  tr: {
    'comp.title': 'Turnuvalar',
    'comp.subtitle': 'Ligler, kupalar ve kıtanın gecesi',
    'comp.browse': 'Tüm Ligler',
    'comp.mine': 'Takımın',
    'comp.tab.table': 'Puan Durumu',
    'comp.tab.fixtures': 'Fikstür',
    'comp.tab.scorers': 'Gol Krallığı',
    'comp.tab.bracket': 'Eşleşmeler',
    'comp.tab.groups': 'Gruplar',
    'comp.tab.knockout': 'Eleme Turları',
    'comp.col.team': 'Takım',
    'comp.col.played': 'Oynanan',
    'comp.col.won': 'Galibiyet',
    'comp.col.drawn': 'Beraberlik',
    'comp.col.lost': 'Mağlubiyet',
    'comp.col.gf': 'Atılan gol',
    'comp.col.ga': 'Yenilen gol',
    'comp.col.gd': 'Averaj',
    'comp.col.pts': 'Puan',
    'comp.abbr.played': 'O',
    'comp.abbr.won': 'G',
    'comp.abbr.drawn': 'B',
    'comp.abbr.lost': 'M',
    'comp.abbr.gf': 'AG',
    'comp.abbr.ga': 'YG',
    'comp.abbr.gd': 'AV',
    'comp.abbr.pts': 'P',
    'comp.zone.title': 'Şampiyon',
    'comp.zone.continental': 'Avrupa kupası',
    'comp.zone.promotion': 'Yükselme',
    'comp.zone.relegation': 'Düşme',
    'comp.zone.qualify': 'Gruptan çıkar',
    'comp.stage.R64': 'Son 64',
    'comp.stage.R32': 'Son 32',
    'comp.stage.R16': 'Son 16',
    'comp.stage.QF': 'Çeyrek Final',
    'comp.stage.SF': 'Yarı Final',
    'comp.stage.F': 'Final',
    'comp.group': 'Grup {g}',
    'comp.weekN': 'Hafta {n}',
    'comp.thisWeek': 'Bu hafta',
    'comp.noFixtures': 'Bu organizasyonda henüz fikstür yok.',
    'comp.noTable': 'Puan durumu henüz oluşmadı.',
    'comp.noScorers': 'Henüz gol atan yok.',
    'comp.noBracket': 'Eşleşmeler henüz belli değil.',
    'comp.noCompetitions': 'Takımın şu an hiçbir organizasyonda yer almıyor.',
    'comp.unavailable': 'Bu organizasyon verisi şu an yüklenemedi.',
    'comp.goals': 'Gol',
    'comp.assists': 'Asist',
    'comp.pens': 'pen. {h}-{a}',
    'comp.tbd': 'Belli değil',
    'comp.winner': 'Şampiyon',
    'comp.stageNow': 'Aşama',
    'comp.stageDone': 'Tamamlandı',
    'comp.stage.group': 'Grup aşaması',
    'comp.stage.league': 'Lig',
    'comp.stage.friendlies': 'Hazırlık ve eleme maçları',
    'comp.prize': 'Ödül havuzu',
    'comp.kind.league': 'Lig',
    'comp.kind.cup': 'Kupa',
    'comp.kind.continental': 'Kıtalararası',
    'comp.kind.international': 'Uluslararası',
    'comp.tier': '{n}. Lig',
    'comp.yourMatch': 'Senin maçın',
    'comp.expand': 'Gol detayları',
    'comp.you': 'Sen',
    'comp.pickLeague': 'Lig seç',
    'comp.leader': 'Lider',
    'comp.top2': 'İlk 2 tur atlar',
  },
  en: {
    'comp.title': 'Competitions',
    'comp.subtitle': 'Leagues, cups and the continent’s big nights',
    'comp.browse': 'All Leagues',
    'comp.mine': 'Your Team',
    'comp.tab.table': 'Table',
    'comp.tab.fixtures': 'Fixtures',
    'comp.tab.scorers': 'Top Scorers',
    'comp.tab.bracket': 'Bracket',
    'comp.tab.groups': 'Groups',
    'comp.tab.knockout': 'Knockout',
    'comp.col.team': 'Team',
    'comp.col.played': 'Played',
    'comp.col.won': 'Won',
    'comp.col.drawn': 'Drawn',
    'comp.col.lost': 'Lost',
    'comp.col.gf': 'Goals for',
    'comp.col.ga': 'Goals against',
    'comp.col.gd': 'Goal difference',
    'comp.col.pts': 'Points',
    'comp.abbr.played': 'P',
    'comp.abbr.won': 'W',
    'comp.abbr.drawn': 'D',
    'comp.abbr.lost': 'L',
    'comp.abbr.gf': 'GF',
    'comp.abbr.ga': 'GA',
    'comp.abbr.gd': 'GD',
    'comp.abbr.pts': 'Pts',
    'comp.zone.title': 'Champions',
    'comp.zone.continental': 'Continental cup',
    'comp.zone.promotion': 'Promotion',
    'comp.zone.relegation': 'Relegation',
    'comp.zone.qualify': 'Qualify',
    'comp.stage.R64': 'Round of 64',
    'comp.stage.R32': 'Round of 32',
    'comp.stage.R16': 'Round of 16',
    'comp.stage.QF': 'Quarter-finals',
    'comp.stage.SF': 'Semi-finals',
    'comp.stage.F': 'Final',
    'comp.group': 'Group {g}',
    'comp.weekN': 'Week {n}',
    'comp.thisWeek': 'This week',
    'comp.noFixtures': 'No fixtures in this competition yet.',
    'comp.noTable': 'The table is not ready yet.',
    'comp.noScorers': 'Nobody has scored yet.',
    'comp.noBracket': 'The ties are not set yet.',
    'comp.noCompetitions': 'Your team is not in any competition right now.',
    'comp.unavailable': 'This competition could not be loaded right now.',
    'comp.goals': 'Goals',
    'comp.assists': 'Assists',
    'comp.pens': 'pens {h}-{a}',
    'comp.tbd': 'TBD',
    'comp.winner': 'Champions',
    'comp.stageNow': 'Stage',
    'comp.stageDone': 'Completed',
    'comp.stage.group': 'Group stage',
    'comp.stage.league': 'League',
    'comp.stage.friendlies': 'Friendlies and qualifiers',
    'comp.prize': 'Prize pool',
    'comp.kind.league': 'League',
    'comp.kind.cup': 'Cup',
    'comp.kind.continental': 'Continental',
    'comp.kind.international': 'International',
    'comp.tier': 'Division {n}',
    'comp.yourMatch': 'Your match',
    'comp.expand': 'Goal details',
    'comp.you': 'You',
    'comp.pickLeague': 'Pick a league',
    'comp.leader': 'Leader',
    'comp.top2': 'Top 2 advance',
  },
};
