export const legacy = {
  tr: {
    'legacy.title': 'Miras',
    'legacy.subtitleDone': 'Perde kapandı; geriye bu hikâye kaldı',
    'legacy.subtitleLive': 'Şimdiye kadarki hikâyen',
    'legacy.hof': 'Efsaneler Salonu',
    'legacy.score': 'Miras Puanı',
    'legacy.tier.immortal': 'Efsane',
    'legacy.tier.great': 'Tarihin Büyüklerinden',
    'legacy.tier.star': 'Yıldız',
    'legacy.tier.respected': 'Saygın Kariyer',
    'legacy.tier.journeyman': 'Alt Lig Kahramanı',
    'legacy.tier.unknown': 'Anonim',
    'legacy.line.immortal': 'Adın tribünlerde nesilden nesile anlatılacak.',
    'legacy.line.great': 'Futbol tarihi senden söz etmeden yazılamaz.',
    'legacy.line.star': 'Bir dönemin yüzüydün; taraftar seni unutmayacak.',
    'legacy.line.respected': 'Emeğin, sahada ve soyunma odasında hep saygı gördü.',
    'legacy.line.journeyman': 'Büyük sahnelerde parlamadın ama gittiğin her kulübe dürüst emek verdin.',
    'legacy.line.unknown': 'Hikâyen daha yeni başlıyor ya da hiç yazılmadı.',
    'legacy.nextTier': 'Sıradaki unvan: {tier} · {n} puan kaldı',
    'legacy.topTier': 'Zirvedesin: bundan yükseği yok.',
    'legacy.badge.done': 'Kramponlar asıldı',
    'legacy.badge.live': 'Kariyer devam ediyor',
    'legacy.motto': 'Mottun',
    'legacy.retire.title': 'Kramponları Asma Vakti mi?',
    'legacy.retire.canText': 'Futbola veda edersen kariyerin burada sona erer ve biyografin yazılır. Bu işlem geri alınamaz.',
    'legacy.retire.cannotText': 'Henüz emekli olamazsın. 32 yaşından sonra ya da uzun bir sakatlıkta bu kapı açılır.',
    'legacy.retire.forced': 'Artık bırakman gerekiyor.',
    'legacy.retire.btn': 'Kramponları As',
    'legacy.retire.confirmTitle': 'Futbola veda?',
    'legacy.retire.confirmText': 'Son düdük çalacak. Kariyerin kapanacak ve geri dönüş olmayacak. Emin misin?',
    'legacy.retire.confirm': 'Evet, bırakıyorum',
    'legacy.retire.cancel': 'Biraz daha oynayayım',
    'legacy.retire.failed': 'Emeklilik işlemi tamamlanamadı. Birazdan tekrar dene.',
    'legacy.card.title': 'Kariyer Kartı',
    'legacy.card.copy': 'Özeti Kopyala',
    'legacy.card.share': 'Paylaş',
    'legacy.card.copied': 'Özet panoya kopyalandı',
    'legacy.card.copyFailed': 'Kopyalanamadı',
    'legacy.card.peak': 'Zirve Güç',
    'legacy.card.peakValue': 'Zirve Değer',
    'legacy.bio.title': 'Hayat Hikâyesi',
    'legacy.bio.writing': 'Biyografin yazılıyor…',
    'legacy.bio.writingSub': 'Maçların, kupaların ve vedaların tek bir hikâyede toplanıyor. Bu biraz sürebilir.',
    'legacy.bio.waiting': 'Biyografin emekli olduğun gün yazılır.',
    'legacy.timeline': 'Yolculuk',
    'legacy.timeline.empty': 'Henüz tamamlanmış bir sezon yok.',
    'legacy.timeline.now': 'Şimdi',
    'legacy.stint.line': '{apps} maç · {goals} gol · {assists} asist',
    'legacy.stint.trophies': '{n} kupa',
    'legacy.records': 'Rekorlar',
    'legacy.rec.bestSeasonGoals': 'Bir sezonda en çok gol',
    'legacy.rec.bestRating': 'En iyi sezon ortalaması',
    'legacy.rec.peakOverall': 'Zirve güç',
    'legacy.rec.peakValue': 'Zirve piyasa değeri',
    'legacy.rec.mostApps': 'Bir sezonda en çok maç',
    'legacy.rec.none': 'Henüz yok',
    'legacy.rec.in': '{a}/{b} sezonu',
    'legacy.rival': 'Rakibinle Hesaplaşma',
    'legacy.rivalGoals': 'Gol',
    'legacy.rivalApps': 'Maç',
    'legacy.rivalWon': 'Yaşıtın olan rakibini geride bıraktın.',
    'legacy.rivalLost': 'Rakibin senden daha çok gol attı ama hikâyeyi sen yazdın.',
    'legacy.rivalEven': 'İkiniz de başa baş gittiniz; tarih berabere dedi.',
    'legacy.newCareer': 'Yeni Kariyer',
    'legacy.newCareerHint': 'Yeni bir tohum, yeni bir dünya, yepyeni bir hikâye.',
    'legacy.backHub': 'Ana Merkez',
  },
  en: {
    'legacy.title': 'Legacy',
    'legacy.subtitleDone': 'The curtain has fallen; this is the story you leave behind',
    'legacy.subtitleLive': 'Your story so far',
    'legacy.hof': 'Hall of Fame',
    'legacy.score': 'Legacy Score',
    'legacy.tier.immortal': 'Immortal',
    'legacy.tier.great': 'All-time Great',
    'legacy.tier.star': 'Star',
    'legacy.tier.respected': 'Respected Career',
    'legacy.tier.journeyman': 'Journeyman',
    'legacy.tier.unknown': 'Unknown',
    'legacy.line.immortal': 'Your name will be sung from the stands for generations.',
    'legacy.line.great': 'The history of the game cannot be told without you.',
    'legacy.line.star': 'You were the face of an era; the fans will never forget you.',
    'legacy.line.respected': 'Your work earned respect on the pitch and in the dressing room.',
    'legacy.line.journeyman': 'You never ruled the big stages, but you gave every club an honest shift.',
    'legacy.line.unknown': 'Your story is only beginning, or was never told.',
    'legacy.nextTier': 'Next title: {tier} · {n} points to go',
    'legacy.topTier': 'You are at the very top: there is nothing higher.',
    'legacy.badge.done': 'Boots hung up',
    'legacy.badge.live': 'Career in progress',
    'legacy.motto': 'Your motto',
    'legacy.retire.title': 'Time to Hang Up the Boots?',
    'legacy.retire.canText': 'If you say goodbye to football your career ends here and your biography is written. This cannot be undone.',
    'legacy.retire.cannotText': 'You cannot retire yet. This door opens after age 32, or after a long-term injury.',
    'legacy.retire.forced': 'You have to retire now.',
    'legacy.retire.btn': 'Hang Up the Boots',
    'legacy.retire.confirmTitle': 'Say goodbye to football?',
    'legacy.retire.confirmText': 'The final whistle will blow. Your career will close and there is no way back. Are you sure?',
    'legacy.retire.confirm': 'Yes, I retire',
    'legacy.retire.cancel': 'Let me play on',
    'legacy.retire.failed': 'Retirement could not be completed. Try again shortly.',
    'legacy.card.title': 'Career Card',
    'legacy.card.copy': 'Copy Summary',
    'legacy.card.share': 'Share',
    'legacy.card.copied': 'Summary copied to the clipboard',
    'legacy.card.copyFailed': 'Could not copy',
    'legacy.card.peak': 'Peak Rating',
    'legacy.card.peakValue': 'Peak Value',
    'legacy.bio.title': 'Life Story',
    'legacy.bio.writing': 'Your biography is being written…',
    'legacy.bio.writingSub': 'Your matches, trophies and goodbyes are being woven into one story. This can take a moment.',
    'legacy.bio.waiting': 'Your biography is written on the day you retire.',
    'legacy.timeline': 'The Journey',
    'legacy.timeline.empty': 'No completed season yet.',
    'legacy.timeline.now': 'Now',
    'legacy.stint.line': '{apps} apps · {goals} goals · {assists} assists',
    'legacy.stint.trophies': '{n} trophies',
    'legacy.records': 'Records',
    'legacy.rec.bestSeasonGoals': 'Most goals in a season',
    'legacy.rec.bestRating': 'Best season average',
    'legacy.rec.peakOverall': 'Peak rating',
    'legacy.rec.peakValue': 'Peak market value',
    'legacy.rec.mostApps': 'Most appearances in a season',
    'legacy.rec.none': 'None yet',
    'legacy.rec.in': '{a}/{b} season',
    'legacy.rival': 'Showdown with Your Rival',
    'legacy.rivalGoals': 'Goals',
    'legacy.rivalApps': 'Apps',
    'legacy.rivalWon': 'You left your age-mate rival behind.',
    'legacy.rivalLost': 'Your rival scored more, but you wrote the better story.',
    'legacy.rivalEven': 'You went toe to toe; history called it a draw.',
    'legacy.newCareer': 'New Career',
    'legacy.newCareerHint': 'A new seed, a new world, a brand new story.',
    'legacy.backHub': 'Main Hub',
  },
};
