export const lifestyle = {
  tr: {
    'lifestyle.title': 'Yaşam Tarzı',
    'lifestyle.subtitle': 'Hafta {week} · {n} hamle kaldı',
    'lifestyle.tab.activities': 'Etkinlikler',
    'lifestyle.tab.shop': 'Mağaza',
    'lifestyle.tab.finances': 'Finans',
    'lifestyle.actions': 'Haftalık Hamle',
    'lifestyle.noActions': 'Bu hafta hamlen kalmadı. Haftayı ilerletince yenilenir.',
    'lifestyle.cat.all': 'Tümü',
    'lifestyle.cat.rest': 'Dinlenme',
    'lifestyle.cat.social': 'Sosyal',
    'lifestyle.cat.family': 'Aile',
    'lifestyle.cat.media': 'Medya',
    'lifestyle.cat.nightlife': 'Gece Hayatı',
    'lifestyle.cat.charity': 'Hayır İşleri',
    'lifestyle.cat.training': 'Antrenman',
    'lifestyle.cat.romance': 'Aşk',
    'lifestyle.do': 'Yap',
    'lifestyle.energyCost': 'Enerji −{n}',
    'lifestyle.energyGain': 'Enerji +{n}',
    'lifestyle.risk': 'Risk %{n}',
    'lifestyle.fameReq': 'Şöhret {n}+',
    'lifestyle.result': 'Son Etkinlik',
    'lifestyle.failed': 'Bu etkinlik şu an yapılamıyor.',
    'lifestyle.errored': 'Etkinlik gerçekleştirilemedi.',
    'lifestyle.empty': 'Bu kategoride etkinlik yok.',
    'lifestyle.shop.collection': 'Koleksiyonun',
    'lifestyle.shop.collectionEmpty': 'Henüz bir şeyin yok. İlk saatin, ilk arabanla başla.',
    'lifestyle.shop.totalValue': 'Toplam değer',
    'lifestyle.shop.totalUpkeep': 'Haftalık bakım',
    'lifestyle.shop.cat.all': 'Hepsi',
    'lifestyle.shop.cat.car': 'Araba',
    'lifestyle.shop.cat.house': 'Ev',
    'lifestyle.shop.cat.watch': 'Saat',
    'lifestyle.shop.cat.fashion': 'Moda',
    'lifestyle.shop.cat.tech': 'Teknoloji',
    'lifestyle.shop.cat.pet': 'Evcil Dost',
    'lifestyle.shop.cat.staff': 'Ekip',
    'lifestyle.shop.cat.boat': 'Tekne',
    'lifestyle.shop.cat.jet': 'Jet',
    'lifestyle.shop.cat.art': 'Sanat',
    'lifestyle.shop.tier.1': 'Standart',
    'lifestyle.shop.tier.2': 'Şık',
    'lifestyle.shop.tier.3': 'Premium',
    'lifestyle.shop.tier.4': 'Elit',
    'lifestyle.shop.tier.5': 'Efsanevi',
    'lifestyle.shop.buy': 'Satın Al',
    'lifestyle.shop.hire': 'İşe Al',
    'lifestyle.shop.sell': 'Sat',
    'lifestyle.shop.release': 'Yolla',
    'lifestyle.shop.owned': 'Sende',
    'lifestyle.shop.hired': 'Ekipte',
    'lifestyle.shop.locked': 'Şöhret {n} gerekli',
    'lifestyle.shop.upkeep': '{money}/hafta bakım',
    'lifestyle.shop.noUpkeep': 'Bakım yok',
    'lifestyle.shop.confirmBuy': '{name} için onay',
    'lifestyle.shop.confirmSell': '{name} elden çıkarılsın mı?',
    'lifestyle.shop.confirmSellText': 'Eşya satılır, bedeli hesabına yatar. Bu işlem geri alınamaz.',
    'lifestyle.shop.confirmReleaseText': 'Ekipten ayrılır, haftalık gideri biter. Geri dönmesi kolay olmaz.',
    'lifestyle.shop.price': 'Fiyat',
    'lifestyle.shop.refund': 'Geri dönecek tutar',
    'lifestyle.shop.balanceAfter': 'İşlem sonrası bakiye',
    'lifestyle.shop.bought': '{name} artık senin!',
    'lifestyle.shop.hiredToast': '{name} ekibe katıldı.',
    'lifestyle.shop.sold': '{name} elden çıktı: +{money}',
    'lifestyle.shop.cantAfford': 'Bakiyen yetmiyor',
    'lifestyle.shop.failed': 'Bu işlem yapılamadı.',
    'lifestyle.shop.empty': 'Bu kategoride ürün yok.',
    'lifestyle.shop.onBuy': 'Satın alınca',
    'fin.balance': 'Bakiye',
    'fin.weekly': 'Haftalık Akış',
    'fin.wage': 'Maaş',
    'fin.sponsors': 'Sponsorlar',
    'fin.upkeep': 'Bakım Giderleri',
    'fin.tax': 'Vergi',
    'fin.net': 'Haftalık Net',
    'fin.trend': 'Para Seyri',
    'fin.projection': '12 haftalık projeksiyon',
    'fin.history': 'Kayıtlı bakiye',
    'fin.sponsorsTitle': 'Sponsor Anlaşmaları',
    'fin.noSponsors': 'Henüz sponsorun yok. Şöhretin arttıkça markalar kapını çalacak.',
    'fin.until': '{season} sezonu sonuna kadar',
    'fin.perWeek': '{money}/hafta',
    'fin.contract': 'Sözleşme maaşı',
    'fin.incomeOut': 'Gelir',
    'fin.expenseOut': 'Gider',
  },
  en: {
    'lifestyle.title': 'Lifestyle',
    'lifestyle.subtitle': 'Week {week} · {n} actions left',
    'lifestyle.tab.activities': 'Activities',
    'lifestyle.tab.shop': 'Shop',
    'lifestyle.tab.finances': 'Finances',
    'lifestyle.actions': 'Weekly Actions',
    'lifestyle.noActions': 'No actions left this week. They refresh when the week advances.',
    'lifestyle.cat.all': 'All',
    'lifestyle.cat.rest': 'Rest',
    'lifestyle.cat.social': 'Social',
    'lifestyle.cat.family': 'Family',
    'lifestyle.cat.media': 'Media',
    'lifestyle.cat.nightlife': 'Nightlife',
    'lifestyle.cat.charity': 'Charity',
    'lifestyle.cat.training': 'Training',
    'lifestyle.cat.romance': 'Romance',
    'lifestyle.do': 'Do it',
    'lifestyle.energyCost': 'Energy −{n}',
    'lifestyle.energyGain': 'Energy +{n}',
    'lifestyle.risk': '{n}% risk',
    'lifestyle.fameReq': 'Fame {n}+',
    'lifestyle.result': 'Latest Activity',
    'lifestyle.failed': 'You cannot do this right now.',
    'lifestyle.errored': 'The activity could not be completed.',
    'lifestyle.empty': 'No activities in this category.',
    'lifestyle.shop.collection': 'Your Collection',
    'lifestyle.shop.collectionEmpty': 'Nothing yet. Start with your first watch or car.',
    'lifestyle.shop.totalValue': 'Total value',
    'lifestyle.shop.totalUpkeep': 'Weekly upkeep',
    'lifestyle.shop.cat.all': 'Everything',
    'lifestyle.shop.cat.car': 'Cars',
    'lifestyle.shop.cat.house': 'Homes',
    'lifestyle.shop.cat.watch': 'Watches',
    'lifestyle.shop.cat.fashion': 'Fashion',
    'lifestyle.shop.cat.tech': 'Tech',
    'lifestyle.shop.cat.pet': 'Pets',
    'lifestyle.shop.cat.staff': 'Staff',
    'lifestyle.shop.cat.boat': 'Boats',
    'lifestyle.shop.cat.jet': 'Jets',
    'lifestyle.shop.cat.art': 'Art',
    'lifestyle.shop.tier.1': 'Standard',
    'lifestyle.shop.tier.2': 'Stylish',
    'lifestyle.shop.tier.3': 'Premium',
    'lifestyle.shop.tier.4': 'Elite',
    'lifestyle.shop.tier.5': 'Legendary',
    'lifestyle.shop.buy': 'Buy',
    'lifestyle.shop.hire': 'Hire',
    'lifestyle.shop.sell': 'Sell',
    'lifestyle.shop.release': 'Let go',
    'lifestyle.shop.owned': 'Owned',
    'lifestyle.shop.hired': 'On the team',
    'lifestyle.shop.locked': 'Needs fame {n}',
    'lifestyle.shop.upkeep': '{money}/week upkeep',
    'lifestyle.shop.noUpkeep': 'No upkeep',
    'lifestyle.shop.confirmBuy': 'Confirm: {name}',
    'lifestyle.shop.confirmSell': 'Sell {name}?',
    'lifestyle.shop.confirmSellText': 'The item is sold and the proceeds go to your account. This cannot be undone.',
    'lifestyle.shop.confirmReleaseText': 'They leave the team and the weekly cost stops. Getting them back will not be easy.',
    'lifestyle.shop.price': 'Price',
    'lifestyle.shop.refund': 'You get back',
    'lifestyle.shop.balanceAfter': 'Balance after',
    'lifestyle.shop.bought': '{name} is yours!',
    'lifestyle.shop.hiredToast': '{name} joined your team.',
    'lifestyle.shop.sold': '{name} sold: +{money}',
    'lifestyle.shop.cantAfford': 'You cannot afford this',
    'lifestyle.shop.failed': 'That did not go through.',
    'lifestyle.shop.empty': 'Nothing in this category.',
    'lifestyle.shop.onBuy': 'On purchase',
    'fin.balance': 'Balance',
    'fin.weekly': 'Weekly Cash Flow',
    'fin.wage': 'Wage',
    'fin.sponsors': 'Sponsors',
    'fin.upkeep': 'Upkeep',
    'fin.tax': 'Tax',
    'fin.net': 'Weekly Net',
    'fin.trend': 'Money Trend',
    'fin.projection': '12-week projection',
    'fin.history': 'Recorded balance',
    'fin.sponsorsTitle': 'Sponsor Deals',
    'fin.noSponsors': 'No sponsors yet. Brands will come knocking as your fame grows.',
    'fin.until': 'Until the end of {season}',
    'fin.perWeek': '{money}/week',
    'fin.contract': 'Contract wage',
    'fin.incomeOut': 'Income',
    'fin.expenseOut': 'Costs',
  },
};
