export const media = {
  tr: {
    'news.title': 'Haberler',
    'news.subtitle': 'Manşetlerde senin adın var mı?',
    'news.edition': 'Sezon {a}/{b} · Hafta {n}',
    'news.issue': 'Sayı {n}',
    'news.sections': 'Spor · Transfer · Magazin',
    'news.top': 'Manşet',
    'news.more': 'Diğer Haberler',
    'news.empty': 'Henüz haber yok. Maçlar oynandıkça gazeteler seni yazacak.',
    'news.read': 'Haberi Oku',
    'news.continue': 'Devamını oku',
    'news.about': 'Senin hakkında',
    'news.week': 'Hafta {n}',
    'news.ai': 'AI',
    'news.aiTitle': 'Bu haberi Claude yazdı',
    'news.filter.all': 'Tümü',
    'news.loadMore': 'Daha fazla haber',
    'news.tag.user': 'Sen',
    'news.tag.transfer': 'Transfer',
    'news.tag.match': 'Maç',
    'news.tag.league': 'Lig',
    'news.tag.rival': 'Rakip',
    'news.tag.scandal': 'Skandal',
    'news.tag.press': 'Basın',
    'news.tag.contract': 'Sözleşme',
    'news.tag.injury': 'Sakatlık',
    'news.tag.retirement': 'Emeklilik',
    'news.tag.award': 'Ödül',
    'news.tag.cup': 'Kupa',
    'news.tag.derby': 'Derbi',
    'news.tag.continental': 'Avrupa',
    'news.tag.international': 'Milli Takım',
    'news.tag.family': 'Aile',
    'news.tag.story': 'Hikâye',
    'news.tag.manager': 'Teknik Direktör',
    'news.tag.sponsor': 'Sponsor',
    'news.tag.title': 'Şampiyonluk',
    'news.tag.record': 'Rekor',
    'social.title': 'Sosyal Medya',
    'social.subtitle': 'Takipçilerin ne diyor?',
    'social.followers': 'Takipçi',
    'social.fame': 'Şöhret',
    'social.compose': 'Ne düşünüyorsun?',
    'social.placeholder': 'Hayranlarınla bir şey paylaş…',
    'social.post': 'Paylaş',
    'social.posting': 'Paylaşılıyor…',
    'social.reactions': 'Tepkiler geliyor…',
    'social.posted': 'Paylaşımın yayında.',
    'social.error': 'Paylaşım yapılamadı.',
    'social.limitHint': 'Aşırı paylaşım etkisini azaltır; haftada birkaç gönderi idealdir.',
    'social.templates': 'Hazır taslaklar',
    'social.tpl.1': 'Bugün sahada elimden geleni yaptım. Tribünlere sonsuz teşekkürler!',
    'social.tpl.2': 'Çalışmaya devam. Her antrenman bir basamak.',
    'social.tpl.3': 'Hafta sonu maçı için sabırsızlanıyorum. Hazırız!',
    'social.tpl.4': 'Ailem ve sizler olmadan hiçbir şey olamazdı. Hepinize teşekkürler.',
    'social.tpl.5': 'Kritik bir maç, tek hedef var: üç puan.',
    'social.filter.all': 'Tümü',
    'social.filter.fan': 'Taraftar',
    'social.filter.media': 'Medya',
    'social.filter.football': 'Futbol',
    'social.filter.mine': 'Benim',
    'social.kind.fan': 'Taraftar',
    'social.kind.journalist': 'Gazeteci',
    'social.kind.player': 'Futbolcu',
    'social.kind.club': 'Kulüp',
    'social.kind.rival': 'Rakip',
    'social.kind.partner': 'Partner',
    'social.kind.user': 'Sen',
    'social.kind.pundit': 'Yorumcu',
    'social.kind.brand': 'Marka',
    'social.empty': 'Akış sessiz. İlk paylaşımı sen yap.',
    'social.verified': 'Onaylı hesap',
    'social.now': 'şimdi',
    'social.weeksAgo': '{n} hf',
    'social.repost': 'Paylaşım',
    'social.like': 'Beğeni',
    'social.mood.good': 'Olumlu',
    'social.mood.bad': 'Olumsuz',
    'social.more': 'Daha fazla göster',
  },
  en: {
    'news.title': 'News',
    'news.subtitle': 'Is your name on the front page?',
    'news.edition': 'Season {a}/{b} · Week {n}',
    'news.issue': 'Issue {n}',
    'news.sections': 'Sport · Transfers · Gossip',
    'news.top': 'Front Page',
    'news.more': 'More Stories',
    'news.empty': 'No news yet. The papers will write about you as the matches go by.',
    'news.read': 'Read story',
    'news.continue': 'Continue reading',
    'news.about': 'About you',
    'news.week': 'Week {n}',
    'news.ai': 'AI',
    'news.aiTitle': 'This story was written by Claude',
    'news.filter.all': 'All',
    'news.loadMore': 'More stories',
    'news.tag.user': 'You',
    'news.tag.transfer': 'Transfers',
    'news.tag.match': 'Match',
    'news.tag.league': 'League',
    'news.tag.rival': 'Rival',
    'news.tag.scandal': 'Scandal',
    'news.tag.press': 'Press',
    'news.tag.contract': 'Contract',
    'news.tag.injury': 'Injury',
    'news.tag.retirement': 'Retirement',
    'news.tag.award': 'Awards',
    'news.tag.cup': 'Cup',
    'news.tag.derby': 'Derby',
    'news.tag.continental': 'Continental',
    'news.tag.international': 'National Team',
    'news.tag.family': 'Family',
    'news.tag.story': 'Story',
    'news.tag.manager': 'Manager',
    'news.tag.sponsor': 'Sponsor',
    'news.tag.title': 'Title',
    'news.tag.record': 'Record',
    'social.title': 'Social',
    'social.subtitle': 'What are your followers saying?',
    'social.followers': 'Followers',
    'social.fame': 'Fame',
    'social.compose': "What's on your mind?",
    'social.placeholder': 'Share something with your fans…',
    'social.post': 'Post',
    'social.posting': 'Posting…',
    'social.reactions': 'Reactions are coming in…',
    'social.posted': 'Your post is live.',
    'social.error': 'The post did not go through.',
    'social.limitHint': 'Posting too often waters down the effect; a few posts a week is ideal.',
    'social.templates': 'Quick drafts',
    'social.tpl.1': 'Gave everything on the pitch today. Endless thanks to the stands!',
    'social.tpl.2': 'Keep working. Every session is a step up.',
    'social.tpl.3': "Can't wait for the weekend game. We're ready!",
    'social.tpl.4': 'None of this happens without my family and you. Thank you all.',
    'social.tpl.5': 'A crucial match, one target: three points.',
    'social.filter.all': 'All',
    'social.filter.fan': 'Fans',
    'social.filter.media': 'Media',
    'social.filter.football': 'Football',
    'social.filter.mine': 'Mine',
    'social.kind.fan': 'Fan',
    'social.kind.journalist': 'Journalist',
    'social.kind.player': 'Player',
    'social.kind.club': 'Club',
    'social.kind.rival': 'Rival',
    'social.kind.partner': 'Partner',
    'social.kind.user': 'You',
    'social.kind.pundit': 'Pundit',
    'social.kind.brand': 'Brand',
    'social.empty': 'The feed is quiet. Be the first to post.',
    'social.verified': 'Verified account',
    'social.now': 'now',
    'social.weeksAgo': '{n}w',
    'social.repost': 'Reposts',
    'social.like': 'Likes',
    'social.mood.good': 'Positive',
    'social.mood.bad': 'Negative',
    'social.more': 'Show more',
  },
};
