export const people = {
  tr: {
    'people.title': 'İnsanlar',
    'people.subtitle': 'Seni sen yapan çevre',
    'people.relationships': 'İlişkiler',
    'people.circle': 'Çevren',
    'people.rel.manager': 'Forma şansını ve taktik güveni belirler.',
    'people.rel.teammates': 'Sahada sana pas atma isteklerini etkiler.',
    'people.rel.fans': 'Şöhretini ve tribün sevgisini taşır.',
    'people.rel.media': 'Manşetlerin tonunu belirler.',
    'people.rel.family': 'Moralin ve huzurun buradan gelir.',
    'people.rel.partner': 'Özel hayatın, moralin ve dengen.',
    'people.rel.agent': 'Gelen teklifleri ve pazarlık gücünü etkiler.',
    'people.rel.sponsors': 'Sponsor gelirlerinin sigortası.',
    'people.band.0': 'Soğuk',
    'people.band.1': 'Mesafeli',
    'people.band.2': 'Nezaketli',
    'people.band.3': 'Yakın',
    'people.band.4': 'Can Dost',
    'people.role.manager': 'Teknik Direktör',
    'people.role.mentor': 'Mentor',
    'people.role.rival': 'Rakip',
    'people.role.agent': 'Menajer',
    'people.role.father': 'Baba',
    'people.role.mother': 'Anne',
    'people.role.sibling': 'Kardeş',
    'people.role.partner': 'Partner',
    'people.role.friend': 'Arkadaş',
    'people.role.journalist': 'Gazeteci',
    'people.role.director': 'Sportif Direktör',
    'people.group.work': 'Kulüp ve Kariyer',
    'people.group.family': 'Aile ve Özel Hayat',
    'people.group.rival': 'Rekabet',
    'people.noPeople': 'Çevrende henüz kimse yok.',
    'people.message': 'Mesaj Yaz',
    'people.noChat': 'Mesajlaşma yok',
    'people.you': 'Sen',
    'people.rivalVs': 'Genel güç: {them} (sen {you})',
    'people.managerStyle': 'Oyun anlayışı',
    'people.trustsYouth': 'Gençlere güven',
    'people.mentorHint': 'Tecrübeli takım arkadaşın',
    'people.chat.empty': 'Henüz yazışma yok. İlk mesajı sen at.',
    'people.chat.placeholder': 'Bir mesaj yaz…',
    'people.chat.send': 'Gönder',
    'people.chat.typing': '{name} yazıyor…',
    'people.chat.error': 'Mesaj gönderilemedi, birazdan tekrar dene.',
    'people.chat.hint': 'Düzenli iletişim ilişkini güçlendirir (haftada bir kez).',
    'people.chat.ai': 'Yanıtları Claude yazıyor',
    'people.chat.template': 'Hazır yanıtlar',
    'people.quick.agent.1': 'Yeni bir teklif var mı?',
    'people.quick.agent.2': 'Sözleşmemi nasıl görüyorsun?',
    'people.quick.manager.1': 'Hocam, daha fazla süre istiyorum.',
    'people.quick.manager.2': 'Takıma nasıl katkı verebilirim?',
    'people.quick.mentor.1': 'Bana bir tavsiyen var mı?',
    'people.quick.mentor.2': 'Sen bu yaşta neler yaşadın?',
    'people.quick.partner.1': 'Bugün nasılsın?',
    'people.quick.partner.2': 'Hafta sonu bir şeyler yapalım mı?',
    'people.quick.family.1': 'Sizi çok özledim.',
    'people.quick.family.2': 'Her şey yolunda mı orada?',
    'people.quick.rival.1': 'Bu sezon seni geçeceğim.',
    'people.quick.rival.2': 'Dostça bir rekabet, değil mi?',
  },
  en: {
    'people.title': 'People',
    'people.subtitle': 'The circle that makes you who you are',
    'people.relationships': 'Relationships',
    'people.circle': 'Your Circle',
    'people.rel.manager': 'Decides your minutes and tactical trust.',
    'people.rel.teammates': 'Shapes how willingly they pass to you.',
    'people.rel.fans': 'Carries your fame and the love of the stands.',
    'people.rel.media': 'Sets the tone of the headlines.',
    'people.rel.family': 'Where your morale and peace come from.',
    'people.rel.partner': 'Your private life, morale and balance.',
    'people.rel.agent': 'Drives incoming offers and bargaining power.',
    'people.rel.sponsors': 'Insurance for your sponsorship income.',
    'people.band.0': 'Cold',
    'people.band.1': 'Distant',
    'people.band.2': 'Cordial',
    'people.band.3': 'Close',
    'people.band.4': 'Inseparable',
    'people.role.manager': 'Manager',
    'people.role.mentor': 'Mentor',
    'people.role.rival': 'Rival',
    'people.role.agent': 'Agent',
    'people.role.father': 'Father',
    'people.role.mother': 'Mother',
    'people.role.sibling': 'Sibling',
    'people.role.partner': 'Partner',
    'people.role.friend': 'Friend',
    'people.role.journalist': 'Journalist',
    'people.role.director': 'Sporting Director',
    'people.group.work': 'Club & Career',
    'people.group.family': 'Family & Private Life',
    'people.group.rival': 'Rivalry',
    'people.noPeople': 'Nobody in your circle yet.',
    'people.message': 'Message',
    'people.noChat': 'No messaging',
    'people.you': 'You',
    'people.rivalVs': 'Overall: {them} (you {you})',
    'people.managerStyle': 'Playing style',
    'people.trustsYouth': 'Trusts youth',
    'people.mentorHint': 'Your experienced teammate',
    'people.chat.empty': 'No messages yet. Send the first one.',
    'people.chat.placeholder': 'Write a message…',
    'people.chat.send': 'Send',
    'people.chat.typing': '{name} is typing…',
    'people.chat.error': 'Message failed, try again shortly.',
    'people.chat.hint': 'Keeping in touch strengthens the bond (once a week).',
    'people.chat.ai': 'Replies written by Claude',
    'people.chat.template': 'Built-in replies',
    'people.quick.agent.1': 'Any new offers?',
    'people.quick.agent.2': 'How do you see my contract?',
    'people.quick.manager.1': 'Boss, I want more minutes.',
    'people.quick.manager.2': 'How can I help the team more?',
    'people.quick.mentor.1': 'Any advice for me?',
    'people.quick.mentor.2': 'What did you go through at my age?',
    'people.quick.partner.1': 'How are you today?',
    'people.quick.partner.2': 'Shall we do something this weekend?',
    'people.quick.family.1': 'I miss you all so much.',
    'people.quick.family.2': 'Is everything okay back there?',
    'people.quick.rival.1': "I'm going to overtake you this season.",
    'people.quick.rival.2': 'Friendly rivalry, right?',
  },
};
