export const training = {
  tr: {
    'training.title': 'Antrenman',
    'training.subtitle': 'Hafta {week} · {club}',
    'training.overallLabel': 'Genel Güç',
    'training.facilities': 'Tesis Kalitesi',
    'training.boost': 'Ekipman Bonusu',
    'training.energyNow': 'Enerji',
    'training.destiny': 'Hocanın Fısıltısı',
    'training.focus': 'Haftalık Odak',
    'training.focusHint': 'Seçtiğin program her hafta otomatik uygulanır. Fizik çalışmaları daha çok enerji götürür.',
    'training.active': 'Aktif',
    'training.intensity': 'Yoğunluk',
    'training.focusSet': '{name} programına geçtin.',
    'training.attributes': 'Özellikler',
    'training.group.technical': 'Teknik',
    'training.group.physical': 'Fiziksel',
    'training.group.mental': 'Zihinsel',
    'training.nextPoint': 'Sonraki puana {pct}%',
    'training.focusAttr': 'Bu haftanın odağı',
    'training.xpLegend': 'Sonraki puana ilerleme',
    'training.recent': 'Son Gelişim',
    'training.recentWeek': 'Hafta {week} raporu',
    'training.recentEmpty': 'Henüz bir gelişme yok. Programını seç, haftayı ilerlet; sahada da puan topla.',
    'training.drills': 'Özel Çalışmalar',
    'training.drillsHint': 'Haftada bir kez, küçük bir enerji karşılığında. Skorun ne kadar yüksekse o kadar çok deneyim puanı.',
    'training.drill.drill_free_kick.name': 'Serbest Vuruş',
    'training.drill.drill_free_kick.desc': 'Barajın üstünden, falsoyla köşeye. Bilek, nefes ve sabır.',
    'training.drill.drill_finishing.name': 'Bitiricilik',
    'training.drill.drill_finishing.desc': 'Ceza sahasında art arda şutlar. Kaleciyi yan, sertliği doğru seç.',
    'training.drill.drill_passing.name': 'Pas Çalışması',
    'training.drill.drill_passing.desc': 'Dar alanda hedeflere pas. Sağ ayak, sol ayak, ilk dokunuş.',
    'training.drillDone': 'Bu hafta tamamlandı',
    'training.drillStart': 'Başla',
    'training.drillCost': '~2 enerji',
    'training.drillTrains': 'Geliştirir',
    'training.retired': 'Kramponlar asıldı; antrenman sahası artık sessiz.',
    'training.intensity.1': 'Hafif',
    'training.intensity.2': 'Orta',
    'training.intensity.3': 'Yüklü',
    'training.intensity.4': 'Ağır',
  },
  en: {
    'training.title': 'Training',
    'training.subtitle': 'Week {week} · {club}',
    'training.overallLabel': 'Overall',
    'training.facilities': 'Facilities',
    'training.boost': 'Gear Bonus',
    'training.energyNow': 'Energy',
    'training.destiny': "Coach's Whisper",
    'training.focus': 'Weekly Focus',
    'training.focusHint': 'Your chosen programme runs automatically every week. Physical work costs the most energy.',
    'training.active': 'Active',
    'training.intensity': 'Load',
    'training.focusSet': 'Switched to {name}.',
    'training.attributes': 'Attributes',
    'training.group.technical': 'Technical',
    'training.group.physical': 'Physical',
    'training.group.mental': 'Mental',
    'training.nextPoint': '{pct}% to next point',
    'training.focusAttr': "This week's focus",
    'training.xpLegend': 'Progress to next point',
    'training.recent': 'Recent Progress',
    'training.recentWeek': 'Week {week} report',
    'training.recentEmpty': 'Nothing yet. Pick a programme, play the week, and earn points on the pitch as well.',
    'training.drills': 'Special Drills',
    'training.drillsHint': 'Once a week for a small energy cost. The higher your score, the more experience you earn.',
    'training.drill.drill_free_kick.name': 'Free Kicks',
    'training.drill.drill_free_kick.desc': 'Over the wall, curled into the corner. Wrist, breath and patience.',
    'training.drill.drill_finishing.name': 'Finishing',
    'training.drill.drill_finishing.desc': 'Back-to-back shots in the box. Pick your corner and your power.',
    'training.drill.drill_passing.name': 'Passing Drill',
    'training.drill.drill_passing.desc': 'Pick out targets in tight spaces. Both feet, first touch.',
    'training.drillDone': 'Done this week',
    'training.drillStart': 'Start',
    'training.drillCost': '~2 energy',
    'training.drillTrains': 'Trains',
    'training.retired': 'The boots are on the wall; the training pitch is quiet now.',
    'training.intensity.1': 'Light',
    'training.intensity.2': 'Medium',
    'training.intensity.3': 'Heavy',
    'training.intensity.4': 'Brutal',
  },
};
