export const transfers = {
  tr: {
    'transfers.title': 'Transferler',
    'transfers.subtitle': 'Sözleşmen, teklifler ve pazarlık masası',
    'transfers.windowOpen': 'Transfer dönemi açık',
    'transfers.windowClosed': 'Transfer dönemi kapalı',
    'transfers.contract': 'Mevcut Sözleşme',
    'transfers.noContract': 'Şu an kulüpsüzsün. Teklifleri değerlendir ve yeni bir yuva bul.',
    'transfers.yearsLeft': '{n} yıl kaldı',
    'transfers.endsThisSeason': 'Bu sezon bitiyor',
    'transfers.loanFrom': '{club} kulübünün oyuncusu, kiralıksın',
    'transfers.bonuses': 'Primler',
    'transfers.perGoal': 'gol başı',
    'transfers.perApp': 'maç başı',
    'transfers.noClause': 'Yok',
    'transfers.clause': 'Serbest Kalma Bedeli',
    'transfers.list.title': 'Transfer Listesi',
    'transfers.list.desc': 'Listeye girersen kulüpler seni daha kolay bırakır, teklifler artar. Ama teknik direktör ve taraftar bundan hoşlanmaz.',
    'transfers.list.on': 'Listede',
    'transfers.list.off': 'Listede değil',
    'transfers.list.toastOn': 'Transfer listesine girdin. Kulüpler seni konuşacak.',
    'transfers.list.toastOff': 'Transfer listesinden çıktın.',
    'transfers.offers': 'Teklifler',
    'transfers.offersEmpty': 'Masada teklif yok. Formunu koru, şöhretini büyüt; kulüpler seni izliyor.',
    'transfers.history': 'Geçmiş Teklifler',
    'transfers.historyHide': 'Gizle',
    'transfers.historyShow': 'Göster',
    'transfers.kind.transfer': 'Transfer',
    'transfers.kind.loan': 'Kiralık',
    'transfers.kind.free': 'Bedelsiz',
    'transfers.kind.renewal': 'Yenileme',
    'transfers.kind.trial': 'Deneme',
    'transfers.status.negotiating': 'Müzakerede',
    'transfers.status.accepted': 'Kabul edildi',
    'transfers.status.rejected': 'Reddedildi',
    'transfers.status.expired': 'Süresi doldu',
    'transfers.status.withdrawn': 'Geri çekildi',
    'transfers.status.blocked': 'Engellendi',
    'transfers.fee': 'Bonservis',
    'transfers.wage': 'Haftalık Maaş',
    'transfers.years': 'Süre',
    'transfers.yearsValue': '{n} yıl',
    'transfers.role': 'Rol',
    'transfers.signing': 'İmza Parası',
    'transfers.goalBonus': 'Gol Primi',
    'transfers.expires': '{n} hafta kaldı',
    'transfers.expiresNow': 'Son gün bu hafta',
    'transfers.parentNo': 'Mevcut kulübün bu bedelle seni bırakmıyor. Transfer listesine girmek durumu değiştirebilir.',
    'transfers.parentYes': 'Mevcut kulübün bırakmaya razı',
    'transfers.vsCurrent': 'mevcut maaşa göre',
    'transfers.accept': 'Kabul Et',
    'transfers.negotiate': 'Pazarlık',
    'transfers.reject': 'Reddet',
    'transfers.confirmAccept': '{club} ile anlaşılsın mı?',
    'transfers.confirmAcceptText': 'İmzaladığın an yeni kulübünün oyuncusu olursun. Geri dönüş yok.',
    'transfers.confirmReject': 'Teklif reddedilsin mi?',
    'transfers.confirmRejectText': '{club} teklifini geri çevireceksin. Bu teklif bir daha gelmeyebilir.',
    'transfers.rejected': 'Teklif reddedildi.',
    'transfers.failed': 'İşlem tamamlanamadı.',
    'transfers.neg.title': 'Müzakere Odası',
    'transfers.neg.round': 'Tur {n}/{max}',
    'transfers.neg.patience': 'Sabır',
    'transfers.neg.clubOffer': 'Kulübün Teklifi',
    'transfers.neg.yourAsk': 'Senin Talebin',
    'transfers.neg.noClause': 'Serbest kalma bedeli yok',
    'transfers.neg.withClause': 'Serbest kalma bedeli',
    'transfers.neg.message': 'Direktöre mesajın',
    'transfers.neg.messagePh': 'İstersen bir şeyler yaz: “Ailem yakınlarda, 5 yıl uzun geliyor…”',
    'transfers.neg.messageAi': 'Yapay zekâ direktör mesajını okuyup ona göre tavır alır.',
    'transfers.neg.send': 'Talebi Gönder',
    'transfers.neg.acceptCurrent': 'Mevcut Teklifi Kabul Et',
    'transfers.neg.sign': 'Anlaşmayı İmzala',
    'transfers.neg.walk': 'Masadan Kalk',
    'transfers.neg.walkConfirm': 'Masadan kalkılsın mı?',
    'transfers.neg.walkText': 'Müzakere biter ve teklif geri çevrilir.',
    'transfers.neg.typing': 'Direktör yazıyor…',
    'transfers.neg.agreed': 'Anlaşma sağlandı. Mürekkep kurumadan imzala.',
    'transfers.neg.collapsed': 'Görüşmeler koptu.',
    'transfers.neg.leave': 'Odadan Çık',
    'transfers.neg.lastRound': 'Son tur: bu, kulübün son sözü.',
    'transfers.neg.greed': 'Talep sertliği',
    'transfers.neg.greed.low': 'Makul',
    'transfers.neg.greed.mid': 'Cesur',
    'transfers.neg.greed.high': 'Çok iddialı',
    'transfers.neg.reset': 'Teklife dön',
    'transfers.neg.who.club': 'Direktör',
    'transfers.neg.who.agent': 'Menajer',
    'transfers.neg.who.player': 'Sen',
    'transfers.neg.who.system': 'Sistem',
    'transfers.neg.conversation': 'Görüşme',
    'transfers.neg.sent': 'Talebin iletildi.',
    'transfers.neg.error': 'Müzakere şu an sürdürülemedi.',
    'transfers.neg.open': 'Müzakereyi aç',
    'transfers.neg.same': 'Teklifle aynı',
  },
  en: {
    'transfers.title': 'Transfers',
    'transfers.subtitle': 'Your contract, offers and the negotiating table',
    'transfers.windowOpen': 'Transfer window open',
    'transfers.windowClosed': 'Transfer window closed',
    'transfers.contract': 'Current Contract',
    'transfers.noContract': 'You are without a club. Weigh the offers and find a new home.',
    'transfers.yearsLeft': '{n} years left',
    'transfers.endsThisSeason': 'Expires this season',
    'transfers.loanFrom': 'Owned by {club}, on loan',
    'transfers.bonuses': 'Bonuses',
    'transfers.perGoal': 'per goal',
    'transfers.perApp': 'per appearance',
    'transfers.noClause': 'None',
    'transfers.clause': 'Release Clause',
    'transfers.list.title': 'Transfer List',
    'transfers.list.desc': 'Listed players are easier to prise away and attract more offers. The price: your manager and the fans will not like it.',
    'transfers.list.on': 'Listed',
    'transfers.list.off': 'Not listed',
    'transfers.list.toastOn': 'You are on the transfer list. Clubs will talk.',
    'transfers.list.toastOff': 'You are off the transfer list.',
    'transfers.offers': 'Offers',
    'transfers.offersEmpty': 'No offers on the table. Keep your form up and grow your fame; clubs are watching.',
    'transfers.history': 'Past Offers',
    'transfers.historyHide': 'Hide',
    'transfers.historyShow': 'Show',
    'transfers.kind.transfer': 'Transfer',
    'transfers.kind.loan': 'Loan',
    'transfers.kind.free': 'Free',
    'transfers.kind.renewal': 'Renewal',
    'transfers.kind.trial': 'Trial',
    'transfers.status.negotiating': 'In talks',
    'transfers.status.accepted': 'Accepted',
    'transfers.status.rejected': 'Rejected',
    'transfers.status.expired': 'Expired',
    'transfers.status.withdrawn': 'Withdrawn',
    'transfers.status.blocked': 'Blocked',
    'transfers.fee': 'Fee',
    'transfers.wage': 'Weekly Wage',
    'transfers.years': 'Length',
    'transfers.yearsValue': '{n} yrs',
    'transfers.role': 'Role',
    'transfers.signing': 'Signing Bonus',
    'transfers.goalBonus': 'Goal Bonus',
    'transfers.expires': '{n} weeks left',
    'transfers.expiresNow': 'Last week to decide',
    'transfers.parentNo': 'Your current club will not let you go at this fee. Joining the transfer list may change that.',
    'transfers.parentYes': 'Your club is willing to sell',
    'transfers.vsCurrent': 'vs current wage',
    'transfers.accept': 'Accept',
    'transfers.negotiate': 'Negotiate',
    'transfers.reject': 'Reject',
    'transfers.confirmAccept': 'Agree terms with {club}?',
    'transfers.confirmAcceptText': 'The moment you sign you are their player. There is no way back.',
    'transfers.confirmReject': 'Reject this offer?',
    'transfers.confirmRejectText': 'You will turn down {club}. This offer may never come again.',
    'transfers.rejected': 'Offer rejected.',
    'transfers.failed': 'That could not be completed.',
    'transfers.neg.title': 'Negotiation Room',
    'transfers.neg.round': 'Round {n}/{max}',
    'transfers.neg.patience': 'Patience',
    'transfers.neg.clubOffer': "Club's Offer",
    'transfers.neg.yourAsk': 'Your Ask',
    'transfers.neg.noClause': 'No release clause',
    'transfers.neg.withClause': 'Release clause',
    'transfers.neg.message': 'Message to the director',
    'transfers.neg.messagePh': 'Write something if you like: "My family is nearby, five years feels long…"',
    'transfers.neg.messageAi': 'The AI director reads your message and reacts to it.',
    'transfers.neg.send': 'Send Ask',
    'transfers.neg.acceptCurrent': 'Accept Current Offer',
    'transfers.neg.sign': 'Sign the Deal',
    'transfers.neg.walk': 'Walk Away',
    'transfers.neg.walkConfirm': 'Walk away?',
    'transfers.neg.walkText': 'The talks end and the offer is turned down.',
    'transfers.neg.typing': 'The director is typing…',
    'transfers.neg.agreed': 'A deal is reached. Sign before the ink dries.',
    'transfers.neg.collapsed': 'Talks have broken down.',
    'transfers.neg.leave': 'Leave the Room',
    'transfers.neg.lastRound': "Final round: this is the club's last word.",
    'transfers.neg.greed': 'Ask boldness',
    'transfers.neg.greed.low': 'Reasonable',
    'transfers.neg.greed.mid': 'Bold',
    'transfers.neg.greed.high': 'Very ambitious',
    'transfers.neg.reset': 'Reset to offer',
    'transfers.neg.who.club': 'Director',
    'transfers.neg.who.agent': 'Agent',
    'transfers.neg.who.player': 'You',
    'transfers.neg.who.system': 'System',
    'transfers.neg.conversation': 'Conversation',
    'transfers.neg.sent': 'Your ask was sent.',
    'transfers.neg.error': 'The talks could not continue right now.',
    'transfers.neg.open': 'Open talks',
    'transfers.neg.same': 'Same as offer',
  },
};
