import { registerStrings } from '../../core/i18n';

/** Banner texts shown over the 3D view (namespace "engine"). */
registerStrings('engine', {
  tr: {
    'banner.goal': 'GOOOL!',
    'banner.goalAgainst': 'GOL YEDİK…',
    'banner.save': 'KURTARIŞ!',
    'banner.held': 'KALECİ TOPU KUCAKLADI',
    'banner.post': 'DİREK!',
    'banner.bar': 'ÜST DİREK!',
    'banner.wide': 'AUT!',
    'banner.over': 'ÜSTTEN AUT!',
    'banner.blocked': 'BLOK!',
    'banner.offside': 'OFSAYT!',
    'banner.foul': 'FAUL!',
    'banner.penalty': 'PENALTI!',
    'banner.tackle': 'TOP KAPILDI!',
    'banner.interception': 'ARAYA GİRDİ!',
    'banner.cleared': 'UZAKLAŞTIRDI!',
    'banner.lost': 'TOP KAYBI',
    'banner.corner': 'KORNER',
    'banner.goalKick': 'KALE VURUŞU',
    'banner.throwIn': 'TAÇ',
    'banner.time': 'POZİSYON BİTTİ',
    'banner.passOk': 'İSABETLİ PAS!',
    'banner.drillDone': 'ANTRENMAN TAMAMLANDI',
    'banner.points': '+{n} PUAN',
    'banner.attempt': 'DENEME {n}/{total}',
    'banner.chance': 'GOL POZİSYONU!',
    'banner.beaten': 'GEÇİLDİ',
  },
  en: {
    'banner.goal': 'GOAL!',
    'banner.goalAgainst': 'THEY SCORE…',
    'banner.save': 'SAVED!',
    'banner.held': 'KEEPER HOLDS ON',
    'banner.post': 'OFF THE POST!',
    'banner.bar': 'OFF THE BAR!',
    'banner.wide': 'WIDE!',
    'banner.over': 'OVER THE BAR!',
    'banner.blocked': 'BLOCKED!',
    'banner.offside': 'OFFSIDE!',
    'banner.foul': 'FOUL!',
    'banner.penalty': 'PENALTY!',
    'banner.tackle': 'BALL WON!',
    'banner.interception': 'INTERCEPTED!',
    'banner.cleared': 'CLEARED!',
    'banner.lost': 'BALL LOST',
    'banner.corner': 'CORNER',
    'banner.goalKick': 'GOAL KICK',
    'banner.throwIn': 'THROW-IN',
    'banner.time': 'MOVE BREAKS DOWN',
    'banner.passOk': 'PASS COMPLETED!',
    'banner.drillDone': 'DRILL COMPLETE',
    'banner.points': '+{n} PTS',
    'banner.attempt': 'ATTEMPT {n}/{total}',
    'banner.chance': 'CHANCE CREATED!',
    'banner.beaten': 'BEATEN',
  },
});
