import { registerStrings } from '../core/i18n';

/** All competition-module text lives under the 'comp' namespace. */
registerStrings('comp', {
  tr: {
    // calendar
    week: 'Hafta {n}',
    preseason: 'Hazırlık',
    summer: 'Yaz Arası',
    intlBreak: 'Milli Ara',
    // competitions
    cc: 'Şampiyonlar Kupası',
    ccShort: 'ŞK',
    intl: 'Milli Maçlar',
    intlShort: 'Milli',
    wc: 'Dünya Kupası {year}',
    wcShort: 'DK',
    cont: 'Kıta Kupası {year}',
    contShort: 'KK',
    'cup.ENG': 'Albion Kupası',
    'cup.ESP': 'Taç Kupası',
    'cup.ITA': 'Tricolore Kupası',
    'cup.GER': 'Kartal Kupası',
    'cup.FRA': 'Cumhuriyet Kupası',
    'cup.POR': 'Lusitanya Kupası',
    'cup.NED': 'Lale Kupası',
    'cup.TUR': 'Türkiye Kupası',
    'cup.other': '{country} Kupası',
    // rounds & stages
    matchday: '{n}. Hafta',
    group: 'Grup {g}',
    groupMd: 'Grup {g} · {n}. Maç',
    'r.R64': 'Son 64 Turu',
    'r.R32': 'Son 32 Turu',
    'r.R16': 'Son 16 Turu',
    'r.QF': 'Çeyrek Final',
    'r.SF': 'Yarı Final',
    'r.F': 'Final',
    'stage.league': 'Lig',
    'stage.group': 'Grup Aşaması',
    'stage.friendlies': 'Milli Maçlar',
    'stage.done': 'Tamamlandı',
    friendly: 'Hazırlık Maçı',
    'qual.WC': 'Dünya Kupası Elemeleri',
    'qual.CONT': 'Kıta Kupası Elemeleri',
    // venues
    nationalStadium: '{nation} Ulusal Stadyumu',
    abroadClub: 'Yurt dışı kulübü',
    // match events (quick sim)
    'ev.kickoff': 'Hakemin düdüğüyle maç başladı.',
    'ev.goal': "{minute}' GOL! {player} ({team}) ağları sarstı.",
    'ev.goalAssist': "{minute}' GOL! {player} ({team}) ağları sarstı. Asist: {assist}",
    'ev.penGoal': "{minute}' GOL! {player} ({team}) penaltıda affetmedi.",
    'ev.penMiss': "{minute}' Penaltı kaçtı! {player} ({team}) beyaz noktada başarısız.",
    'ev.ownGoal': "{minute}' Kendi kalesine! {player} ({team}) talihsiz bir dokunuşla topu ağlara gönderdi.",
    'ev.yellow': "{minute}' Sarı kart: {player} ({team})",
    'ev.secondYellow': "{minute}' İkinci sarıdan kırmızı! {player} ({team}) oyun dışı.",
    'ev.red': "{minute}' Direkt kırmızı kart! {player} ({team}) soyunma odasının yolunu tuttu.",
    'ev.injury': "{minute}' {player} ({team}) sakatlandı, oyuna devam edemiyor.",
    'ev.sub': "{minute}' Oyuncu değişikliği ({team}): {on} girdi, {off} çıktı.",
    'ev.ht': 'İlk yarı sona erdi: {score}',
    'ev.ft': 'Maç sona erdi: {score}',
    'ev.et': 'Eşitlik bozulmadı, uzatmalara gidiliyor!',
    'ev.shootout': 'Penaltı atışları: {home} {hp}-{ap} {away}. {winner} turladı!',
    // awards
    'aw.golden_ball': 'Altın Top',
    'aw.league_top_scorer': 'Gol Kralı · {league}',
    'aw.league_mvp': 'Sezonun Oyuncusu · {league}',
    'aw.young_player': 'Yılın Genç Oyuncusu',
    'aw.team_of_season': "Sezonun 11'i · {league}",
    'aw.tournament_best': 'Turnuvanın Oyuncusu · {comp}',
    'aw.tournament_top_scorer': 'Gol Kralı · {comp}',
    'aw.cc_top_scorer': 'Gol Kralı · {comp}',
    'aw.cc_best': 'Sezonun Oyuncusu · {comp}',
    'detail.player': '{name} ({team})',
    'detail.stats': '{goals} gol · {assists} asist · ort. {avg}',
    'detail.goals': '{goals} gol',
    'detail.pos': '{pos} · {name} ({team})',
    // positions (short)
    'pos.GK': 'KL', 'pos.CB': 'STP', 'pos.FB': 'BEK', 'pos.DM': 'DOS', 'pos.CM': 'OS', 'pos.AM': 'OOS', 'pos.W': 'KAN', 'pos.ST': 'SNT',
  },
  en: {
    week: 'Week {n}',
    preseason: 'Pre-season',
    summer: 'Summer Break',
    intlBreak: 'International Break',
    cc: 'Champions Cup',
    ccShort: 'CC',
    intl: 'Internationals',
    intlShort: 'INT',
    wc: 'World Cup {year}',
    wcShort: 'WC',
    cont: 'Continental Cup {year}',
    contShort: 'CONT',
    'cup.ENG': 'Albion Cup',
    'cup.ESP': 'Crown Cup',
    'cup.ITA': 'Tricolore Cup',
    'cup.GER': 'Eagle Cup',
    'cup.FRA': 'Republic Cup',
    'cup.POR': 'Lusitania Cup',
    'cup.NED': 'Tulip Cup',
    'cup.TUR': 'Turkish Cup',
    'cup.other': '{country} Cup',
    matchday: 'Matchday {n}',
    group: 'Group {g}',
    groupMd: 'Group {g} · MD{n}',
    'r.R64': 'Round of 64',
    'r.R32': 'Round of 32',
    'r.R16': 'Round of 16',
    'r.QF': 'Quarter-final',
    'r.SF': 'Semi-final',
    'r.F': 'Final',
    'stage.league': 'League',
    'stage.group': 'Group Stage',
    'stage.friendlies': 'Internationals',
    'stage.done': 'Finished',
    friendly: 'Friendly',
    'qual.WC': 'World Cup Qualifier',
    'qual.CONT': 'Continental Cup Qualifier',
    nationalStadium: '{nation} National Stadium',
    abroadClub: 'Club abroad',
    'ev.kickoff': 'The referee blows the whistle and we are under way.',
    'ev.goal': "{minute}' GOAL! {player} ({team}) finds the net.",
    'ev.goalAssist': "{minute}' GOAL! {player} ({team}) finds the net. Assist: {assist}",
    'ev.penGoal': "{minute}' GOAL! {player} ({team}) makes no mistake from the spot.",
    'ev.penMiss': "{minute}' Penalty missed! {player} ({team}) fails from twelve yards.",
    'ev.ownGoal': "{minute}' Own goal! An unlucky touch from {player} ({team}) beats his own keeper.",
    'ev.yellow': "{minute}' Yellow card: {player} ({team})",
    'ev.secondYellow': "{minute}' Second yellow, he's off! {player} ({team}) is sent off.",
    'ev.red': "{minute}' Straight red! {player} ({team}) takes an early bath.",
    'ev.injury': "{minute}' {player} ({team}) is injured and cannot continue.",
    'ev.sub': "{minute}' Substitution ({team}): {on} on, {off} off.",
    'ev.ht': 'Half-time: {score}',
    'ev.ft': 'Full-time: {score}',
    'ev.et': 'Still level, we are going to extra time!',
    'ev.shootout': 'Penalty shoot-out: {home} {hp}-{ap} {away}. {winner} go through!',
    'aw.golden_ball': 'Golden Ball',
    'aw.league_top_scorer': 'Golden Boot · {league}',
    'aw.league_mvp': 'Player of the Season · {league}',
    'aw.young_player': 'Young Player of the Year',
    'aw.team_of_season': 'Team of the Season · {league}',
    'aw.tournament_best': 'Player of the Tournament · {comp}',
    'aw.tournament_top_scorer': 'Top Scorer · {comp}',
    'aw.cc_top_scorer': 'Top Scorer · {comp}',
    'aw.cc_best': 'Player of the Season · {comp}',
    'detail.player': '{name} ({team})',
    'detail.stats': '{goals} goals · {assists} assists · avg {avg}',
    'detail.goals': '{goals} goals',
    'detail.pos': '{pos} · {name} ({team})',
    'pos.GK': 'GK', 'pos.CB': 'CB', 'pos.FB': 'FB', 'pos.DM': 'DM', 'pos.CM': 'CM', 'pos.AM': 'AM', 'pos.W': 'W', 'pos.ST': 'ST',
  },
});

export {};
