import { registerStrings } from '../core/i18n';

/** UI + fallback vocabulary for the Claude narrator (namespace 'ai'). */
registerStrings('ai', {
  tr: {
    // errors (shown as aiStatus().lastError and in the Settings test result)
    'err.auth': 'API anahtarı geçersiz. Ayarlar’dan anahtarını kontrol et.',
    'err.permission': 'Bu anahtarın seçili modele erişim izni yok.',
    'err.notFound': 'Model bulunamadı ya da hesabında etkin değil.',
    'err.rateLimit': 'İstek sınırına takıldın; biraz soluklanıp tekrar dene.',
    'err.overloaded': 'Claude şu an çok yoğun, birazdan tekrar dene.',
    'err.billing': 'Hesabında kullanılabilir kredi kalmamış görünüyor.',
    'err.badRequest': 'İstek reddedildi: {detail}',
    'err.connection': 'Bağlantı kurulamadı. İnternet bağlantını kontrol et.',
    'err.timeout': 'Claude zamanında yanıt vermedi.',
    'err.server': 'Claude sunucusunda bir sorun var ({status}). Birazdan tekrar dene.',
    'err.refusal': 'Claude bu isteği yanıtlamadı; hazır anlatıcı devreye girdi.',
    'err.invalid': 'Claude’un yanıtı okunamadı; hazır anlatıcı devreye girdi.',
    'err.unknown': 'Beklenmeyen hata: {detail}',

    // connection test
    'test.noKey': 'Önce bir Claude API anahtarı gir.',
    'test.ok': 'Bağlantı başarılı: {model} hazır. Hikâyen artık Claude’un kaleminden çıkacak.',
    'test.fail': 'Bağlantı başarısız. {error}',

    // status / badges the UI may show
    writing: 'Claude yazıyor…',
    poweredBy: 'Hikâyeni Claude yazıyor',
    offline: 'Hazır anlatıcı',
    aiTag: 'YZ',
    'status.calls': 'İstek',
    'status.failures': 'Hata',
    'status.pending': 'Bekleyen',
    'status.paused': 'Claude kısa bir mola verdi; şimdilik hazır anlatıcı devrede.',

    // feature toggles (Settings)
    'feature.genesis': 'Kariyer başlangıcı',
    'feature.genesis.desc': 'Memleketin, ailen, menajerin ve hikâyenin ilk sayfası.',
    'feature.news': 'Gazete',
    'feature.news.desc': 'Maç sonrası manşetler, transfer dedikoduları, köşe yazıları.',
    'feature.social': 'Sosyal medya',
    'feature.social.desc': 'Taraftarın, gazetecilerin ve rakiplerin paylaşımları.',
    'feature.press': 'Basın toplantısı',
    'feature.press.desc': 'Sorular ve kendi yazdığın cevapların değerlendirilmesi.',
    'feature.negotiation': 'Sözleşme pazarlığı',
    'feature.negotiation.desc': 'Sportif direktörle karşılıklı, canlı pazarlık.',
    'feature.events': 'Sürpriz olaylar',
    'feature.events.desc': 'Sadece senin kariyerine özel, beklenmedik gelişmeler.',
    'feature.chat': 'Mesajlaşma',
    'feature.chat.desc': 'Menajerin, hocan, ailen ve partnerinle sohbet.',
    'feature.biography': 'Belgesel',
    'feature.biography.desc': 'Emekliliğinde kariyerinin belgesel anlatımı.',

    // last-resort texts (used only if even the template narrator fails)
    'lr.outlet': 'Gol Postası',
    'lr.backstory': '{name}, {hometown} sokaklarında, ayakkabısı delinene kadar top koşturarak büyüdü. Mahallede herkes onun bir gün büyük statlarda oynayacağına inanıyordu.',
    'lr.motto': 'Ter yalan söylemez.',
    'lr.dream': 'Bir gün milli formayla büyük bir finalde sahaya çıkmak.',
    'lr.theme': 'Mahalleden zirveye',
    'lr.destiny': 'Bazı yıldızlar geç parlar, ama parladıklarında herkes görür.',
    'lr.rival': '{rival} ile altyapıdan beri süren bir çekişme bu; biri gol attığında öbürü uyuyamıyor.',
    'lr.mentor': '{mentor}, soyunma odasında ona ilk elini uzatan isim oldu.',
    'lr.agentName': 'Kemal Usta',
    'lr.agentPersonality': 'kurnaz, sadık',
    'lr.agentBio': 'Yıllardır genç yetenekleri kollayan, telefonu hiç susmayan eski usul bir menajer.',
    'lr.q1': '{name}, bu sezon için kendine koyduğun hedef ne?',
    'lr.q1.humble': 'Önce takıma faydalı olmak istiyorum, gerisi kendiliğinden gelir.',
    'lr.q1.confident': 'Gol krallığı dahil her şeye oynuyorum, saklayacak değilim.',
    'lr.q1.deflect': 'Hedefleri sahada konuşmayı tercih ederim.',
    'lr.q2': 'Teknik direktörünle ilişkin nasıl, forma şansından memnun musun?',
    'lr.q2.diplomatic': 'Hocamın kararlarına saygım sonsuz, ben işimi yapmaya bakıyorum.',
    'lr.q2.emotional': 'Bu formayı giymek benim için her şey, her dakikaya razıyım.',
    'lr.q2.provocative': 'Daha fazla süre hak ettiğimi düşünüyorum, bunu da saklamayacağım.',
    'lr.journalist': 'Murat Kaya',
    'lr.pressHeadline': '{name} basının karşısında',
    'lr.pressFeedback': 'Sözlerin not defterlerine geçti; yarın manşetlerde ne çıkacağını göreceğiz.',
    'lr.negotiation': 'Teklifimiz masada. Düşün, taşın, sonra bize dön.',
    'lr.chat': 'Şu an biraz yoğunum, sonra uzun uzun konuşalım.',
  },
  en: {
    'err.auth': 'Invalid API key. Check your key in Settings.',
    'err.permission': 'This key has no permission to use the selected model.',
    'err.notFound': 'Model not found or not enabled for your account.',
    'err.rateLimit': 'Rate limited: too many requests, give it a moment and try again.',
    'err.overloaded': 'Claude is overloaded right now; try again shortly.',
    'err.billing': 'Your account appears to be out of credit.',
    'err.badRequest': 'Request rejected: {detail}',
    'err.connection': 'Could not connect. Check your internet connection.',
    'err.timeout': 'Claude didn’t answer in time.',
    'err.server': 'Claude’s servers hit a problem ({status}). Try again shortly.',
    'err.refusal': 'Claude declined this one; the built-in narrator took over.',
    'err.invalid': 'Couldn’t read Claude’s reply; the built-in narrator took over.',
    'err.unknown': 'Unexpected error: {detail}',

    'test.noKey': 'Enter a Claude API key first.',
    'test.ok': 'Connected: {model} is ready to write your story.',
    'test.fail': 'Connection failed. {error}',

    writing: 'Claude is writing…',
    poweredBy: 'Your story is written by Claude',
    offline: 'Built-in narrator',
    aiTag: 'AI',
    'status.calls': 'Requests',
    'status.failures': 'Errors',
    'status.pending': 'Pending',
    'status.paused': 'Claude is taking a breather; the built-in narrator has the mic for now.',

    'feature.genesis': 'Career origin',
    'feature.genesis.desc': 'Your hometown, family, agent and the first page of your story.',
    'feature.news': 'Newspaper',
    'feature.news.desc': 'Match reports, transfer gossip and columns.',
    'feature.social': 'Social media',
    'feature.social.desc': 'Posts from fans, journalists and rivals.',
    'feature.press': 'Press conferences',
    'feature.press.desc': 'Questions, and verdicts on answers you type yourself.',
    'feature.negotiation': 'Contract talks',
    'feature.negotiation.desc': 'Live back-and-forth with the sporting director.',
    'feature.events': 'Surprise events',
    'feature.events.desc': 'Unexpected twists written for your career only.',
    'feature.chat': 'Messages',
    'feature.chat.desc': 'Chat with your agent, manager, family and partner.',
    'feature.biography': 'Documentary',
    'feature.biography.desc': 'The documentary narration of your career when you retire.',

    'lr.outlet': 'The Touchline Herald',
    'lr.backstory': '{name} grew up in {hometown}, playing in the streets until the soles came off every pair of shoes. Everyone on the block was sure the kid would one day fill big stadiums.',
    'lr.motto': 'Sweat never lies.',
    'lr.dream': 'To walk out in a major final wearing the national shirt.',
    'lr.theme': 'From the streets to the summit',
    'lr.destiny': 'Some stars rise late, but when they shine, everyone looks up.',
    'lr.rival': 'A rivalry with {rival} that dates back to academy days; when one scores, the other can’t sleep.',
    'lr.mentor': '{mentor} was the first in the dressing room to offer a helping hand.',
    'lr.agentName': 'Frank Mallory',
    'lr.agentPersonality': 'shrewd, loyal',
    'lr.agentBio': 'An old-school agent who has spent decades scouting young talent, phone permanently glued to his ear.',
    'lr.q1': '{name}, what target have you set yourself this season?',
    'lr.q1.humble': 'First I want to help the team; the rest will follow.',
    'lr.q1.confident': 'I’m going for everything, the golden boot included. No point hiding it.',
    'lr.q1.deflect': 'I’d rather talk about targets on the pitch.',
    'lr.q2': 'How is your relationship with the manager? Happy with your minutes?',
    'lr.q2.diplomatic': 'I fully respect the gaffer’s decisions. I just focus on my job.',
    'lr.q2.emotional': 'Wearing this shirt means everything to me. I’ll take every minute.',
    'lr.q2.provocative': 'I think I deserve more minutes, and I won’t pretend otherwise.',
    'lr.journalist': 'Tom Hartley',
    'lr.pressHeadline': '{name} faces the press',
    'lr.pressFeedback': 'Your words went into the notebooks; tomorrow’s headlines will tell how they landed.',
    'lr.negotiation': 'Our offer stands. Take your time and come back to us.',
    'lr.chat': 'Bit swamped right now, let’s talk properly later.',
  },
});
