import { registerStrings } from '../../core/i18n';

/** 'view' namespace: in-viewport HUD, coach marks, camera names, replay, sandbox. */
registerStrings('view', {
  tr: {
    'hud.call': 'PAS!',
    'hud.through': 'ARA PAS',
    'hud.sprint': 'DEPAR',
    'hud.camera': 'Kamera',
    'hud.help': 'Kontroller',
    'hud.loft': 'Yükseklik',
    'hud.loftHigh': 'Havadan',
    'hud.loftLow': 'Yerden',
    'hud.power': 'GÜÇ',
    'hud.curl': 'FALSO',
    'hud.curlLeft': 'sola',
    'hud.curlRight': 'sağa',
    'hud.focus': 'ODAK',
    'hud.wind': 'Rüzgâr',
    'hud.windUnit': '{v} m/sn',
    'hud.hitIt': 'VUR!',
    'hud.yourBall': 'Top sende',
    'hud.cancelHint': 'Esc / sağ tık: iptal',
    'hud.timeLeft': 'Süre',
    'hud.dragHint': 'Topa bas · sürükle · bırak',
    'hud.defendHint': 'Top sahibine dokun: müdahale · çift dokun: kayarak',
    'hud.callHint': 'PAS! iste ya da boşa koş',
    'hud.tackle': 'MÜDAHALE',
    'hud.loftHint': 'Q / E · tekerlek',
    'hud.after': 'SON DOKUNUŞ',
    'hud.paused': 'DURAKLATILDI',
    'out.goal': 'GOOOL!',
    'out.assist': 'ASİST!',
    'out.chance_created': 'FIRSAT YARATTI',
    'out.saved': 'KURTARIŞ!',
    'out.missed': 'AUT!',
    'out.woodwork': 'DİREK!',
    'out.blocked': 'BLOK!',
    'out.lost_ball': 'TOPU KAPTIRDI',
    'out.offside': 'OFSAYT',
    'out.foul_won': 'FAUL!',
    'out.penalty_won': 'PENALTI!',
    'out.tackle_won': 'TOPU ÇALDI!',
    'out.interception': 'ARAYA GİRDİ!',
    'out.tackle_lost': 'ÇALIMI YEDİ',
    'out.foul_conceded': 'FAUL YAPTI',
    'out.pass_completed': 'İSABETLİ PAS',
    'out.cleared': 'UZAKLAŞTIRDI',
    'out.conceded': 'GOL YEDİK',
    'out.timeout': 'POZİSYON BİTTİ',
    'out.drill_complete': 'ANTRENMAN BİTTİ',
    'replay.label': 'TEKRAR',
    'replay.skip': 'Geç',
    'replay.hint': 'Geçmek için dokun',
    'cam.behind': 'Oyuncu Arkası',
    'cam.broadcast': 'Yayın Açısı',
    'cam.top': 'Kuşbakışı',
    'board.goal': 'GOOOL!',
    'board.welcome': 'HOŞ GELDİNİZ',
    'help.title': 'Nasıl oynanır?',
    'help.subtitle': 'Topu sen konuşturuyorsun.',
    'help.move': 'Sahaya dokun ya da WASD / ok tuşları: koş. Shift ya da DEPAR: hızlan.',
    'help.shoot': 'Topa bas, vurmak istediğin yöne doğru sürükle, bırak. Çizgi ne kadar uzunsa şut o kadar sert.',
    'help.curl': 'Falso Çizgisi: çizgiyi yay gibi bük. Sağa doğru kavis çizersen top sola döner — barajın üstünden, kalecinin ulaşamadığı köşeye.',
    'help.loft': 'Sağdaki çubuk topun yüksekliği: yerden pas mı, aşırtma mı? Tekerlek ya da Q / E.',
    'help.after': 'Bıraktıktan hemen sonra yana kaydır: topa son anda ekstra falso ver.',
    'help.pass': 'Topsuzken PAS! ya da Boşluk: topu iste. Önüne çift dokun: ara pas iste.',
    'help.defend': 'Savunmada top sahibine yakınken ona dokun: müdahale. Çift dokun: kayarak müdahale.',
    'help.camera': 'Kamera düğmesi ya da C: açıyı değiştir.',
    'help.go': 'Hadi, sahne senin!',
    'type.open_play': 'Akan Oyun',
    'type.counter': 'Kontra Atak',
    'type.one_on_one': 'Kaleciyle Karşı Karşıya',
    'type.cross_receive': 'Orta Geliyor',
    'type.wing_cross': 'Kanat Akını',
    'type.build_up': 'Oyun Kurma',
    'type.defend': 'Savunma',
    'type.free_kick': 'Serbest Vuruş',
    'type.penalty': 'Penaltı',
    'type.corner': 'Korner',
    'type.drill_free_kick': 'Antrenman · Serbest Vuruş',
    'type.drill_finishing': 'Antrenman · Bitiricilik',
    'type.drill_passing': 'Antrenman · Pas',
    'sb.title': 'Geliştirici Sahası',
    'sb.moment': 'Pozisyon',
    'sb.weather': 'Hava',
    'sb.time': 'Saat',
    'sb.camera': 'Kamera',
    'sb.quality': 'Kalite',
    'sb.shadows': 'Gölgeler',
    'sb.restart': 'Yeniden Başlat',
    'sb.replay': 'Tekrarı İzle',
    'sb.backdrop': 'Stadyum Arka Planı',
    'sb.help': 'Yardım',
    'sb.engine': 'Motor',
    'sb.engineReal': 'gerçek motor',
    'sb.engineMock': 'deneme motoru',
    'sb.result': 'Sonuç',
    'w.clear': 'Açık',
    'w.cloudy': 'Bulutlu',
    'w.rain': 'Yağmurlu',
    'w.snow': 'Karlı',
    'w.fog': 'Sisli',
    't.day': 'Gündüz',
    't.dusk': 'Gün batımı',
    't.night': 'Gece',
    'q.low': 'Düşük',
    'q.medium': 'Orta',
    'q.high': 'Yüksek',
  },
  en: {
    'hud.call': 'PASS!',
    'hud.through': 'THROUGH',
    'hud.sprint': 'SPRINT',
    'hud.camera': 'Camera',
    'hud.help': 'Controls',
    'hud.loft': 'Loft',
    'hud.loftHigh': 'Lofted',
    'hud.loftLow': 'Ground',
    'hud.power': 'POWER',
    'hud.curl': 'CURL',
    'hud.curlLeft': 'left',
    'hud.curlRight': 'right',
    'hud.focus': 'FOCUS',
    'hud.wind': 'Wind',
    'hud.windUnit': '{v} m/s',
    'hud.hitIt': 'HIT IT!',
    'hud.yourBall': 'Your ball',
    'hud.cancelHint': 'Esc / right-click: cancel',
    'hud.timeLeft': 'Time',
    'hud.dragHint': 'Press the ball · drag · release',
    'hud.defendHint': 'Tap the ball carrier to tackle · double-tap to slide',
    'hud.callHint': 'Call for it with PASS! or make a run',
    'hud.tackle': 'TACKLE',
    'hud.loftHint': 'Q / E · wheel',
    'hud.after': 'AFTERTOUCH',
    'hud.paused': 'PAUSED',
    'out.goal': 'GOAL!',
    'out.assist': 'ASSIST!',
    'out.chance_created': 'CHANCE CREATED',
    'out.saved': 'SAVED!',
    'out.missed': 'WIDE!',
    'out.woodwork': 'OFF THE POST!',
    'out.blocked': 'BLOCKED!',
    'out.lost_ball': 'POSSESSION LOST',
    'out.offside': 'OFFSIDE',
    'out.foul_won': 'FOUL WON!',
    'out.penalty_won': 'PENALTY!',
    'out.tackle_won': 'WON IT BACK!',
    'out.interception': 'INTERCEPTED!',
    'out.tackle_lost': 'SKINNED',
    'out.foul_conceded': 'FOUL',
    'out.pass_completed': 'PASS COMPLETED',
    'out.cleared': 'CLEARED',
    'out.conceded': 'CONCEDED',
    'out.timeout': 'MOMENT OVER',
    'out.drill_complete': 'DRILL COMPLETE',
    'replay.label': 'REPLAY',
    'replay.skip': 'Skip',
    'replay.hint': 'Tap to skip',
    'cam.behind': 'Behind Player',
    'cam.broadcast': 'Broadcast',
    'cam.top': 'Top-down',
    'board.goal': 'GOAL!',
    'board.welcome': 'WELCOME',
    'help.title': 'How to play',
    'help.subtitle': 'You do the talking with the ball.',
    'help.move': 'Tap the pitch or use WASD / arrow keys to run. Shift or SPRINT to accelerate.',
    'help.shoot': 'Press on the ball, drag toward where you want it to go, release. The longer the line, the harder the strike.',
    'help.curl': 'The Curl Line: bend your line like a bow. Bow it to the right and the ball swerves left — over the wall, into the corner the keeper can’t reach.',
    'help.loft': 'The slider on the right sets the height: driven along the grass or chipped? Mouse wheel or Q / E.',
    'help.after': 'Swipe sideways right after releasing to add late swerve (aftertouch).',
    'help.pass': 'Without the ball press PASS! or Space to call for it. Double-tap ahead of you to ask for a through ball.',
    'help.defend': 'When defending, tap the ball carrier while close to tackle. Double-tap for a sliding tackle.',
    'help.camera': 'Camera button or C switches the angle.',
    'help.go': 'Go on, the stage is yours!',
    'type.open_play': 'Open Play',
    'type.counter': 'Counter-Attack',
    'type.one_on_one': 'One-on-One',
    'type.cross_receive': 'Cross Incoming',
    'type.wing_cross': 'Down the Wing',
    'type.build_up': 'Build-up',
    'type.defend': 'Defending',
    'type.free_kick': 'Free Kick',
    'type.penalty': 'Penalty',
    'type.corner': 'Corner',
    'type.drill_free_kick': 'Training · Free Kicks',
    'type.drill_finishing': 'Training · Finishing',
    'type.drill_passing': 'Training · Passing',
    'sb.title': 'Developer Sandbox',
    'sb.moment': 'Moment',
    'sb.weather': 'Weather',
    'sb.time': 'Time',
    'sb.camera': 'Camera',
    'sb.quality': 'Quality',
    'sb.shadows': 'Shadows',
    'sb.restart': 'Restart',
    'sb.replay': 'Watch Replay',
    'sb.backdrop': 'Stadium Backdrop',
    'sb.help': 'Help',
    'sb.engine': 'Engine',
    'sb.engineReal': 'real engine',
    'sb.engineMock': 'mock engine',
    'sb.result': 'Result',
    'w.clear': 'Clear',
    'w.cloudy': 'Cloudy',
    'w.rain': 'Rain',
    'w.snow': 'Snow',
    'w.fog': 'Fog',
    't.day': 'Day',
    't.dusk': 'Dusk',
    't.night': 'Night',
    'q.low': 'Low',
    'q.medium': 'Medium',
    'q.high': 'High',
  },
});
