import { registerStrings } from '../../core/i18n';

/** 'v2d' namespace: 2D match view controls, hints, help card, touch buttons, moment tips. */
registerStrings('v2d', {
  tr: {
    'hint.attack': 'Koştuğun yöne: SPACE şut (basılı tut = sert) · F pas · Shift depar',
    'hint.noBall': 'F: pas iste · F basılı tut + koş: ara pas iste · topa yakınken SPACE: tek vuruş',
    'hint.defend': 'Rakibe yaklaş · SPACE / F: müdahale (çift bas: kayarak)',
    'hint.setPiece': 'W / S: hedefi seç · SPACE: vur (basılı tut: güç) · F: kısa pas · Q / E: falso',
    'hint.corner': 'SPACE: ceza sahasına orta · F: kısa pas',
    'hint.touch': 'Sol: joystick · ŞUT (basılı tut) · PAS (topsuzken: pas iste)',
    'touch.shoot': 'ŞUT',
    'touch.pass': 'PAS',
    'touch.through': 'ARA',
    'aim.power': 'GÜÇ',
    'aim.curl': 'FALSO',
    'aim.chip': 'AŞIRTMA',
    'replay': 'TEKRAR',
    'replay.skip': 'Geçmek için tıkla / Space',
    'help.title': 'Kontroller',
    'help.sub': 'Basit: koştuğun yöne vur, F ile pas ver ya da pas iste.',
    'help.move': 'Koş (3D: yön kameraya göre, yukarı = rakip kaleye doğru)',
    'help.sprint': 'Depar',
    'help.shoot': 'Şut — koştuğun yöne vurur (tuşa basmıyorsan baktığın yöne). Basılı tut = daha sert, bırak = vur. Kaleye doğru koşuyorsan nişan kale ağzına yardım eder.',
    'help.curl': 'Şut yüklerken falso (sola / sağa)',
    'help.pass': 'Top sende: koştuğun yöndeki en uygun arkadaşa pas. Topsuzken: pas iste — arkadaşın hemen sana atar. Basılı tutup koşarsan ara pas ister.',
    'help.through': 'Ara pas (topsuzken: ara pas iste)',
    'help.call': 'Pas iste (F ile aynı)',
    'help.defend': 'Savunma: rakibe yakınken SPACE / F = müdahale, çift bas = kayarak',
    'help.mouseKey': 'Fare',
    'help.mouse': 'Fare: sahaya tıkla = oraya koş (nişan için kullanılmaz)',
    'help.setPiece': 'Serbest vuruş / penaltı: W / S ile hedefi seç',
    'help.go': 'Başlamak için bir tuşa bas',
    'zoom.behind': 'Yakın',
    'zoom.broadcast': 'Orta',
    'zoom.top': 'Geniş',
    'tip.open_play': 'Kaleye doğru koş ve SPACE: kaleye doğru koşarken şut köşeye gider. Sıkışırsan F.',
    'tip.counter': 'Topu ileri sür; F ile koşan arkadaşına pas ver ya da kendin bitir.',
    'tip.one_on_one': 'Kaleye doğru koş, 14 metre civarında SPACE: kalecinin boş bıraktığı köşe.',
    'tip.cross_receive': 'Ortaya doğru koş, top gelirken SPACE basılı tut: kafa ya da vole.',
    'tip.wing_cross': 'Beki geç; ceza sahasına doğru F ile pas ya da kaleye doğru SPACE.',
    'tip.build_up': 'Topu kaybetme: koştuğun yöne F ile pas ver, topsuzken F ile geri iste.',
    'tip.defend': 'Top sahibine yaklaş, yanındayken SPACE: müdahale.',
    'tip.free_kick': 'W / S ile köşeyi seç, SPACE: barajın üstünden kıvrılan şut.',
    'tip.penalty': 'W / S ile köşeyi seç, SPACE basılı tut ve bırak.',
    'tip.corner': 'SPACE: ceza sahasındaki arkadaşına orta. F: kısa pas.',
    'tip.drill_free_kick': 'W / S ile hedef seç, SPACE ile vur. Köşeler daha çok puan!',
    'tip.drill_finishing': 'Gelen topa koş, SPACE ile bitir.',
    'tip.drill_passing': 'F ile arkadaşına pas ver. R: ara pas ekstra puan!',
    'tip.shootout': 'W / S ile köşeyi seç, SPACE ile vur.',
    'drill.shoot': 'SPACE basılı tut, bırak: koştuğun yöne şut (kaleye doğruysa köşeye yardım). W / S: hedef, Q / E: falso.',
    'drill.move': 'WASD / ok tuşları: koş, Shift: depar.',
    'drill.pass': 'F: koştuğun yöndeki arkadaşa pas, R: ara pas. Dokunmatikte: joystick + ŞUT / PAS.',
    'set.title': 'Maç',
    'set.view': 'Maç görünümü',
    'set.viewDesc': '3D: stadyum ve oyuncularla tam görünüm (önerilen). 2D: basit kuşbakışı, düşük donanımlı cihazlar için. Kontroller ikisinde de aynı.',
    'set.2d': '2D (basit / düşük donanım)',
    'set.3d': '3D (önerilen)',
    'set.controls': 'Maç kontrolleri',
    'set.mode': 'Kontrol modu',
    'set.modeDesc': 'Sakin: SPACE ile oyun durur, şutu / pası çizip vurursun; koşmak ve pas istemek gerçek zamanlı (önerilen). Hızlı: her şey gerçek zamanlı, basılı tut ve bırak.',
    'set.calm': 'Sakin (durdur ve çiz) — önerilen',
    'set.fast': 'Hızlı (gerçek zamanlı)',
    'help.subCalm': 'Sakin mod: koş, SPACE ile oyunu durdur, vuruşu çiz ve bırak. Sonra koşmaya, pas istemeye devam.',
    'chint.attack': 'SPACE: oyunu durdur, şutu / pası çiz · F: pas için durdur · Shift: depar',
    'chint.noBall': 'F: pas iste · F basılı tut + koş: ara pas iste · top yanına gelince SPACE: durdur ve vur',
    'chint.defend': 'Rakibe yaklaş · SPACE / F: müdahale (çift bas: kayarak)',
    'chint.setPiece': 'Oyun durdu: fareyle çiz ya da A / D yön, W / S güç, Q / E falso · SPACE: vur',
    'chint.corner': 'Oyun durdu: ortayı çiz (Z: yükseklik) · SPACE: vur',
    'chint.touch': 'Sol: joystick · ŞUT / PAS: oyunu durdur, parmağınla çiz, VUR · topsuzken PAS: pas iste',
    'calm.space': 'Top sende (ya da ayağına geliyor): oyun DURUR, vuruşu çiz ya da tuşlarla ayarla, sonra vur. Topsuzken: arkadaşın topta ise pas ister.',
    'calm.draw': 'Oyun durunca topun yanından sürükle: çizginin yönü = yön, uzunluğu = güç, kıvrımı = falso. Bırak = vur. Tekerlek = yükseklik.',
    'calm.keys': 'Oyun durunca: A / D yönü çevirir, W / S gücü ayarlar',
    'calm.curlLoft': 'Oyun durunca: Q / E falso, Z yükseklik (Yerden / Yarım / Havadan)',
    'calm.confirm': 'Vur · Esc: vurmadan devam et',
    'calm.f': 'Top sende: pas için durdur (en uygun arkadaşa hazır). Topsuzken: pas iste — basılı tutup koşarsan ara pas ister.',
    'aim.stopped': 'OYUN DURDU',
    'aim.kind.pass': 'PAS',
    'aim.kind.shot': 'ŞUT',
    'aim.kind.free': 'BOŞLUĞA',
    'aim.onTarget': 'Kaleyi buluyor',
    'aim.offTarget': 'Çerçeve dışı',
    'aim.danger': 'Dikkat: {n} rakip araya girebilir',
    'aim.assist': 'Arkadaşının koşusuna ayarlandı',
    'aim.loft.0': 'Yerden',
    'aim.loft.1': 'Yarım',
    'aim.loft.2': 'Havadan',
    'aim.kick': 'VUR',
    'aim.cancel': 'İptal',
    'aim.curlNone': 'yok',
    'aim.keys': '<b>Çiz:</b> topun yanından sürükle, bırak = vur · <b>A / D</b> yön · <b>W / S</b> güç · <b>Q / E</b> falso · <b>Z</b> yükseklik',
    'aim.touchHelp': '<b>Parmağınla çiz:</b> topun yanından sürükle, sonra <b>VUR</b>',
    'ctip.open_play': 'Kaleye doğru koş, SPACE: oyun durur — şutu ya da pası çiz, bırak.',
    'ctip.counter': 'Topu ileri sür; SPACE ile durdur, koşan arkadaşına pası çiz ya da kendin vur.',
    'ctip.one_on_one': 'Kaleciye doğru koş, SPACE: oyun durur — boş köşeye çiz.',
    'ctip.cross_receive': 'Ortaya doğru koş; top gelince SPACE: oyun durur, kafa / voleyi çiz.',
    'ctip.wing_cross': 'Beki geç; SPACE ile durdur ve ceza sahasına ortayı çiz (Z: havadan).',
    'ctip.build_up': 'Topu kaybetme: SPACE ile durdur, pası çiz; sonra F ile topu geri iste.',
    'ctip.defend': 'Top sahibine yaklaş, yanındayken SPACE: müdahale.',
    'ctip.free_kick': 'Oyun durdu: barajın üstünden kıvrılan şutu çiz (kıvrım = falso), bırak.',
    'ctip.penalty': 'Oyun durdu: köşeye çiz, güç için çizgiyi uzat, bırak.',
    'ctip.corner': 'Oyun durdu: ceza sahasındaki arkadaşına ortayı çiz (Z: yükseklik).',
    'ctip.drill_free_kick': 'Oyun durdu: hedefe kıvrılan şutu çiz. Köşeler daha çok puan!',
    'ctip.drill_finishing': 'Gelen topa koş, SPACE: oyun durur, bitirişi çiz.',
    'ctip.drill_passing': 'SPACE / F: oyun durur, arkadaşına pası çiz. Ara pas ekstra puan!',
    'ctip.shootout': 'Oyun durdu: köşeye çiz ve bırak.',
    'cdrill.shoot': 'SPACE: oyun durur — topun yanından vuruşu çiz (yön, uzunluk = güç, kıvrım = falso) ve bırak. Tuşlarla: A / D, W / S, Q / E, Z.',
    'cdrill.pass': 'Top sende F / SPACE: oyun durur, arkadaşına pası çiz. Dokunmatikte: joystick + ŞUT / PAS, çiz, VUR.',
  },
  en: {
    'hint.attack': 'Where you run: SPACE shoot (hold = harder) · F pass · Shift sprint',
    'hint.noBall': 'F: call for the ball · hold F + run: ask for a through ball · SPACE near the ball: one-touch',
    'hint.defend': 'Close him down · SPACE / F: tackle (double-tap: slide)',
    'hint.setPiece': 'W / S: pick your target · SPACE: strike (hold: power) · F: short pass · Q / E: curl',
    'hint.corner': 'SPACE: cross into the box · F: short pass',
    'hint.touch': 'Left: joystick · SHOOT (hold) · PASS (without the ball: call for it)',
    'touch.shoot': 'SHOOT',
    'touch.pass': 'PASS',
    'touch.through': 'THRU',
    'aim.power': 'POWER',
    'aim.curl': 'CURL',
    'aim.chip': 'CHIP',
    'replay': 'REPLAY',
    'replay.skip': 'Click / Space to skip',
    'help.title': 'Controls',
    'help.sub': 'Simple: shoot where you run, pass or call for the ball with F.',
    'help.move': 'Run (3D: camera-relative, up = towards the opponent\'s goal)',
    'help.sprint': 'Sprint',
    'help.shoot': 'Shoot — strikes where you are running (no keys held: where you face). Hold for more power, release to strike. Running at goal, the aim helps it into the goal mouth.',
    'help.curl': 'Curl while charging (left / right)',
    'help.pass': 'With the ball: pass to the best team-mate in your running direction. Without it: call for the ball — your team-mate plays it straight to you. Hold it while running to ask for a through ball.',
    'help.through': 'Through ball (without the ball: ask for one)',
    'help.call': 'Call for the ball (same as F)',
    'help.defend': 'Defending: SPACE / F near the carrier = tackle, double-tap = slide',
    'help.mouseKey': 'Mouse',
    'help.mouse': 'Mouse: click the pitch = run there (not used for aiming)',
    'help.setPiece': 'Free kicks / penalties: pick your target with W / S',
    'help.go': 'Press any key to start',
    'zoom.behind': 'Close',
    'zoom.broadcast': 'Medium',
    'zoom.top': 'Wide',
    'tip.open_play': 'Run at goal and press SPACE: running at goal, the shot finds a corner. Crowded out? F.',
    'tip.counter': 'Drive forward; pass to a runner with F or finish it yourself.',
    'tip.one_on_one': 'Run at goal and press SPACE from around 14 m: the corner the keeper leaves open.',
    'tip.cross_receive': 'Attack the cross and hold SPACE as it arrives: header or volley.',
    'tip.wing_cross': 'Beat your full-back; pass towards the box with F or shoot at goal with SPACE.',
    'tip.build_up': 'Keep the ball: pass with F where you run, call for it back with F.',
    'tip.defend': 'Close down the carrier and press SPACE next to him to tackle.',
    'tip.free_kick': 'Pick your corner with W / S, SPACE: a curler over the wall.',
    'tip.penalty': 'Pick your corner with W / S, hold SPACE and release.',
    'tip.corner': 'SPACE: cross to a team-mate in the box. F: short pass.',
    'tip.drill_free_kick': 'Pick your target with W / S and strike with SPACE. Corners score more!',
    'tip.drill_finishing': 'Run onto the pass and finish with SPACE.',
    'tip.drill_passing': 'Pass to your team-mates with F. Through balls (R) score extra!',
    'tip.shootout': 'Pick your corner with W / S and strike with SPACE.',
    'drill.shoot': 'Hold SPACE and release: a shot where you run (helped into a corner when at goal). W / S: target, Q / E: curl.',
    'drill.move': 'WASD / arrow keys: run, Shift: sprint.',
    'drill.pass': 'F: pass to the team-mate where you run, R: through ball. On touch: joystick + SHOOT / PASS.',
    'set.title': 'Match',
    'set.view': 'Match view',
    'set.viewDesc': '3D: the full stadium-and-players view (recommended). 2D: simple top-down view for low-spec devices. The controls are the same in both.',
    'set.2d': '2D (simple / low-spec)',
    'set.3d': '3D (recommended)',
    'set.controls': 'Match controls',
    'set.mode': 'Control mode',
    'set.modeDesc': 'Calm: SPACE stops the game, you draw your shot / pass and release; running and calling for the ball stay real-time (recommended). Fast: everything in real time, hold and release.',
    'set.calm': 'Calm (stop & draw) — recommended',
    'set.fast': 'Fast (real-time)',
    'help.subCalm': 'Calm mode: run, stop the game with SPACE, draw your kick and release. Then keep running and calling for the ball.',
    'chint.attack': 'SPACE: stop the game and draw your shot / pass · F: stop to pass · Shift: sprint',
    'chint.noBall': 'F: call for the ball · hold F + run: ask for a through ball · SPACE as the ball arrives: stop and strike',
    'chint.defend': 'Close him down · SPACE / F: tackle (double-tap: slide)',
    'chint.setPiece': 'Game stopped: draw with the mouse or A / D direction, W / S power, Q / E curl · SPACE: strike',
    'chint.corner': 'Game stopped: draw your cross (Z: height) · SPACE: strike',
    'chint.touch': 'Left: joystick · SHOOT / PASS: stop the game, draw with your finger, KICK · without the ball PASS: call for it',
    'calm.space': 'With the ball (or as it arrives): the game STOPS — draw your kick or set it with the keys, then strike. Without it: calls for the ball when a team-mate has it.',
    'calm.draw': 'While stopped, drag from the ball: the line\'s direction = direction, length = power, bend = curl. Release = strike. Wheel = height.',
    'calm.keys': 'While stopped: A / D turn the direction, W / S set the power',
    'calm.curlLoft': 'While stopped: Q / E curl, Z height (Ground / Half / High)',
    'calm.confirm': 'Strike · Esc: carry on without kicking',
    'calm.f': 'With the ball: stop to pass (set up for the best team-mate). Without it: call for the ball — hold it while running to ask for a through ball.',
    'aim.stopped': 'GAME STOPPED',
    'aim.kind.pass': 'PASS',
    'aim.kind.shot': 'SHOT',
    'aim.kind.free': 'INTO SPACE',
    'aim.onTarget': 'On target',
    'aim.offTarget': 'Off target',
    'aim.danger': 'Careful: {n} opponent(s) may cut it out',
    'aim.assist': 'Set to your team-mate\'s run',
    'aim.loft.0': 'Ground',
    'aim.loft.1': 'Half',
    'aim.loft.2': 'High',
    'aim.kick': 'KICK',
    'aim.cancel': 'Cancel',
    'aim.curlNone': 'none',
    'aim.keys': '<b>Draw:</b> drag from the ball, release = strike · <b>A / D</b> direction · <b>W / S</b> power · <b>Q / E</b> curl · <b>Z</b> height',
    'aim.touchHelp': '<b>Draw with your finger:</b> drag from the ball, then <b>KICK</b>',
    'ctip.open_play': 'Run at goal and press SPACE: the game stops — draw your shot or pass and release.',
    'ctip.counter': 'Drive forward; stop with SPACE and draw the pass to a runner, or finish it yourself.',
    'ctip.one_on_one': 'Run at the keeper and press SPACE: the game stops — draw it into the open corner.',
    'ctip.cross_receive': 'Attack the cross; as it arrives press SPACE: the game stops, draw your header / volley.',
    'ctip.wing_cross': 'Beat your full-back; stop with SPACE and draw the cross into the box (Z: high).',
    'ctip.build_up': 'Keep the ball: stop with SPACE and draw the pass; then call for it back with F.',
    'ctip.defend': 'Close down the carrier and press SPACE next to him to tackle.',
    'ctip.free_kick': 'Game stopped: draw a curler over the wall (bend = curl) and release.',
    'ctip.penalty': 'Game stopped: draw into a corner, longer line = more power, release.',
    'ctip.corner': 'Game stopped: draw the cross to a team-mate in the box (Z: height).',
    'ctip.drill_free_kick': 'Game stopped: draw a curler at the target. Corners score more!',
    'ctip.drill_finishing': 'Run onto the pass, SPACE: the game stops, draw your finish.',
    'ctip.drill_passing': 'SPACE / F: the game stops, draw the pass to a team-mate. Through balls score extra!',
    'ctip.shootout': 'Game stopped: draw into a corner and release.',
    'cdrill.shoot': 'SPACE: the game stops — drag your kick from the ball (direction, length = power, bend = curl) and release. Keys: A / D, W / S, Q / E, Z.',
    'cdrill.pass': 'With the ball F / SPACE: the game stops, draw the pass to a team-mate. On touch: joystick + SHOOT / PASS, draw, KICK.',
  },
});
