import { registerStrings } from '../../core/i18n';

/** 'v2d' namespace: 2D match view controls, hints, help card, touch buttons, moment tips. */
registerStrings('v2d', {
  tr: {
    'hint.attack': 'Koştuğun yöne: SPACE şut (basılı tut = sert) · F pas · Shift depar',
    'hint.noBall': 'F: pas iste · F basılı tut + koş: ara pas iste · topa yakınken SPACE: tek vuruş',
    'hint.defend': 'Rakibe yaklaş · SPACE / F: müdahale (çift bas: kayarak)',
    'hint.setPiece': 'W / S: hedefi seç · SPACE: vur (basılı tut: güç) · F: kısa pas · Q / E: falso',
    'hint.corner': 'SPACE: ceza sahasına orta · F: kısa pas',
    'hint.touch': 'Sol: joystick · ŞUT (basılı tut) · PAS (topsuzken: pas iste)',
    'touch.shoot': 'ŞUT',
    'touch.pass': 'PAS',
    'touch.through': 'ARA',
    'aim.power': 'GÜÇ',
    'aim.curl': 'FALSO',
    'aim.chip': 'AŞIRTMA',
    'replay': 'TEKRAR',
    'replay.skip': 'Geçmek için tıkla / Space',
    'help.title': 'Kontroller',
    'help.sub': 'Basit: koştuğun yöne vur, F ile pas ver ya da pas iste.',
    'help.move': 'Koş (3D: yön kameraya göre, yukarı = rakip kaleye doğru)',
    'help.sprint': 'Depar',
    'help.shoot': 'Şut — koştuğun yöne vurur (tuşa basmıyorsan baktığın yöne). Basılı tut = daha sert, bırak = vur. Kaleye doğru koşuyorsan nişan kale ağzına yardım eder.',
    'help.curl': 'Şut yüklerken falso (sola / sağa)',
    'help.pass': 'Top sende: koştuğun yöndeki en uygun arkadaşa pas. Topsuzken: pas iste — arkadaşın hemen sana atar. Basılı tutup koşarsan ara pas ister.',
    'help.through': 'Ara pas (topsuzken: ara pas iste)',
    'help.call': 'Pas iste (F ile aynı)',
    'help.defend': 'Savunma: rakibe yakınken SPACE / F = müdahale, çift bas = kayarak',
    'help.mouseKey': 'Fare',
    'help.mouse': 'Fare: sahaya tıkla = oraya koş (nişan için kullanılmaz)',
    'help.setPiece': 'Serbest vuruş / penaltı: W / S ile hedefi seç',
    'help.go': 'Başlamak için bir tuşa bas',
    'zoom.behind': 'Yakın',
    'zoom.broadcast': 'Orta',
    'zoom.top': 'Geniş',
    'tip.open_play': 'Kaleye doğru koş ve SPACE: kaleye doğru koşarken şut köşeye gider. Sıkışırsan F.',
    'tip.counter': 'Topu ileri sür; F ile koşan arkadaşına pas ver ya da kendin bitir.',
    'tip.one_on_one': 'Kaleye doğru koş, 14 metre civarında SPACE: kalecinin boş bıraktığı köşe.',
    'tip.cross_receive': 'Ortaya doğru koş, top gelirken SPACE basılı tut: kafa ya da vole.',
    'tip.wing_cross': 'Beki geç; ceza sahasına doğru F ile pas ya da kaleye doğru SPACE.',
    'tip.build_up': 'Topu kaybetme: koştuğun yöne F ile pas ver, topsuzken F ile geri iste.',
    'tip.defend': 'Top sahibine yaklaş, yanındayken SPACE: müdahale.',
    'tip.free_kick': 'W / S ile köşeyi seç, SPACE: barajın üstünden kıvrılan şut.',
    'tip.penalty': 'W / S ile köşeyi seç, SPACE basılı tut ve bırak.',
    'tip.corner': 'SPACE: ceza sahasındaki arkadaşına orta. F: kısa pas.',
    'tip.drill_free_kick': 'W / S ile hedef seç, SPACE ile vur. Köşeler daha çok puan!',
    'tip.drill_finishing': 'Gelen topa koş, SPACE ile bitir.',
    'tip.drill_passing': 'F ile arkadaşına pas ver. R: ara pas ekstra puan!',
    'tip.shootout': 'W / S ile köşeyi seç, SPACE ile vur.',
    'drill.shoot': 'SPACE basılı tut, bırak: koştuğun yöne şut (kaleye doğruysa köşeye yardım). W / S: hedef, Q / E: falso.',
    'drill.move': 'WASD / ok tuşları: koş, Shift: depar.',
    'drill.pass': 'F: koştuğun yöndeki arkadaşa pas, R: ara pas. Dokunmatikte: joystick + ŞUT / PAS.',
    'set.title': 'Maç',
    'set.view': 'Maç görünümü',
    'set.viewDesc': '3D: stadyum ve oyuncularla tam görünüm (önerilen). 2D: basit kuşbakışı, düşük donanımlı cihazlar için. Kontroller ikisinde de aynı.',
    'set.2d': '2D (basit / düşük donanım)',
    'set.3d': '3D (önerilen)',
    'set.controls': 'Maç kontrolleri',
  },
  en: {
    'hint.attack': 'Where you run: SPACE shoot (hold = harder) · F pass · Shift sprint',
    'hint.noBall': 'F: call for the ball · hold F + run: ask for a through ball · SPACE near the ball: one-touch',
    'hint.defend': 'Close him down · SPACE / F: tackle (double-tap: slide)',
    'hint.setPiece': 'W / S: pick your target · SPACE: strike (hold: power) · F: short pass · Q / E: curl',
    'hint.corner': 'SPACE: cross into the box · F: short pass',
    'hint.touch': 'Left: joystick · SHOOT (hold) · PASS (without the ball: call for it)',
    'touch.shoot': 'SHOOT',
    'touch.pass': 'PASS',
    'touch.through': 'THRU',
    'aim.power': 'POWER',
    'aim.curl': 'CURL',
    'aim.chip': 'CHIP',
    'replay': 'REPLAY',
    'replay.skip': 'Click / Space to skip',
    'help.title': 'Controls',
    'help.sub': 'Simple: shoot where you run, pass or call for the ball with F.',
    'help.move': 'Run (3D: camera-relative, up = towards the opponent\'s goal)',
    'help.sprint': 'Sprint',
    'help.shoot': 'Shoot — strikes where you are running (no keys held: where you face). Hold for more power, release to strike. Running at goal, the aim helps it into the goal mouth.',
    'help.curl': 'Curl while charging (left / right)',
    'help.pass': 'With the ball: pass to the best team-mate in your running direction. Without it: call for the ball — your team-mate plays it straight to you. Hold it while running to ask for a through ball.',
    'help.through': 'Through ball (without the ball: ask for one)',
    'help.call': 'Call for the ball (same as F)',
    'help.defend': 'Defending: SPACE / F near the carrier = tackle, double-tap = slide',
    'help.mouseKey': 'Mouse',
    'help.mouse': 'Mouse: click the pitch = run there (not used for aiming)',
    'help.setPiece': 'Free kicks / penalties: pick your target with W / S',
    'help.go': 'Press any key to start',
    'zoom.behind': 'Close',
    'zoom.broadcast': 'Medium',
    'zoom.top': 'Wide',
    'tip.open_play': 'Run at goal and press SPACE: running at goal, the shot finds a corner. Crowded out? F.',
    'tip.counter': 'Drive forward; pass to a runner with F or finish it yourself.',
    'tip.one_on_one': 'Run at goal and press SPACE from around 14 m: the corner the keeper leaves open.',
    'tip.cross_receive': 'Attack the cross and hold SPACE as it arrives: header or volley.',
    'tip.wing_cross': 'Beat your full-back; pass towards the box with F or shoot at goal with SPACE.',
    'tip.build_up': 'Keep the ball: pass with F where you run, call for it back with F.',
    'tip.defend': 'Close down the carrier and press SPACE next to him to tackle.',
    'tip.free_kick': 'Pick your corner with W / S, SPACE: a curler over the wall.',
    'tip.penalty': 'Pick your corner with W / S, hold SPACE and release.',
    'tip.corner': 'SPACE: cross to a team-mate in the box. F: short pass.',
    'tip.drill_free_kick': 'Pick your target with W / S and strike with SPACE. Corners score more!',
    'tip.drill_finishing': 'Run onto the pass and finish with SPACE.',
    'tip.drill_passing': 'Pass to your team-mates with F. Through balls (R) score extra!',
    'tip.shootout': 'Pick your corner with W / S and strike with SPACE.',
    'drill.shoot': 'Hold SPACE and release: a shot where you run (helped into a corner when at goal). W / S: target, Q / E: curl.',
    'drill.move': 'WASD / arrow keys: run, Shift: sprint.',
    'drill.pass': 'F: pass to the team-mate where you run, R: through ball. On touch: joystick + SHOOT / PASS.',
    'set.title': 'Match',
    'set.view': 'Match view',
    'set.viewDesc': '3D: the full stadium-and-players view (recommended). 2D: simple top-down view for low-spec devices. The controls are the same in both.',
    'set.2d': '2D (simple / low-spec)',
    'set.3d': '3D (recommended)',
    'set.controls': 'Match controls',
  },
});
