import { registerStrings } from '../../core/i18n';

/** 'v2d' namespace: 2D match view controls, hints, help card, touch buttons, moment tips. */
registerStrings('v2d', {
  tr: {
    'hint.attack': 'WASD: koş · Shift: depar · SPACE: şut (basılı tut) · F: pas · R: ara pas · Q/E: falso',
    'hint.noBall': 'C: pas iste · R: ara pas iste · topa yakınken SPACE: tek vuruş',
    'hint.defend': 'Rakibe yaklaş · SPACE / F: müdahale (çift bas: kayarak)',
    'hint.setPiece': 'W / S: hedefi seç · SPACE: vur (basılı tut: güç) · F: kısa pas · Q / E: falso',
    'hint.corner': 'SPACE: ceza sahasına orta · F: kısa pas',
    'hint.touch': 'Sol: joystick · ŞUT basılı tut · PAS',
    'touch.shoot': 'ŞUT',
    'touch.pass': 'PAS',
    'touch.through': 'ARA',
    'aim.power': 'GÜÇ',
    'aim.curl': 'FALSO',
    'aim.chip': 'AŞIRTMA',
    'replay': 'TEKRAR',
    'replay.skip': 'Geçmek için tıkla / Space',
    'help.title': 'Kontroller',
    'help.sub': 'Basit ve hızlı — HaxBall gibi.',
    'help.move': 'Koş',
    'help.sprint': 'Depar',
    'help.shoot': 'Şut — basılı tut = daha sert, bırak = vur. Nişan otomatik: kalecinin uzak köşesi.',
    'help.curl': 'Şut yüklerken falso (sola / sağa)',
    'help.pass': 'Pas — en uygun arkadaşa otomatik (koştuğun yöne göre)',
    'help.through': 'Ara pas — en öndeki arkadaşın önüne',
    'help.call': 'Topsuzken: pas iste',
    'help.defend': 'Savunma: rakibe yakınken SPACE / F = müdahale, çift bas = kayarak',
    'help.mouseKey': 'Fare',
    'help.mouse': 'Fare (isteğe bağlı): imleç = nişan, sol tık = şut, sağ tık = pas, topsuzken tıkla = oraya koş',
    'help.setPiece': 'Serbest vuruş / penaltı: W / S ile hedefi seç',
    'help.go': 'Başlamak için bir tuşa bas',
    'zoom.behind': 'Yakın',
    'zoom.broadcast': 'Orta',
    'zoom.top': 'Geniş',
    'tip.open_play': 'Kaleye koş, SPACE ile vur. Sıkışırsan F ile pas ver.',
    'tip.counter': 'Topu sür, arkadaşların koşuda: R ile ara pas ya da kendin bitir.',
    'tip.one_on_one': 'Kaleye doğru koş, 14 metre civarında SPACE: köşeye otomatik nişan.',
    'tip.cross_receive': 'Ortaya doğru koş, top gelirken SPACE basılı tut: kafa ya da vole.',
    'tip.wing_cross': 'Beki geç, ceza sahasına yaklaşınca F ile orta ya da SPACE ile şut.',
    'tip.build_up': 'Topu kaybetme: F ile en uygun arkadaşına pas ver.',
    'tip.defend': 'Top sahibine yaklaş, yanındayken SPACE: müdahale.',
    'tip.free_kick': 'W / S ile köşeyi seç, SPACE: barajın üstünden kıvrılan şut.',
    'tip.penalty': 'W / S ile köşeyi seç, SPACE basılı tut ve bırak.',
    'tip.corner': 'SPACE: ceza sahasındaki arkadaşına orta. F: kısa pas.',
    'tip.drill_free_kick': 'W / S ile hedef seç, SPACE ile vur. Köşeler daha çok puan!',
    'tip.drill_finishing': 'Gelen topa koş, SPACE ile bitir.',
    'tip.drill_passing': 'F ile arkadaşına pas ver. R: ara pas ekstra puan!',
    'tip.shootout': 'W / S ile köşeyi seç, SPACE ile vur.',
    'drill.shoot': 'SPACE basılı tut, bırak: şut (nişan otomatik). W / S: hedef, Q / E: falso.',
    'drill.move': 'WASD / ok tuşları: koş, Shift: depar.',
    'drill.pass': 'F: pas, R: ara pas. Dokunmatikte: joystick + ŞUT / PAS.',
    'set.title': 'Maç',
    'set.view': 'Maç görünümü',
    'set.viewDesc': '2D kuşbakışı: en kolay ve akıcı oynanış, kolay şut / pas yardımı. 3D: sinematik görünüm, sürükle-bırak kontroller.',
    'set.2d': '2D (önerilen)',
    'set.3d': '3D',
    'set.controls': 'Maç kontrolleri (2D)',
  },
  en: {
    'hint.attack': 'WASD: run · Shift: sprint · SPACE: shoot (hold) · F: pass · R: through ball · Q/E: curl',
    'hint.noBall': 'C: call for the ball · R: ask for a through ball · SPACE near the ball: one-touch',
    'hint.defend': 'Close him down · SPACE / F: tackle (double-tap: slide)',
    'hint.setPiece': 'W / S: pick your target · SPACE: strike (hold: power) · F: short pass · Q / E: curl',
    'hint.corner': 'SPACE: cross into the box · F: short pass',
    'hint.touch': 'Left: joystick · hold SHOOT · PASS',
    'touch.shoot': 'SHOOT',
    'touch.pass': 'PASS',
    'touch.through': 'THRU',
    'aim.power': 'POWER',
    'aim.curl': 'CURL',
    'aim.chip': 'CHIP',
    'replay': 'REPLAY',
    'replay.skip': 'Click / Space to skip',
    'help.title': 'Controls',
    'help.sub': 'Simple and quick — like HaxBall.',
    'help.move': 'Run',
    'help.sprint': 'Sprint',
    'help.shoot': 'Shoot — hold for more power, release to strike. Aim is automatic: the corner away from the keeper.',
    'help.curl': 'Curl while charging (left / right)',
    'help.pass': 'Pass — to the best team-mate automatically (in your running direction)',
    'help.through': 'Through ball — into space ahead of your furthest forward team-mate',
    'help.call': 'Without the ball: call for it',
    'help.defend': 'Defending: SPACE / F near the carrier = tackle, double-tap = slide',
    'help.mouseKey': 'Mouse',
    'help.mouse': 'Mouse (optional): cursor = aim, left click = shoot, right click = pass, click without the ball = run there',
    'help.setPiece': 'Free kicks / penalties: pick your target with W / S',
    'help.go': 'Press any key to start',
    'zoom.behind': 'Close',
    'zoom.broadcast': 'Medium',
    'zoom.top': 'Wide',
    'tip.open_play': 'Run at goal and press SPACE to shoot. If you are crowded out, pass with F.',
    'tip.counter': 'Drive forward with your runners: through ball with R, or finish it yourself.',
    'tip.one_on_one': 'Run at goal and press SPACE from around 14 m: the aim picks the corner.',
    'tip.cross_receive': 'Attack the cross and hold SPACE as it arrives: header or volley.',
    'tip.wing_cross': 'Beat your full-back, then cross with F or shoot with SPACE.',
    'tip.build_up': 'Keep the ball: pass to the best-placed team-mate with F.',
    'tip.defend': 'Close down the carrier and press SPACE next to him to tackle.',
    'tip.free_kick': 'Pick your corner with W / S, SPACE: a curler over the wall.',
    'tip.penalty': 'Pick your corner with W / S, hold SPACE and release.',
    'tip.corner': 'SPACE: cross to a team-mate in the box. F: short pass.',
    'tip.drill_free_kick': 'Pick your target with W / S and strike with SPACE. Corners score more!',
    'tip.drill_finishing': 'Run onto the pass and finish with SPACE.',
    'tip.drill_passing': 'Pass to your team-mates with F. Through balls (R) score extra!',
    'tip.shootout': 'Pick your corner with W / S and strike with SPACE.',
    'drill.shoot': 'Hold SPACE and release to shoot (automatic aim). W / S: target, Q / E: curl.',
    'drill.move': 'WASD / arrow keys: run, Shift: sprint.',
    'drill.pass': 'F: pass, R: through ball. On touch: joystick + SHOOT / PASS.',
    'set.title': 'Match',
    'set.view': 'Match view',
    'set.viewDesc': '2D top-down: the easiest, smoothest play with shot / pass assists. 3D: cinematic view with drag-and-release controls.',
    'set.2d': '2D (recommended)',
    'set.3d': '3D',
    'set.controls': 'Match controls (2D)',
  },
});
