/** Namespace "shell": app chrome, title, new career, hub, settings, inbox, press, overlays. */
import { registerStrings } from '../../../core/i18n';

const tr: Record<string, string> = {
  // generic
  'err.generic': 'Bir şeyler ters gitti.',
  'time.now': 'Şimdi', 'time.week1': 'Geçen hafta', 'time.weeks': '{n} hafta önce', 'time.season': '{s} sezonu',
  'fx.injury': 'Sakatlık', 'fx.weeks': '{n} hf',

  // navigation & status
  'nav.hub': 'Merkez', 'nav.inbox': 'Gelen Kutusu', 'nav.training': 'Antrenman', 'nav.lifestyle': 'Yaşam', 'nav.people': 'Çevre',
  'nav.transfers': 'Transfer', 'nav.competitions': 'Turnuvalar', 'nav.news': 'Haberler', 'nav.social': 'Sosyal', 'nav.career': 'Kariyer',
  'nav.club': 'Kulüp', 'nav.settings': 'Ayarlar', 'nav.more': 'Diğer', 'nav.save': 'Kaydet', 'nav.mainMenu': 'Ana Menü',
  'nav.saved': 'Oyun kaydedildi', 'nav.saveFail': 'Kayıt başarısız',
  'status.noClub': 'Kulüpsüz', 'status.actions': '{n} aktivite hakkın kaldı',

  // positions
  'pos.GK': 'Kaleci', 'pos.CB': 'Stoper', 'pos.FB': 'Bek', 'pos.DM': 'Ön Libero', 'pos.CM': 'Orta Saha', 'pos.AM': 'On Numara', 'pos.W': 'Kanat', 'pos.ST': 'Santrafor',
  'posShort.GK': 'KL', 'posShort.CB': 'STP', 'posShort.FB': 'BEK', 'posShort.DM': 'ÖL', 'posShort.CM': 'OS', 'posShort.AM': 'ON', 'posShort.W': 'KNT', 'posShort.ST': 'SF',
  'role.father': 'Baba', 'role.mother': 'Anne', 'role.sibling': 'Kardeş', 'role.partner': 'Partner', 'role.friend': 'Arkadaş', 'role.agent': 'Menajer',
  'role.journalist': 'Gazeteci', 'role.director': 'Sportif Direktör',
  'weather.clear': 'Açık', 'weather.cloudy': 'Bulutlu', 'weather.rain': 'Yağmurlu', 'weather.snow': 'Karlı', 'weather.fog': 'Sisli',
  'offerKind.transfer': 'Transfer', 'offerKind.loan': 'Kiralık', 'offerKind.free': 'Bedelsiz', 'offerKind.renewal': 'Yenileme', 'offerKind.trial': 'Deneme',

  // title
  'title.kicker': 'Futbol Kariyer Oyunu',
  'title.continue': 'Devam Et', 'title.continueSub': '{name} · {club} · {season} sezonu, {week}. hafta',
  'title.new': 'Yeni Kariyer', 'title.load': 'Yükle', 'title.settings': 'Ayarlar',
  'title.aiOn': 'AI: Açık', 'title.aiOff': 'AI: Kapalı', 'title.aiTip': 'Yapay zekâ anlatıcıyı Ayarlar’dan açıp kapatabilirsin',
  'title.credits': 'Tüm kulüpler, oyuncular ve olaylar kurgusaldır. Gerçek kulüp, lig ya da kişilerle bağlantısı yoktur.',
  'title.footer': 'Neo Star Soccer · v0.1 · Her kariyer farklı.',
  'title.loadTitle': 'Kayıtlı Kariyerler', 'title.loadFail': 'Kayıt yüklenemedi', 'title.noSaves': 'Henüz kayıt yok. İlk hikâyeni yaz!',
  'title.pickSlot': 'Hangi yuvaya kaydedelim?', 'title.pickSlotHint': 'Dolu bir yuvayı seçersen eski kariyerin üzerine yazılır.',
  'title.slotEmpty': 'Yuva {n} · Boş', 'title.slotEmptyHint': 'Yeni kariyer buraya kaydedilir',
  'title.overwrite': 'Üzerine yaz', 'title.overwriteTitle': 'Kariyerin üzerine yazılsın mı?', 'title.overwriteConfirm': 'Bu yuvadaki mevcut kariyer kalıcı olarak silinecek ve yeni kariyer onun yerine geçecek.',
  'title.delete': 'Sil', 'title.deleteTitle': 'Kayıt silinsin mi?', 'title.deleteConfirm': 'Bu kariyer kalıcı olarak silinecek. Bu işlem geri alınamaz.', 'title.deleted': 'Kayıt silindi',

  // new career
  'nc.title': 'Yeni Kariyer', 'nc.slot': 'Yuva {n}',
  'nc.step.name': 'İsim', 'nc.step.nation': 'Ülke', 'nc.step.position': 'Mevki', 'nc.step.look': 'Görünüm', 'nc.step.trait': 'Karakter', 'nc.step.fate': 'Kader',
  'nc.preview.noName': 'İsimsiz Yetenek',
  'nc.name.title': 'Adın ne?', 'nc.name.sub': 'Stadyum spikerinin ağzından çıkacak isim bu. İyi seç.',
  'nc.name.first': 'Ad', 'nc.name.last': 'Soyad', 'nc.name.firstPh': 'örn. Emre', 'nc.name.lastPh': 'örn. Yıldız',
  'nc.name.nick': 'Lakap (isteğe bağlı)', 'nc.name.nickPh': 'örn. Bomba', 'nc.name.nickHint': 'Tribünün sana taktığı isim. Doluysa forma ve haberlerde o görünür.',
  'nc.name.dice': 'Rastgele isim', 'nc.name.diceFail': 'İsim üretilemedi',
  'nc.nation.title': 'Nerelisin?', 'nc.nation.sub': 'Ülken; milli takımını, isim havuzunu ve köklerini belirler.',
  'nc.nation.search': 'Ülke ara…', 'nc.nation.league': 'Ligi var', 'nc.nation.empty': 'Eşleşen ülke bulunamadı', 'nc.nation.none': 'Ülke listesi yüklenemedi',
  'nc.pos.title': 'Sahadaki yerin', 'nc.pos.sub': 'Mevkin, oynayacağın anları ve gelişim yolunu belirler.',
  'nc.pos.desc.ST': 'Golün adresi. Ceza sahasında ölümcül, kaleyle arasında hep tek vuruş var.',
  'nc.pos.desc.W': 'Çizgiyi yakan hız canavarı. Çalım at, ortayı aç, içeri kat et ve falsoyla şaşırt.',
  'nc.pos.desc.AM': 'Takımın beyni. Son pası veren, serbest vuruşta topun başına geçen yaratıcı oyuncu.',
  'nc.pos.desc.CM': 'Orta sahanın motoru. Her yerde: top kap, oyunu aç, ritmi sen belirle.',
  'nc.pos.desc.FB': 'Kanadın bekçisi. 90 dakika gidip gelen; hem savunan hem ortayı açan koşucu.',
  'nc.pos.desc.CB': 'Savunmanın duvarı. Havada hâkim, ikili mücadelede acımasız; takımın sigortası.',
  'nc.look.title': 'Görünüm', 'nc.look.sub': 'Sahaya çıktığında herkes seni böyle görecek. Sonradan değişmez, iyi bak.', 'nc.look.random': 'Rastgele',
  'nc.look.foot': 'Güçlü Ayak', 'nc.look.left': 'Sol ayak', 'nc.look.right': 'Sağ ayak', 'nc.look.footHint': 'Şutlarında ve falsolarında belirleyici; zayıf ayağın zamanla gelişir.',
  'nc.look.skin': 'Ten', 'nc.look.face': 'Yüz', 'nc.look.hairStyle': 'Saç Stili', 'nc.look.hairColor': 'Saç Rengi', 'nc.look.beard': 'Sakal', 'nc.look.boots': 'Krampon',
  'nc.trait.title': 'Karakterin', 'nc.trait.sub': 'Altı özellikten birini seç. Seçtiğin özellik kariyerin boyunca peşini bırakmaz.',
  'nc.trait.hidden': 'Bazı özellikler gizli: zamanla ortaya çıkacak.', 'nc.trait.none': 'Özellik listesi yüklenemedi',
  'nc.fate.title': 'Kaderini Yaz', 'nc.fate.sub': 'Her şey hazır. Bir kere başlayınca dünya yalnızca senin için yaratılacak: kulüpler, rakipler, bir menajer ve henüz bilmediğin bir potansiyel.',
  'nc.fate.cta': 'Kaderini Yaz', 'nc.fate.name': 'Futbolcu',
  'nc.forge.world': 'Dünyan oluşturuluyor…', 'nc.forge.clubs': 'Kulüpler ve rakipler kuruluyor…', 'nc.forge.ai': 'Yapay zekâ hikâyeni yazıyor…',
  'nc.forge.story': 'Hikâyen kaleme alınıyor…', 'nc.forge.agent': 'Menajerin telefonlara sarıldı…', 'nc.forge.final': 'Son rötuşlar…',
  'nc.forge.note': 'Şablon anlatıcı çalışıyor', 'nc.forge.aiNote': 'Claude yazıyor — biraz sürebilir', 'nc.forge.fail': 'Kariyer oluşturulamadı: {msg}',
  'nc.gen.kicker': 'Kariyerin başlıyor', 'nc.gen.title': 'Hikâyen', 'nc.gen.ai': 'Claude yazdı', 'nc.gen.skip': 'Atla',
  'nc.gen.motto': 'Mottun', 'nc.gen.dream': 'Hayalin', 'nc.gen.destiny': 'Kader İşareti', 'nc.gen.people': 'Seni destekleyenler', 'nc.gen.rival': 'Rakibin', 'nc.gen.goals': 'Kariyer Hedeflerin',
  'nc.gen.next': 'Deneme Tekliflerine Geç',
  'nc.offers.kicker': 'Kapı çalındı', 'nc.offers.title': 'Deneme Teklifleri', 'nc.offers.sub': 'Üç kulüp seni denemek istiyor. İlk adımını nerede atacaksın?',
  'nc.offers.rep': 'İtibar', 'nc.offers.role': 'Rol', 'nc.offers.accept': 'Bu Kulüpte Başla',

  // hub
  'hub.title': 'Kariyer Merkezi', 'hub.noCareer': 'Aktif kariyer yok', 'hub.noCareerSub': 'Ana menüden bir kariyer yükle ya da yenisini başlat.', 'hub.toTitle': 'Ana Menüye Dön',
  'hub.next': 'Sıradaki Maç', 'hub.noMatch': 'Bu hafta maç yok', 'hub.noMatchSub': 'Dinlen, antrenman yap, hayatını yaşa.', 'hub.noMatchBreak': 'Milli ara: kulüp maçı yok.',
  'hub.played': 'Oynandı', 'hub.leg': '{n}. maç', 'hub.neutral': 'Tarafsız saha', 'hub.forecast': 'Hava tahmini',
  'hub.window': 'Transfer dönemi', 'hub.intl': 'Milli takım haftası',
  'hub.role.starter': 'İlk 11’de bekleniyor', 'hub.role.bench': 'Yedek kulübesi', 'hub.role.none': 'Kadro dışı',
  'hub.play': 'Maça Çık', 'hub.advance': 'Haftayı Bitir', 'hub.advancing': 'Hafta oynanıyor…', 'hub.advanceFail': 'Hafta ilerletilemedi',
  'hub.press': 'Basın Toplantısı', 'hub.pressShort': 'Basın', 'hub.blockers': 'Önce şunları halletmelisin', 'hub.decide': 'Karar Ver',
  'hub.noOffers': 'Şu an masada teklif yok. Bir sonraki haftada yeni kulüpler seni izleyecek.', 'hub.needsClub': 'Önce bir kulüp seç', 'hub.needsClubSub': 'Hikâyen bir imzayla başlıyor. Teklifleri incele ve yolunu çiz.',
  'hub.events': '{n} karar seni bekliyor', 'hub.formUp': 'Formda', 'hub.formDown': 'Formsuz', 'hub.formFlat': 'Dengeli',
  'hub.injured': 'Sakat · {n} hf', 'hub.noContract': 'Sözleşmesiz', 'hub.contractUntil': '{y} sezon sonuna dek', 'hub.xp': 'Gelişim: yeni puana yakın',
  'hub.rel': 'İlişkiler', 'hub.qa': 'Hızlı Eylemler', 'hub.agent': 'Menajerle Konuş', 'hub.actions': 'Haftalık aktivite hakkı: {n}/{max}',
  'hub.drills': 'Çalışmalar', 'hub.drill.freekick': 'Frikik', 'hub.drill.finishing': 'Bitiriş', 'hub.drill.passing': 'Pas',
  'hub.inbox': 'Gelen Kutusu', 'hub.inboxEmpty': 'Yeni mesaj yok', 'hub.all': 'Tümü',
  'hub.news': 'Manşetler', 'hub.newsEmpty': 'Henüz haber yok. İlk maçını bekle.', 'hub.aboutYou': 'Senin hakkında',
  'hub.tableP': 'O', 'hub.tableGD': 'Av', 'hub.tablePts': 'P',
  'hub.season': 'Sezon İstatistikleri', 'hub.starts': 'ilk 11', 'hub.avgRating': 'Ort. Puan', 'hub.motm': 'maçın adamı',
  'hub.social': 'Sosyal Medya', 'hub.socialEmpty': 'Sessizlik… henüz kimse bir şey yazmadı.',
  'hub.goals': 'Kariyer Hedefleri', 'hub.goalsDone': '{done}/{total} tamam',
  'hub.ai.on': 'Claude aktif', 'hub.ai.busy': 'Claude yazıyor…', 'hub.ai.off': 'Şablon anlatıcı', 'hub.ai.paused': 'Claude duraklatıldı', 'hub.ai.tip': 'Yapay zekâ durumu — Ayarlar’a git',

  // overlays
  'ov.event.label': 'Karar anı', 'ov.event.later': 'Sonra karar ver', 'ov.event.risk': 'Risk %{n}', 'ov.event.riskHint': 'Bu seçim kumar: sonuç şansa bağlı.',
  'ov.event.result': 'Sonuç', 'ov.event.youChose': 'Seçimin:', 'ov.event.more': '{n} karar daha bekliyor',
  'ov.week.title': '{label} Raporu', 'ov.week.yourMatches': 'Maçların', 'ov.week.noMatch': 'Bu hafta maçın yoktu.', 'ov.week.progress': 'Gelişim',
  'ov.week.noProgress': 'Bu hafta fark edilir bir gelişim olmadı.', 'ov.week.money': 'Haftalık net gelir', 'ov.week.notes': 'Notlar', 'ov.week.others': 'Diğer maçlar ({n})',
  'ov.week.seasonEnd': '{s} sezonu bitti!', 'ov.week.seasonEndSub': 'Ödüller, transferler ve yeni sezon seni bekliyor.',
  'cel.trophy': 'KUPA!', 'cel.award': 'ÖDÜL!', 'cel.levelup': 'SEVİYE ATLADIN!', 'cel.milestone': 'DÖNÜM NOKTASI!',
  'cel.levelupTitle': 'Genel {n}', 'cel.levelupSub': 'Genel güç {from} → {to}', 'cel.cta': 'Harika!',

  // inbox
  'inbox.title': 'Gelen Kutusu', 'inbox.unread': '{n} okunmamış mesaj', 'inbox.allRead': 'Hepsi okundu', 'inbox.markAll': 'Tümünü okundu yap',
  'inbox.f.all': 'Tümü', 'inbox.f.offers': 'Teklifler', 'inbox.f.events': 'Olaylar', 'inbox.f.sponsors': 'Sponsor', 'inbox.f.press': 'Basın', 'inbox.f.other': 'Diğer',
  'inbox.empty': 'Gelen kutun boş', 'inbox.emptySub': 'Kulüpler, menajerin ve hayat seni arayacak.', 'inbox.emptyFilter': 'Bu filtrede mesaj yok.', 'inbox.select': 'Okumak için bir mesaj seç',
  'inbox.kind.offer': 'Teklif', 'inbox.kind.event': 'Olay', 'inbox.kind.info': 'Bilgi', 'inbox.kind.sponsor': 'Sponsor', 'inbox.kind.callup': 'Milli davet', 'inbox.kind.award': 'Ödül',
  'inbox.kind.contract': 'Sözleşme', 'inbox.kind.manager': 'Hoca', 'inbox.kind.press': 'Basın', 'inbox.kind.injury': 'Sakatlık', 'inbox.kind.story': 'Hikâye',
  'inbox.viewOffer': 'Teklifi Gör', 'inbox.decide': 'Karar Ver', 'inbox.decided': 'Karar verildi', 'inbox.gone': 'Bu olay artık mevcut değil.', 'inbox.answered': 'Yanıtlandı',
  'inbox.until': '{y} sezonuna dek', 'inbox.toCareer': 'Kariyerime Git', 'inbox.toPress': 'Basın Toplantısına Git',
  'inbox.offerStatus.pending': 'Bekliyor', 'inbox.offerStatus.negotiating': 'Pazarlıkta', 'inbox.offerStatus.accepted': 'Kabul edildi', 'inbox.offerStatus.rejected': 'Reddedildi',
  'inbox.offerStatus.expired': 'Süresi doldu', 'inbox.offerStatus.withdrawn': 'Geri çekildi', 'inbox.offerStatus.blocked': 'Engellendi',

  // press
  'press.title': 'Basın Toplantısı', 'press.loading': 'Salon hazırlanıyor…', 'press.none': 'Şu an basın toplantısı yok', 'press.noneSub': 'Önemli bir maç, transfer ya da olay olunca gazeteciler seni arayacak.',
  'press.failed': 'Basın toplantısı başlatılamadı', 'press.back': 'Merkeze Dön',
  'press.occ.pre_match': 'Maç Öncesi Basın Toplantısı', 'press.occ.post_match': 'Maç Sonu Röportajı', 'press.occ.transfer': 'Transfer Söylentileri', 'press.occ.scandal': 'Skandal Sorusu',
  'press.occ.milestone': 'Kilometre Taşı Röportajı', 'press.occ.unveiling': 'Imza Töreni',
  'press.introSub': 'Mikrofonlar açık, flaşlar hazır. {n} soru seni bekliyor. Her cevap yarının manşeti olabilir.', 'press.enter': 'Salona Gir',
  'press.q': 'Soru {n}/{total}', 'press.yourAnswer': 'Cevabını seç', 'press.free': 'Kendi cevabını yaz', 'press.freePh': 'Gazetecilere ne diyeceksin?', 'press.prepared': 'Hazır cevaplara dön', 'press.send': 'Cevapla',
  'press.judging': 'Gazeteciler not alıyor…', 'press.headline': 'Yarınki manşet', 'press.next': 'Sonraki Soru', 'press.finish': 'Toplantıyı Bitir',
  'press.done': 'Toplantı bitti', 'press.doneSub': 'Flaşlar söndü. İşte yarınki gazetelerin söyleyecekleri.', 'press.total': 'Toplam etki',
  'press.tone.humble': 'Alçakgönüllü', 'press.tone.confident': 'Kendinden emin', 'press.tone.provocative': 'Kışkırtıcı', 'press.tone.diplomatic': 'Diplomatik', 'press.tone.emotional': 'Duygusal', 'press.tone.deflect': 'Geçiştir',
  'press.topic.rival': 'Rakip', 'press.topic.manager': 'Teknik direktör', 'press.topic.transfer': 'Transfer', 'press.topic.form': 'Form', 'press.topic.fans': 'Taraftar', 'press.topic.personal': 'Özel hayat',

  // settings
  'set.title': 'Ayarlar', 'set.subtitle': 'Dil, yapay zekâ, ses, kayıtlar ve yardım',
  'set.tab.general': 'Genel', 'set.tab.ai': 'Yapay Zekâ', 'set.tab.av': 'Görüntü & Ses', 'set.tab.saves': 'Kayıtlar', 'set.tab.help': 'Yardım',
  'set.lang': 'Dil', 'set.langDesc': 'Arayüz ve yeni üretilen hikâye metinleri bu dilde olur.',
  'set.gameplay': 'Oynanış', 'set.difficulty': 'Zorluk', 'set.difficultyDesc': 'Rakip kalitesi ve kaleci refleksleri.', 'set.diff.easy': 'Kolay', 'set.diff.normal': 'Normal', 'set.diff.hard': 'Zor',
  'set.camera': 'Kamera', 'set.cameraDesc': 'Maç anlarındaki varsayılan kamera açısı.', 'set.cam.behind': 'Arkadan', 'set.cam.broadcast': 'Yayın', 'set.cam.top': 'Kuş bakışı',
  'set.slowmo': 'Nişan alırken ağır çekim', 'set.slowmoDesc': 'Şut çizerken zaman yavaşlar; falso çizgisini rahatça ayarla.',
  'set.speed': 'Maç hızı', 'set.speedDesc': 'Maç akış ekranındaki anlatım hızı.',
  'set.gfx': 'Grafik', 'set.quality': 'Kalite', 'set.qualityDesc': 'Telefon ve eski cihazlarda “Düşük” daha akıcıdır.', 'set.q.low': 'Düşük', 'set.q.medium': 'Orta', 'set.q.high': 'Yüksek',
  'set.shadows': 'Gölgeler', 'set.shadowsDesc': 'Oyuncu ve top gölgeleri.',
  'set.audio': 'Ses', 'set.mute': 'Sesi kapat', 'set.master': 'Ana ses', 'set.sfx': 'Efektler', 'set.crowd': 'Tribün',
  'set.ai.title': 'Yapay Zekâ Anlatıcı', 'set.ai.intro': 'Kendi Claude API anahtarını girersen hikâyeni, gazeteleri, sosyal medyayı ve basın toplantılarını Claude yazar; serbest cevaplarını da o değerlendirir. Anahtarsız oyun, zengin şablonlarla eksiksiz çalışır.',
  'set.ai.enable': 'Yapay zekâyı etkinleştir', 'set.ai.key': 'Claude API Anahtarı', 'set.ai.show': 'Anahtarı göster', 'set.ai.hide': 'Anahtarı gizle',
  'set.ai.model': 'Model', 'set.ai.modelDesc': 'Opus en iyi yazar, Haiku en hızlı ve en ucuz olandır.', 'set.ai.features': 'Özellikler',
  'set.ai.test': 'Bağlantıyı Test Et', 'set.ai.testing': 'Test ediliyor…', 'set.ai.noKey': 'Önce bir anahtar gir.',
  'set.ai.privacyTitle': 'Gizlilik ve maliyet',
  'set.ai.privacy': 'Anahtarın yalnızca bu tarayıcının localStorage alanında saklanır ve sadece api.anthropic.com adresine gönderilir. Oyunun sunucusu yoktur; başka hiçbir yere iletilmez.',
  'set.ai.cost': 'İstekler senin Anthropic hesabından ücretlendirilir. Maliyeti düşürmek için daha küçük bir model seç ya da kullanmadığın özellikleri kapat.',
  'set.saves.slots': 'Kayıt yuvaları', 'set.saves.where': 'Kayıtlar yalnızca bu tarayıcıda saklanır. Yedek almak için dışa aktar.',
  'set.saves.backup': 'Yedekle & Geri Yükle', 'set.saves.export': 'Kariyeri Dışa Aktar (JSON)', 'set.saves.exportNone': 'Önce bir kariyer yükle.', 'set.saves.exported': 'Kayıt dosyası indirildi',
  'set.saves.importInto': 'İçe aktarılacak yuva', 'set.saves.import': 'Dosyadan İçe Aktar', 'set.saves.imported': 'Kayıt {n}. yuvaya aktarıldı', 'set.saves.importFail': 'İçe aktarma başarısız',
  'set.saves.importOver': 'Dikkat: {n}. yuvadaki kayıt üzerine yazılacak.',
  'set.help.curlTitle': 'Falso Çizgisi', 'set.help.drawn': 'Çizdiğin yay', 'set.help.ball': 'Topun gerçek yolu', 'set.help.wall': 'baraj',
  'set.help.curlBody': 'Oyunun imzası bu: şutu bir çizgi gibi çizersin, çizgiyi yay gibi bükersen top ters yöne döner. Sağa doğru kavis çizersen top sola kıvrılır; barajın üstünden dolanıp kalecinin yetişemediği köşeye gider. Çizgi uzadıkça şut sertleşir.',
  'set.help.controls': 'Kontroller',
  'set.help.move.t': 'Koş', 'set.help.move.d': 'Sahaya dokun ya da WASD / ok tuşları. Shift veya DEPAR ile hızlan.',
  'set.help.shoot.t': 'Şut ve pas', 'set.help.shoot.d': 'Topa bas, hedefe doğru sürükle, bırak. Çizgi ne kadar uzunsa vuruş o kadar sert.',
  'set.help.curl.t': 'Falso', 'set.help.curl.d': 'Çizgiyi yay gibi bük: kavisin tersine döner. Barajı aşmanın ve kaleciyi şaşırtmanın yolu.',
  'set.help.loft.t': 'Yükseklik', 'set.help.loft.d': 'Sağdaki çubuk (ya da tekerlek, Q / E) topun havalanmasını ayarlar: yerden pas mı, aşırtma mı?',
  'set.help.after.t': 'Son an falsosu', 'set.help.after.d': 'Vurduktan hemen sonra yana kaydır: top uçarken ekstra falso ver.',
  'set.help.pass.t': 'Pas iste', 'set.help.pass.d': 'Topsuzken PAS! ya da Boşluk: topu iste. Önüne çift dokun: ara pas iste.',
  'set.help.defend.t': 'Savunma', 'set.help.defend.d': 'Top sahibine yakınken dokun: müdahale. Çift dokun: kayarak müdahale.',
  'set.help.camera.t': 'Kamera', 'set.help.camera.d': 'Kamera düğmesi ya da C tuşu: açıyı değiştir.',
  'set.about.title': 'Hakkında', 'set.about.body': 'Neo Star Soccer; klasik futbol kariyer oyunlarına saygı duruşu olarak yapılmış, yapay zekâ destekli, modern ve kişisel bir kariyer simülasyonudur. Her kariyer farklı bir dünya, farklı bir rakip ve farklı bir kader getirir.',
};

const en: Record<string, string> = {
  'err.generic': 'Something went wrong.',
  'time.now': 'Now', 'time.week1': 'Last week', 'time.weeks': '{n} weeks ago', 'time.season': 'Season {s}',
  'fx.injury': 'Injury', 'fx.weeks': '{n} wk',

  'nav.hub': 'Hub', 'nav.inbox': 'Inbox', 'nav.training': 'Training', 'nav.lifestyle': 'Lifestyle', 'nav.people': 'People',
  'nav.transfers': 'Transfers', 'nav.competitions': 'Competitions', 'nav.news': 'News', 'nav.social': 'Social', 'nav.career': 'Career',
  'nav.club': 'Club', 'nav.settings': 'Settings', 'nav.more': 'More', 'nav.save': 'Save', 'nav.mainMenu': 'Main Menu',
  'nav.saved': 'Game saved', 'nav.saveFail': 'Save failed',
  'status.noClub': 'Free agent', 'status.actions': '{n} activity slots left',

  'pos.GK': 'Goalkeeper', 'pos.CB': 'Centre-back', 'pos.FB': 'Full-back', 'pos.DM': 'Holding Mid', 'pos.CM': 'Midfielder', 'pos.AM': 'Playmaker', 'pos.W': 'Winger', 'pos.ST': 'Striker',
  'posShort.GK': 'GK', 'posShort.CB': 'CB', 'posShort.FB': 'FB', 'posShort.DM': 'DM', 'posShort.CM': 'CM', 'posShort.AM': 'AM', 'posShort.W': 'W', 'posShort.ST': 'ST',
  'role.father': 'Father', 'role.mother': 'Mother', 'role.sibling': 'Sibling', 'role.partner': 'Partner', 'role.friend': 'Friend', 'role.agent': 'Agent',
  'role.journalist': 'Journalist', 'role.director': 'Sporting Director',
  'weather.clear': 'Clear', 'weather.cloudy': 'Cloudy', 'weather.rain': 'Rain', 'weather.snow': 'Snow', 'weather.fog': 'Fog',
  'offerKind.transfer': 'Transfer', 'offerKind.loan': 'Loan', 'offerKind.free': 'Free', 'offerKind.renewal': 'Renewal', 'offerKind.trial': 'Trial',

  'title.kicker': 'A Football Career Game',
  'title.continue': 'Continue', 'title.continueSub': '{name} · {club} · {season}, week {week}',
  'title.new': 'New Career', 'title.load': 'Load', 'title.settings': 'Settings',
  'title.aiOn': 'AI: On', 'title.aiOff': 'AI: Off', 'title.aiTip': 'Turn the AI narrator on or off in Settings',
  'title.credits': 'All clubs, players and events are fictional. Any resemblance to real clubs, leagues or people is coincidental.',
  'title.footer': 'Neo Star Soccer · v0.1 · Every career is different.',
  'title.loadTitle': 'Saved Careers', 'title.loadFail': 'Could not load the save', 'title.noSaves': 'No saves yet. Write your first story!',
  'title.pickSlot': 'Which slot should we use?', 'title.pickSlotHint': 'Picking a used slot overwrites the career stored there.',
  'title.slotEmpty': 'Slot {n} · Empty', 'title.slotEmptyHint': 'The new career will be saved here',
  'title.overwrite': 'Overwrite', 'title.overwriteTitle': 'Overwrite this career?', 'title.overwriteConfirm': 'The career in this slot will be permanently deleted and replaced by the new one.',
  'title.delete': 'Delete', 'title.deleteTitle': 'Delete this save?', 'title.deleteConfirm': 'This career will be deleted permanently. This cannot be undone.', 'title.deleted': 'Save deleted',

  'nc.title': 'New Career', 'nc.slot': 'Slot {n}',
  'nc.step.name': 'Name', 'nc.step.nation': 'Nation', 'nc.step.position': 'Position', 'nc.step.look': 'Look', 'nc.step.trait': 'Trait', 'nc.step.fate': 'Fate',
  'nc.preview.noName': 'Nameless Talent',
  'nc.name.title': 'What’s your name?', 'nc.name.sub': 'The stadium announcer will say it aloud. Choose well.',
  'nc.name.first': 'First name', 'nc.name.last': 'Surname', 'nc.name.firstPh': 'e.g. Marco', 'nc.name.lastPh': 'e.g. Silva',
  'nc.name.nick': 'Nickname (optional)', 'nc.name.nickPh': 'e.g. Rocket', 'nc.name.nickHint': 'The name the terraces gave you. If filled, it shows on shirts and in headlines.',
  'nc.name.dice': 'Random name', 'nc.name.diceFail': 'Could not generate a name',
  'nc.nation.title': 'Where are you from?', 'nc.nation.sub': 'Your nation sets your national team, name pool and roots.',
  'nc.nation.search': 'Search nations…', 'nc.nation.league': 'Has a league', 'nc.nation.empty': 'No matching nation', 'nc.nation.none': 'Could not load the nation list',
  'nc.pos.title': 'Your place on the pitch', 'nc.pos.sub': 'Your position decides the moments you play and how you grow.',
  'nc.pos.desc.ST': 'The home of goals. Lethal in the box — always one touch away from the net.',
  'nc.pos.desc.W': 'Pace down the line. Dribble, cross, cut inside and surprise with a curler.',
  'nc.pos.desc.AM': 'The team’s brain. The creator of the final pass and the one over the free kick.',
  'nc.pos.desc.CM': 'The engine room. Everywhere at once: win it, spread it, set the tempo.',
  'nc.pos.desc.FB': 'The flank’s guardian. A 90-minute runner who defends and delivers crosses.',
  'nc.pos.desc.CB': 'The defensive wall. Commands the air, ruthless in duels — the team’s insurance.',
  'nc.look.title': 'Appearance', 'nc.look.sub': 'This is how everyone will see you on the pitch. Take a good look.', 'nc.look.random': 'Randomize',
  'nc.look.foot': 'Strong Foot', 'nc.look.left': 'Left foot', 'nc.look.right': 'Right foot', 'nc.look.footHint': 'It decides your shots and curl; your weaker foot improves over time.',
  'nc.look.skin': 'Skin', 'nc.look.face': 'Face', 'nc.look.hairStyle': 'Hair Style', 'nc.look.hairColor': 'Hair Colour', 'nc.look.beard': 'Beard', 'nc.look.boots': 'Boots',
  'nc.trait.title': 'Your character', 'nc.trait.sub': 'Pick one of six traits. It will follow you through your whole career.',
  'nc.trait.hidden': 'Some traits are hidden — they will reveal themselves over time.', 'nc.trait.none': 'Could not load the trait list',
  'nc.fate.title': 'Write Your Destiny', 'nc.fate.sub': 'Everything is ready. Once you begin, a world is created just for you: clubs, rivals, an agent and a potential you do not know yet.',
  'nc.fate.cta': 'Write Your Destiny', 'nc.fate.name': 'Player',
  'nc.forge.world': 'Building your world…', 'nc.forge.clubs': 'Founding clubs and rivals…', 'nc.forge.ai': 'AI is writing your story…',
  'nc.forge.story': 'Your story is being written…', 'nc.forge.agent': 'Your agent is working the phones…', 'nc.forge.final': 'Final touches…',
  'nc.forge.note': 'Template narrator at work', 'nc.forge.aiNote': 'Claude is writing — this may take a moment', 'nc.forge.fail': 'Could not create the career: {msg}',
  'nc.gen.kicker': 'Your career begins', 'nc.gen.title': 'Your Story', 'nc.gen.ai': 'Written by Claude', 'nc.gen.skip': 'Skip',
  'nc.gen.motto': 'Your motto', 'nc.gen.dream': 'Your dream', 'nc.gen.destiny': 'Sign of Destiny', 'nc.gen.people': 'Those behind you', 'nc.gen.rival': 'Your rival', 'nc.gen.goals': 'Career Goals',
  'nc.gen.next': 'On to the Trial Offers',
  'nc.offers.kicker': 'A knock at the door', 'nc.offers.title': 'Trial Offers', 'nc.offers.sub': 'Three clubs want to see you. Where will you take your first step?',
  'nc.offers.rep': 'Reputation', 'nc.offers.role': 'Role', 'nc.offers.accept': 'Start Here',

  'hub.title': 'Career Hub', 'hub.noCareer': 'No active career', 'hub.noCareerSub': 'Load a career or start a new one from the main menu.', 'hub.toTitle': 'Back to Main Menu',
  'hub.next': 'Next Match', 'hub.noMatch': 'No match this week', 'hub.noMatchSub': 'Rest, train, live your life.', 'hub.noMatchBreak': 'International break: no club match.',
  'hub.played': 'Played', 'hub.leg': 'Leg {n}', 'hub.neutral': 'Neutral venue', 'hub.forecast': 'Weather forecast',
  'hub.window': 'Transfer window', 'hub.intl': 'International week',
  'hub.role.starter': 'Expected to start', 'hub.role.bench': 'On the bench', 'hub.role.none': 'Out of the squad',
  'hub.play': 'Play Match', 'hub.advance': 'End Week', 'hub.advancing': 'Playing the week…', 'hub.advanceFail': 'Could not advance the week',
  'hub.press': 'Press Conference', 'hub.pressShort': 'Press', 'hub.blockers': 'First you need to sort out', 'hub.decide': 'Decide',
  'hub.noOffers': 'No offers on the table right now. New clubs will be watching you next week.', 'hub.needsClub': 'Choose a club first', 'hub.needsClubSub': 'Your story starts with a signature. Study the offers and pick your path.',
  'hub.events': '{n} decisions are waiting', 'hub.formUp': 'In form', 'hub.formDown': 'Out of form', 'hub.formFlat': 'Steady',
  'hub.injured': 'Injured · {n} wk', 'hub.noContract': 'No contract', 'hub.contractUntil': 'Until the end of {y}', 'hub.xp': 'Growth: close to a new point',
  'hub.rel': 'Relationships', 'hub.qa': 'Quick Actions', 'hub.agent': 'Talk to Agent', 'hub.actions': 'Weekly activity slots: {n}/{max}',
  'hub.drills': 'Drills', 'hub.drill.freekick': 'Free kick', 'hub.drill.finishing': 'Finishing', 'hub.drill.passing': 'Passing',
  'hub.inbox': 'Inbox', 'hub.inboxEmpty': 'No new messages', 'hub.all': 'All',
  'hub.news': 'Headlines', 'hub.newsEmpty': 'No news yet. Wait for your first match.', 'hub.aboutYou': 'About you',
  'hub.tableP': 'P', 'hub.tableGD': 'GD', 'hub.tablePts': 'Pts',
  'hub.season': 'Season Stats', 'hub.starts': 'starts', 'hub.avgRating': 'Avg Rating', 'hub.motm': 'MOTM',
  'hub.social': 'Social Media', 'hub.socialEmpty': 'Silence… nobody has posted yet.',
  'hub.goals': 'Career Goals', 'hub.goalsDone': '{done}/{total} done',
  'hub.ai.on': 'Claude active', 'hub.ai.busy': 'Claude is writing…', 'hub.ai.off': 'Template narrator', 'hub.ai.paused': 'Claude paused', 'hub.ai.tip': 'AI status — open Settings',

  'ov.event.label': 'Decision time', 'ov.event.later': 'Decide later', 'ov.event.risk': 'Risk {n}%', 'ov.event.riskHint': 'This choice is a gamble: the outcome depends on luck.',
  'ov.event.result': 'Result', 'ov.event.youChose': 'Your choice:', 'ov.event.more': '{n} more decisions waiting',
  'ov.week.title': '{label} Report', 'ov.week.yourMatches': 'Your matches', 'ov.week.noMatch': 'You had no match this week.', 'ov.week.progress': 'Progress',
  'ov.week.noProgress': 'No noticeable progress this week.', 'ov.week.money': 'Weekly net income', 'ov.week.notes': 'Notes', 'ov.week.others': 'Other results ({n})',
  'ov.week.seasonEnd': 'The {s} season is over!', 'ov.week.seasonEndSub': 'Awards, transfers and a new season await.',
  'cel.trophy': 'TROPHY!', 'cel.award': 'AWARD!', 'cel.levelup': 'LEVEL UP!', 'cel.milestone': 'MILESTONE!',
  'cel.levelupTitle': 'Overall {n}', 'cel.levelupSub': 'Overall rating {from} → {to}', 'cel.cta': 'Awesome!',

  'inbox.title': 'Inbox', 'inbox.unread': '{n} unread messages', 'inbox.allRead': 'All caught up', 'inbox.markAll': 'Mark all read',
  'inbox.f.all': 'All', 'inbox.f.offers': 'Offers', 'inbox.f.events': 'Events', 'inbox.f.sponsors': 'Sponsors', 'inbox.f.press': 'Press', 'inbox.f.other': 'Other',
  'inbox.empty': 'Your inbox is empty', 'inbox.emptySub': 'Clubs, your agent and life itself will be in touch.', 'inbox.emptyFilter': 'No messages in this filter.', 'inbox.select': 'Select a message to read',
  'inbox.kind.offer': 'Offer', 'inbox.kind.event': 'Event', 'inbox.kind.info': 'Info', 'inbox.kind.sponsor': 'Sponsor', 'inbox.kind.callup': 'Call-up', 'inbox.kind.award': 'Award',
  'inbox.kind.contract': 'Contract', 'inbox.kind.manager': 'Manager', 'inbox.kind.press': 'Press', 'inbox.kind.injury': 'Injury', 'inbox.kind.story': 'Story',
  'inbox.viewOffer': 'View Offer', 'inbox.decide': 'Decide', 'inbox.decided': 'Decision made', 'inbox.gone': 'This event is no longer available.', 'inbox.answered': 'Answered',
  'inbox.until': 'Until {y}', 'inbox.toCareer': 'Go to My Career', 'inbox.toPress': 'Go to the Press Conference',
  'inbox.offerStatus.pending': 'Pending', 'inbox.offerStatus.negotiating': 'Negotiating', 'inbox.offerStatus.accepted': 'Accepted', 'inbox.offerStatus.rejected': 'Rejected',
  'inbox.offerStatus.expired': 'Expired', 'inbox.offerStatus.withdrawn': 'Withdrawn', 'inbox.offerStatus.blocked': 'Blocked',

  'press.title': 'Press Conference', 'press.loading': 'Setting up the room…', 'press.none': 'No press conference right now', 'press.noneSub': 'When a big match, transfer or story breaks, the journalists will call.',
  'press.failed': 'Could not start the press conference', 'press.back': 'Back to Hub',
  'press.occ.pre_match': 'Pre-Match Press Conference', 'press.occ.post_match': 'Post-Match Interview', 'press.occ.transfer': 'Transfer Rumours', 'press.occ.scandal': 'Scandal Questions',
  'press.occ.milestone': 'Milestone Interview', 'press.occ.unveiling': 'Unveiling',
  'press.introSub': 'Microphones are live, flashes are ready. {n} questions await. Every answer could be tomorrow’s headline.', 'press.enter': 'Enter the Room',
  'press.q': 'Question {n}/{total}', 'press.yourAnswer': 'Choose your answer', 'press.free': 'Write your own answer', 'press.freePh': 'What will you tell the journalists?', 'press.prepared': 'Back to prepared answers', 'press.send': 'Answer',
  'press.judging': 'The journalists are taking notes…', 'press.headline': 'Tomorrow’s headline', 'press.next': 'Next Question', 'press.finish': 'End the Conference',
  'press.done': 'Conference over', 'press.doneSub': 'The flashes have faded. Here is what tomorrow’s papers will say.', 'press.total': 'Total impact',
  'press.tone.humble': 'Humble', 'press.tone.confident': 'Confident', 'press.tone.provocative': 'Provocative', 'press.tone.diplomatic': 'Diplomatic', 'press.tone.emotional': 'Emotional', 'press.tone.deflect': 'Deflect',
  'press.topic.rival': 'Rival', 'press.topic.manager': 'Manager', 'press.topic.transfer': 'Transfer', 'press.topic.form': 'Form', 'press.topic.fans': 'Fans', 'press.topic.personal': 'Personal life',

  'set.title': 'Settings', 'set.subtitle': 'Language, AI, sound, saves and help',
  'set.tab.general': 'General', 'set.tab.ai': 'AI', 'set.tab.av': 'Display & Sound', 'set.tab.saves': 'Saves', 'set.tab.help': 'Help',
  'set.lang': 'Language', 'set.langDesc': 'The interface and newly generated story text use this language.',
  'set.gameplay': 'Gameplay', 'set.difficulty': 'Difficulty', 'set.difficultyDesc': 'Opponent quality and goalkeeper reflexes.', 'set.diff.easy': 'Easy', 'set.diff.normal': 'Normal', 'set.diff.hard': 'Hard',
  'set.camera': 'Camera', 'set.cameraDesc': 'Default camera angle in match moments.', 'set.cam.behind': 'Behind', 'set.cam.broadcast': 'Broadcast', 'set.cam.top': 'Top-down',
  'set.slowmo': 'Slow motion while aiming', 'set.slowmoDesc': 'Time slows while you draw a shot, so you can set the curl line calmly.',
  'set.speed': 'Match speed', 'set.speedDesc': 'Commentary speed on the match ticker.',
  'set.gfx': 'Graphics', 'set.quality': 'Quality', 'set.qualityDesc': '“Low” runs smoother on phones and older devices.', 'set.q.low': 'Low', 'set.q.medium': 'Medium', 'set.q.high': 'High',
  'set.shadows': 'Shadows', 'set.shadowsDesc': 'Player and ball shadows.',
  'set.audio': 'Audio', 'set.mute': 'Mute all', 'set.master': 'Master volume', 'set.sfx': 'Effects', 'set.crowd': 'Crowd',
  'set.ai.title': 'AI Narrator', 'set.ai.intro': 'Enter your own Claude API key and Claude writes your story, the newspapers, social media and press conferences — and judges your free-text answers. Without a key the game works fully with rich templates.',
  'set.ai.enable': 'Enable AI', 'set.ai.key': 'Claude API Key', 'set.ai.show': 'Show key', 'set.ai.hide': 'Hide key',
  'set.ai.model': 'Model', 'set.ai.modelDesc': 'Opus writes best; Haiku is the fastest and cheapest.', 'set.ai.features': 'Features',
  'set.ai.test': 'Test Connection', 'set.ai.testing': 'Testing…', 'set.ai.noKey': 'Enter a key first.',
  'set.ai.privacyTitle': 'Privacy and cost',
  'set.ai.privacy': 'Your key is stored only in this browser’s localStorage and is sent only to api.anthropic.com. The game has no server of its own; nothing is forwarded anywhere else.',
  'set.ai.cost': 'Requests are billed to your own Anthropic account. To keep costs down, pick a smaller model or switch off features you do not use.',
  'set.saves.slots': 'Save slots', 'set.saves.where': 'Saves live in this browser only. Export a backup to be safe.',
  'set.saves.backup': 'Backup & Restore', 'set.saves.export': 'Export Career (JSON)', 'set.saves.exportNone': 'Load a career first.', 'set.saves.exported': 'Save file downloaded',
  'set.saves.importInto': 'Import into slot', 'set.saves.import': 'Import from File', 'set.saves.imported': 'Save imported into slot {n}', 'set.saves.importFail': 'Import failed',
  'set.saves.importOver': 'Careful: the save in slot {n} will be overwritten.',
  'set.help.curlTitle': 'The Curl Line', 'set.help.drawn': 'Your drawn bow', 'set.help.ball': 'The ball’s real path', 'set.help.wall': 'wall',
  'set.help.curlBody': 'This is the game’s signature: you draw the shot as a line, and if you bend the line like a bow the ball swerves the opposite way. Bow it to the right and the ball bends left — around the wall and into the corner the keeper can’t reach. The longer the line, the harder the strike.',
  'set.help.controls': 'Controls',
  'set.help.move.t': 'Run', 'set.help.move.d': 'Tap the pitch or use WASD / arrow keys. Shift or SPRINT to accelerate.',
  'set.help.shoot.t': 'Shoot & pass', 'set.help.shoot.d': 'Press on the ball, drag toward the target, release. The longer the line, the harder the strike.',
  'set.help.curl.t': 'Curl', 'set.help.curl.d': 'Bend the line like a bow: the ball curves the opposite way. How you beat the wall and fool the keeper.',
  'set.help.loft.t': 'Loft', 'set.help.loft.d': 'The bar on the right (or wheel, Q / E) sets the height: a ground pass or a chip?',
  'set.help.after.t': 'Late curl', 'set.help.after.d': 'Right after striking, swipe sideways: add extra curl while the ball is in flight.',
  'set.help.pass.t': 'Call for the ball', 'set.help.pass.d': 'Off the ball, press PASS! or Space to call for it. Double-tap ahead for a through ball.',
  'set.help.defend.t': 'Defend', 'set.help.defend.d': 'Tap the ball carrier when close: tackle. Double-tap: slide tackle.',
  'set.help.camera.t': 'Camera', 'set.help.camera.d': 'The camera button or C key changes the angle.',
  'set.about.title': 'About', 'set.about.body': 'Neo Star Soccer is an AI-assisted, modern and personal career simulation made as a tribute to classic football career games. Every career brings a different world, a different rival and a different destiny.',
};

registerStrings('shell', { tr, en });
