import { registerStrings } from '../../core/i18n';

/**
 * Namespace 'match' — live ticker, moment titles/tips/outcomes, fallback commentary
 * and every label of the match & drill screens.
 *
 * Turkish lines never attach case suffixes to {player}/{team} placeholders
 * (vowel harmony would break on arbitrary names).
 */
registerStrings('match', {
  tr: {
    // ── fallback commentary (used when narrative is unavailable) ──
    'c.kickoff.0': 'İlk düdük çaldı! {team} santrayı yaptı, mücadele başladı.',
    'c.kickoff.1': 'Ve maç başladı! Tribünler ayakta, {team} topla buluşuyor.',
    'c.kickoff.2': 'Hakem düdüğü çaldı, bu akşamın hikâyesi yazılmaya başlıyor!',
    'c.kickoff2.0': 'İkinci yarı başladı! Skor {score}.',
    'c.kickoff2.1': 'Takımlar sahada, ikinci 45 dakika başlıyor. Tabela {score}.',
    'c.kickoff2.2': 'Soyunma odasından dönüldü, ikinci yarıda top yeniden yuvarlanıyor. {score}',
    'c.goal.0': 'GOOOL! {player} ağları sarstı! {team} sevinçten çılgına döndü. {score}',
    'c.goal.1': '{player} affetmedi! Top filelerde, skor {score}.',
    'c.goal.2': 'Ve gol! {player} soğukkanlı bitirdi. {score}',
    'c.goal.3': 'Muhteşem! {player} vuruyor ve gol! Tribünler yıkılıyor! {score}',
    'c.goal.4': '{team} golü buldu! {player} kaleciye şans tanımadı. {score}',
    'c.own_goal.0': 'Talihsiz an! {player} topu kendi ağlarına gönderdi. {score}',
    'c.own_goal.1': 'Kendi kalesine! {player} için unutulmak istenecek bir an. {score}',
    'c.penalty_goal.0': 'Penaltı golü! {player} topu köşeye yerleştirdi. {score}',
    'c.penalty_goal.1': '{player} beyaz noktadan affetmedi; kaleci bir yana, top bir yana! {score}',
    'c.penalty_miss.0': 'Penaltı kaçtı! Vuruşu yapan {player}, ellerini başına götürdü.',
    'c.penalty_miss.1': 'İnanılmaz! {player} beyaz noktada hata yaptı, top dışarıda!',
    'c.yellow.0': 'Sarı kart! {player} sert müdahalesinin ardından hakemin defterine yazıldı.',
    'c.yellow.1': 'Hakem cebine gitti: {player} için sarı kart.',
    'c.yellow.2': '{player} itirazın bedelini sarı kartla ödedi.',
    'c.red.0': 'KIRMIZI KART! {player} oyundan atıldı, {team} 10 kişi kaldı!',
    'c.red.1': 'Hakem tereddüt etmedi, direkt kırmızı! {player} soyunma odasının yolunu tutuyor.',
    'c.red2.0': 'İkinci sarıdan kırmızı! {player} oyun dışı, {team} eksik kaldı.',
    'c.injury.0': '{player} yerde kaldı, sağlık ekibi sahada. Devam edemeyecek gibi görünüyor.',
    'c.injury.1': 'Kötü haber: {player} sakatlandı ve kenara işaret ediyor.',
    'c.sub.0': '{team} değişikliğe gitti: {player} oyuna girdi, {extra} kenara geldi.',
    'c.sub.1': 'Oyuncu değişikliği. {player} oyunda, {extra} dinlenmeye çekildi.',
    'c.chance.0': '{player} müthiş bir fırsatı kaçırdı! Top az farkla auta gitti.',
    'c.chance.1': 'Ohh! {player} kafayı vurdu, top direğin yanından dışarıda.',
    'c.chance.2': '{player} vurdu, top üstten auta! Büyük fırsattı.',
    'c.save.0': '{player} harika bir kurtarışla gole izin vermedi!',
    'c.save.1': 'Kurtarış! {player} topu köşeden çıkardı.',
    'c.save.2': '{player} yerinde! Uzanıp topu kornere çeldi.',
    'c.woodwork.0': 'DİREK! {player} vurdu, top direkten döndü!',
    'c.woodwork.1': 'Üst direk! {player} çok şanssız.',
    'c.halftime.0': 'İlk yarının sonu: {score}.',
    'c.halftime.1': 'Hakem ilk yarıyı bitirdi. Skor {score}.',
    'c.halftime.2': 'Devre arası! Takımlar soyunma odasına gidiyor, tabela {score}.',
    'c.fulltime.0': 'Maç sona erdi! Skor: {score}.',
    'c.fulltime.1': 'Son düdük! Tabela {score} gösteriyor.',
    'c.fulltime.2': 'Ve bitti! {score}.',
    'c.var.0': 'VAR devrede... Gol iptal edildi! {team} tribünleri buz kesti.',
    'c.var.1': 'VAR incelemesinin ardından gol geçersiz sayıldı!',
    'c.extra_time.0': 'Normal süre {score} bitti, uzatmalara gidiyoruz!',
    'c.extra_time.1': 'Kazanan yok! 30 dakikalık uzatma bizi bekliyor. {score}',
    'c.shootout.0': 'Seri penaltılar! Kazananı sinirler belirleyecek.',
    'c.moment.0': '{player} oyunun merkezinde!',

    // ── extra live lines ──
    'pressure.0': '{team} baskıyı artırdı, top hep rakip yarı sahada.',
    'pressure.1': '{team} oyunun kontrolünü ele geçirdi, tribünler takımını itiyor!',
    'pressure.2': '{team} rakibini kendi yarı sahasına hapsetti.',
    'ht.extra': 'Uzatmaların ilk yarısı bitti. {score}',
    'et.second': 'Uzatmaların ikinci yarısı başladı!',
    'stoppage': 'Dördüncü hakem tabelayı kaldırdı: +{n} dakika.',
    'pen.scored': '{team} — {player} gol! Seri penaltılar: {score}',
    'pen.missed': '{team} — {player} kaçırdı! Seri penaltılar: {score}',
    'pen.saved': '{team} — {player} vuruşunda kaleci kurtardı! Seri penaltılar: {score}',
    'pen.winner': '{team} seri penaltılarda kazandı! ({score})',
    'agg.winner': '{team} toplam skorla tur atladı! (Toplam {score})',
    'user.subOn': 'Hoca seni çağırdı! {player} ısınmayı bitirip oyuna giriyor.',
    'user.subOff': '{player} kenara çağrıldı. Bugünlük bu kadar.',
    'user.subOffInjured': '{player} sakatlık nedeniyle oyuna devam edemiyor.',
    'user.yellow': '{player} sarı kart gördü. Dikkat, bir sarı daha kırmızı demek!',
    'user.red': 'KIRMIZI KART! {player} oyundan atıldı! Takımını 10 kişi bıraktı.',
    'assistBy': 'Asist: {name}',
    'setpiece.fk': '{player} serbest vuruşu kullandı...',
    'setpiece.corner': '{player} korneri ceza sahasına astı...',
    'oppPenalty': '{team} lehine penaltı! Topun başında {player}...',

    // ── user moment outcomes (ticker) ──
    'o.goal': '{player} sahnede! Muhteşem bir golle skoru değiştirdi.',
    'o.assist': '{player} ustaca bir pasla golü hazırladı!',
    'o.chance_created': '{player} müthiş bir pozisyon hazırladı ama arkadaşları değerlendiremedi.',
    'o.saved': '{player} vurdu ama kaleci geçit vermedi.',
    'o.missed': '{player} şutunu çekti, top auta gitti.',
    'o.woodwork': '{player} vurdu, top direkten döndü!',
    'o.blocked': '{player} vurdu, top savunmaya çarptı.',
    'o.lost_ball': '{player} topu kaptırdı, atak sonuçsuz.',
    'o.offside': '{player} ofsayta yakalandı.',
    'o.foul_won': '{player} faul aldı, tehlikeli bölgede serbest vuruş!',
    'o.penalty_won': '{player} ceza sahasında yere indirildi — PENALTI!',
    'o.tackle_won': '{player} kusursuz bir müdahaleyle topu kaptı.',
    'o.interception': '{player} araya girip atağı kesti.',
    'o.tackle_lost': '{player} rakibini durduramadı.',
    'o.foul_conceded': '{player} faul yaptı, hakem düdüğü çaldı.',
    'o.pass_completed': '{player} isabetli pasıyla oyunu yönlendirdi.',
    'o.cleared': '{player} tehlikeyi uzaklaştırdı.',
    'o.conceded': '{player} rakibini durduramadı ve gol geldi.',
    'o.timeout': '{player} için pozisyon sonuçsuz kaldı.',
    'o.drill_complete': '{player} antrenmanı tamamladı.',

    // ── moment titles / tips ──
    'mt.open_play': 'POZİSYON!',
    'mt.counter': 'KARŞI ATAK!',
    'mt.one_on_one': 'KALECİYLE KARŞI KARŞIYA!',
    'mt.cross_receive': 'ORTA GELİYOR!',
    'mt.wing_cross': 'KANAT SENDE!',
    'mt.build_up': 'OYUN KURULUMU',
    'mt.defend': 'TEHLİKE VAR!',
    'mt.free_kick': 'SERBEST VURUŞ!',
    'mt.penalty': 'PENALTI!',
    'mt.corner': 'KORNER!',
    'mt.drill_free_kick': 'FRİKİK ANTRENMANI',
    'mt.drill_finishing': 'BİTİRİCİLİK ANTRENMANI',
    'mt.drill_passing': 'PAS ANTRENMANI',
    'mt.shootout': 'SERİ PENALTILAR!',
    'tip.open_play': 'Boşluğu bul, pası iste; fırsat doğarsa vur.',
    'tip.counter': 'Topu sürüp kaleciyle karşı karşıya kal.',
    'tip.one_on_one': 'Soğukkanlı ol: köşeyi seç ya da kaleciyi çalımla.',
    'tip.cross_receive': 'Doğru anda koşuya çık, kafayla ya da voleyle bitir.',
    'tip.wing_cross': 'Bekini geç ve ceza sahasına tehlikeli bir orta yap.',
    'tip.build_up': 'Topu kaybetme; doğru pasla atağı başlat.',
    'tip.defend': 'Rakibi karşıla, zamanlamayı tuttur ve topu kap.',
    'tip.free_kick': 'Falso Çizgisi’ni çiz: barajın üstünden ya da yanından kıvır.',
    'tip.penalty': 'Köşeni seç, gücünü ayarla, kaleciyi ters köşeye yatır.',
    'tip.corner': 'Ortanı ceza sahasına as, arkadaşların kafa için bekliyor.',
    'tip.drill_free_kick': 'Barajı aş, köşeleri bul. Her gol puan, köşeler daha çok puan!',
    'tip.drill_finishing': 'Gelen paslarla kaleciyi avla. Az dokunuş, net bitiriş.',
    'tip.drill_passing': 'Baskı altında pasları arkadaşlarına ulaştır. Ara pas ekstra puan!',
    'tip.shootout': 'Her şey bu vuruşta. Derin bir nefes al.',
    'tag.lastgasp': 'SON DAKİKA!',
    'tag.followup': 'DURAN TOP',
    'tag.shootout': 'SERİ PENALTILAR',

    // ── outcome banners ──
    'ob.goal': 'GOOOL!',
    'ob.assist': 'ASİST!',
    'ob.chance_created': 'FIRSAT YARATTIN',
    'ob.saved': 'KURTARIŞ!',
    'ob.missed': 'AUT!',
    'ob.woodwork': 'DİREK!',
    'ob.blocked': 'BLOKE!',
    'ob.lost_ball': 'TOP KAYBI',
    'ob.offside': 'OFSAYT!',
    'ob.foul_won': 'FAUL ALDIN!',
    'ob.penalty_won': 'PENALTI!',
    'ob.tackle_won': 'TOPU KAPTIN!',
    'ob.interception': 'ARAYA GİRDİN!',
    'ob.tackle_lost': 'GEÇİLDİN',
    'ob.foul_conceded': 'FAUL',
    'ob.pass_completed': 'İSABETLİ PAS',
    'ob.cleared': 'UZAKLAŞTIRDIN',
    'ob.conceded': 'GOL YEDİK',
    'ob.timeout': 'POZİSYON BİTTİ',
    'ob.drill_complete': 'ANTRENMAN BİTTİ',

    // ── periods / clock ──
    'period.pre': 'Maç öncesi',
    'period.first': '1. Yarı',
    'period.ht': 'Devre Arası',
    'period.second': '2. Yarı',
    'period.et_break': 'Uzatma',
    'period.et1': 'Uzatma 1',
    'period.et2': 'Uzatma 2',
    'period.pens': 'Penaltılar',
    'period.over': 'Maç Sonu',

    // ── screen: pre-match ──
    'pre.title': 'Maç Önü',
    'pre.stakes.derby': 'DERBİ',
    'pre.stakes.final': 'FİNAL',
    'pre.stakes.big': 'KRİTİK MAÇ',
    'pre.stakes.knockout': 'ELEME',
    'pre.stakes.normal': 'LİG MAÇI',
    'pre.attendance': '{n} seyirci',
    'pre.start': 'Maça Başla',
    'pre.simulate': 'Simüle Et',
    'pre.role.starter': 'İlk 11’desin. Sahne senin!',
    'pre.role.bench': 'Yedek kulübesindesin. Hocanın işaretini bekle.',
    'pre.role.none': 'Bu maçın kadrosunda yoksun. Maçı tribünden izleyeceksin.',
    'pre.lineups': 'Kadrolar',
    'pre.bench': 'Yedekler',
    'pre.strength': 'Güç Dengesi',
    'pre.att': 'Hücum',
    'pre.mid': 'Orta Saha',
    'pre.def': 'Savunma',
    'pre.gk': 'Kaleci',
    'pre.weather': 'Hava',
    'pre.you': 'SEN',
    'pre.formation': 'Diziliş',
    'pre.neutral': 'Tarafsız saha',
    'w.clear': 'Açık',
    'w.cloudy': 'Bulutlu',
    'w.rain': 'Yağmurlu',
    'w.snow': 'Karlı',
    'w.fog': 'Sisli',
    't.day': 'Gündüz',
    't.dusk': 'Akşamüstü',
    't.night': 'Gece',
    'wind': 'Rüzgâr {n} m/s',

    // ── screen: live ──
    'live.momentum': 'Baskı',
    'live.possession': 'Topla oynama',
    'live.shots': 'Şut',
    'live.onTarget': 'İsabetli',
    'live.xg': 'xG',
    'live.simToEnd': 'Sona Kadar Simüle Et',
    'live.pause': 'Duraklat',
    'live.resume': 'Devam',
    'live.speed': 'Hız',
    'live.yourRating': 'Canlı Puanın',
    'live.onBench': 'Yedek kulübesinde ısınıyorsun… Hocanın bir işareti yeter.',
    'live.offPitch': 'Oyundan çıktın. Takımını kenardan destekliyorsun.',
    'live.notInSquad': 'Bu maçta forma giymiyorsun.',
    'live.moments': 'An',
    'live.minutes': 'dk',
    'live.waiting': 'Maç başlamak üzere…',
    'live.feed': 'Canlı Anlatım',
    'live.shootout': 'Seri Penaltılar',
    'live.extraTime': 'UZATMALAR!',
    'live.agg': 'Toplam {score}',

    // ── screen: half-time ──
    'ht.title': 'Devre Arası',
    'ht.continue': 'İkinci Yarıyı Başlat',
    'ht.talk.win': 'Hoca soyunma odasında sakin: “Aynen böyle devam. Odağınızı kaybetmeyin.”',
    'ht.talk.draw': 'Hoca tahtaya bir şeyler çiziyor: “Bu maçı kazanabiliriz. Daha cesur olun!”',
    'ht.talk.lose': 'Soyunma odasında fırtına koptu! Hoca masaya yumruğunu vurdu: “Bu forma terlenecek!”',
    'ht.yourHalf': 'İlk yarı puanın',

    // ── screen: moment ──
    'mo.play': 'OYNA',
    'mo.simulate': 'Simüle Et',
    'mo.skip': 'Simüle et',
    'mo.camera': 'Kamera',
    'mo.replay': 'Tekrar (T)',
    'mo.continue': 'Devam',
    'mo.autostart': 'Otomatik başlıyor…',
    'mo.webglFallback': '3D görünüm açılamadı; pozisyon otomatik oynandı.',
    'mo.resolving': 'Pozisyon oynanıyor…',
    'mo.attempt': 'Deneme {n}/{m}',
    'mo.score': 'Puan {n}',
    'cam.behind': 'Oyuncu arkası',
    'cam.broadcast': 'Yayın',
    'cam.top': 'Kuşbakışı',

    // ── screen: full time ──
    'ft.title': 'Maç Sonu',
    'ft.pens': 'Penaltılar: {score}',
    'ft.yourRating': 'Maç Puanın',
    'ft.motm': 'MAÇIN ADAMI',
    'ft.motmOther': 'Maçın adamı: {name}',
    'ft.xp': 'Gelişim',
    'ft.stats': 'Senin Maçın',
    'ft.teamStats': 'Maç İstatistikleri',
    'ft.notes': 'Maçın Yansımaları',
    'ft.applying': 'Maç sonucu işleniyor…',
    'ft.continue': 'Devam',
    'ft.press': 'Basın Toplantısı',
    'ft.didNotPlay': 'Bu maçta süre almadın.',
    'ft.minutesPlayed': '{n} dakika',
    'ft.win': 'GALİBİYET',
    'ft.draw': 'BERABERLİK',
    'ft.loss': 'MAĞLUBİYET',
    'ft.applyError': 'Maç sonucu kaydedilemedi.',
    'grade.legend': 'Efsanevi',
    'grade.great': 'Harika',
    'grade.good': 'İyi',
    'grade.ok': 'Fena değil',
    'grade.poor': 'Zayıf',
    'grade.awful': 'Kötü',
    'st.goals': 'Gol',
    'st.assists': 'Asist',
    'st.shots': 'Şut (isabetli)',
    'st.passes': 'Pas',
    'st.keyPasses': 'Kilit pas',
    'st.dribbles': 'Çalım',
    'st.tackles': 'Top kapma',
    'st.interceptions': 'Araya girme',
    'st.moments': 'Oynanan an',
    'st.minutes': 'Dakika',

    // ── errors ──
    'err.noMatch': 'Maç bulunamadı.',
    'err.start': 'Maç başlatılamadı: {msg}',
    'err.back': 'Merkeze Dön',

    // ── drills ──
    'drill.team.us': 'Antrenman',
    'drill.team.them': 'Yelekliler',
    'drill.keeper': 'Kaleci',
    'drill.defender': 'Savunmacı',
    'drill.mate': 'Takım Arkadaşı',
    'drill.desc.drill_free_kick': 'Ceza sahası dışından, baraj ve kaleciye karşı frikik çalış. Falso Çizgisi’ni çizerek topu barajın üstünden kıvır; köşeler ekstra puan getirir.',
    'drill.desc.drill_finishing': 'Takım arkadaşından gelen paslarla kaleciyi avla. Hızlı karar ver, köşeleri hedefle; ilk vuruşta gol en yüksek puanı getirir.',
    'drill.desc.drill_passing': 'Baskı yapan savunmacılara rağmen pasları arkadaşlarına ulaştır. İsabet ve tempo önemli, ara paslar ekstra puan!',
    'drill.attempts': '{n} deneme',
    'drill.start': 'Antrenmana Başla',
    'drill.back': 'Antrenmana Dön',
    'drill.result': 'Antrenman Sonucu',
    'drill.score': 'Skor',
    'drill.invalid': 'Bilinmeyen antrenman türü.',
    'drill.controls': 'Kontroller',
    'drill.ctrl.aim': 'Topun üzerinden sürükle: uzunluk = güç, yay = falso.',
    'drill.ctrl.move': 'Sahaya dokun ya da WASD/ok tuşlarıyla koş.',
    'drill.ctrl.call': 'Boşluk / PAS! ile topu iste.',
    'drill.noState': 'Aktif kariyer yok.',
    'drill.rewards': 'Kazanımlar',
  },
  en: {
    'c.kickoff.0': 'The first whistle goes! {team} kick off and we are under way.',
    'c.kickoff.1': 'And we are off! The stands are on their feet as {team} get us started.',
    'c.kickoff.2': 'The referee blows, and tonight’s story begins!',
    'c.kickoff2.0': 'The second half is under way! It’s {score}.',
    'c.kickoff2.1': 'The teams are back out for the second 45. Scoreboard reads {score}.',
    'c.kickoff2.2': 'Back from the dressing rooms, the ball is rolling again. {score}',
    'c.goal.0': 'GOAL! {player} rips the net! {team} go wild. {score}',
    'c.goal.1': '{player} makes no mistake! In it goes, {score}.',
    'c.goal.2': 'And it’s a goal! Ice-cool finish from {player}. {score}',
    'c.goal.3': 'Sensational! {player} shoots and scores! The stadium erupts! {score}',
    'c.goal.4': '{team} have their goal! {player} gives the keeper no chance. {score}',
    'c.own_goal.0': 'Disaster! {player} turns it into his own net. {score}',
    'c.own_goal.1': 'Own goal! A moment {player} will want to forget. {score}',
    'c.penalty_goal.0': 'Penalty scored! {player} tucks it into the corner. {score}',
    'c.penalty_goal.1': '{player} is deadly from the spot — keeper one way, ball the other! {score}',
    'c.penalty_miss.0': 'Penalty missed! {player} can’t believe it, hands on head.',
    'c.penalty_miss.1': 'Incredible! {player} fails to convert from twelve yards!',
    'c.yellow.0': 'Yellow card! {player} goes into the book after a heavy challenge.',
    'c.yellow.1': 'The referee reaches for his pocket: yellow for {player}.',
    'c.yellow.2': '{player} pays for the dissent with a booking.',
    'c.red.0': 'RED CARD! {player} is sent off and {team} are down to ten!',
    'c.red.1': 'Straight red, no hesitation! {player} trudges off to the dressing room.',
    'c.red2.0': 'Second yellow, and that’s red! {player} is off and {team} are a man down.',
    'c.injury.0': '{player} is down and the medics are on. It doesn’t look like he can continue.',
    'c.injury.1': 'Bad news: {player} is injured and signalling to the bench.',
    'c.sub.0': 'Change for {team}: {player} comes on, {extra} makes way.',
    'c.sub.1': 'Substitution. {player} is on, {extra} takes a breather.',
    'c.chance.0': '{player} misses a glorious chance! Just wide.',
    'c.chance.1': 'Ooh! {player} gets his head to it, but it flashes past the post.',
    'c.chance.2': '{player} lets fly, over the bar! That was a big opportunity.',
    'c.save.0': '{player} with a superb save to keep it out!',
    'c.save.1': 'What a stop! {player} claws it out of the corner.',
    'c.save.2': '{player} is equal to it, tipping it round for a corner.',
    'c.woodwork.0': 'OFF THE POST! {player} strikes the woodwork!',
    'c.woodwork.1': 'Crossbar! So unlucky for {player}.',
    'c.halftime.0': 'Half-time: {score}.',
    'c.halftime.1': 'The referee brings the first half to a close. {score}.',
    'c.halftime.2': 'Half-time! The players head for the tunnel at {score}.',
    'c.fulltime.0': 'Full-time! It finishes {score}.',
    'c.fulltime.1': 'The final whistle! The scoreboard reads {score}.',
    'c.fulltime.2': 'And that’s it! {score}.',
    'c.var.0': 'VAR is checking... Goal disallowed! The {team} end falls silent.',
    'c.var.1': 'After a VAR review, the goal is ruled out!',
    'c.extra_time.0': 'Normal time ends {score} — we are going to extra time!',
    'c.extra_time.1': 'Nothing to separate them! Thirty more minutes await. {score}',
    'c.shootout.0': 'Penalties! Nerves will decide this one.',
    'c.moment.0': '{player} is at the heart of it!',

    'pressure.0': '{team} are turning the screw, camped in the opposition half.',
    'pressure.1': '{team} have taken control and the crowd is roaring them on!',
    'pressure.2': '{team} have pinned their opponents back.',
    'ht.extra': 'End of the first period of extra time. {score}',
    'et.second': 'The second period of extra time is under way!',
    'stoppage': 'The fourth official holds up the board: +{n} minutes.',
    'pen.scored': '{team} — {player} scores! Shootout: {score}',
    'pen.missed': '{team} — {player} misses! Shootout: {score}',
    'pen.saved': '{team} — {player} is denied by the keeper! Shootout: {score}',
    'pen.winner': '{team} win the shootout! ({score})',
    'agg.winner': '{team} go through on aggregate! (Aggregate {score})',
    'user.subOn': 'The manager calls for you! {player} finishes warming up and comes on.',
    'user.subOff': '{player} is called to the bench. That’s enough for today.',
    'user.subOffInjured': '{player} can’t continue because of an injury.',
    'user.yellow': '{player} is booked. Careful — another one means red!',
    'user.red': 'RED CARD! {player} is sent off and leaves the team with ten men!',
    'assistBy': 'Assist: {name}',
    'setpiece.fk': '{player} steps up to take the free kick...',
    'setpiece.corner': '{player} whips the corner into the box...',
    'oppPenalty': 'Penalty to {team}! {player} places the ball on the spot...',

    'o.goal': '{player} takes centre stage with a stunning goal!',
    'o.assist': '{player} sets it up with a perfectly weighted pass!',
    'o.chance_created': '{player} carves out a huge chance, but his teammates can’t finish it.',
    'o.saved': '{player} shoots, but the keeper stands firm.',
    'o.missed': '{player} pulls the trigger, but it’s off target.',
    'o.woodwork': '{player} rattles the woodwork!',
    'o.blocked': '{player} shoots, and it’s blocked by a defender.',
    'o.lost_ball': '{player} loses possession and the attack fizzles out.',
    'o.offside': '{player} is caught offside.',
    'o.foul_won': '{player} wins a free kick in a dangerous area!',
    'o.penalty_won': '{player} is brought down in the box — PENALTY!',
    'o.tackle_won': '{player} wins the ball with a perfect challenge.',
    'o.interception': '{player} reads it and intercepts.',
    'o.tackle_lost': '{player} can’t stop his man.',
    'o.foul_conceded': '{player} commits a foul and the referee blows.',
    'o.pass_completed': '{player} keeps things ticking with a crisp pass.',
    'o.cleared': '{player} clears the danger.',
    'o.conceded': '{player} is beaten and the opponents score.',
    'o.timeout': 'Nothing comes of the move for {player}.',
    'o.drill_complete': '{player} completes the drill.',

    'mt.open_play': 'CHANCE!',
    'mt.counter': 'COUNTER-ATTACK!',
    'mt.one_on_one': 'ONE ON ONE!',
    'mt.cross_receive': 'CROSS INCOMING!',
    'mt.wing_cross': 'DOWN THE WING!',
    'mt.build_up': 'BUILD-UP PLAY',
    'mt.defend': 'DANGER!',
    'mt.free_kick': 'FREE KICK!',
    'mt.penalty': 'PENALTY!',
    'mt.corner': 'CORNER!',
    'mt.drill_free_kick': 'FREE-KICK DRILL',
    'mt.drill_finishing': 'FINISHING DRILL',
    'mt.drill_passing': 'PASSING DRILL',
    'mt.shootout': 'PENALTY SHOOTOUT!',
    'tip.open_play': 'Find space, call for the ball, and shoot if the chance opens up.',
    'tip.counter': 'Drive forward and get one on one with the keeper.',
    'tip.one_on_one': 'Stay calm: pick your corner or round the keeper.',
    'tip.cross_receive': 'Time your run and finish with a header or a volley.',
    'tip.wing_cross': 'Beat your full-back and whip a dangerous cross into the box.',
    'tip.build_up': 'Keep the ball and start the attack with the right pass.',
    'tip.defend': 'Close down your man, time the tackle and win it back.',
    'tip.free_kick': 'Draw the curl line: bend it over or around the wall.',
    'tip.penalty': 'Pick your corner, set your power, send the keeper the wrong way.',
    'tip.corner': 'Whip it into the box — your teammates are waiting to attack it.',
    'tip.drill_free_kick': 'Beat the wall and find the corners. Every goal scores, corners score more!',
    'tip.drill_finishing': 'Finish the passes you receive. Few touches, clean finishes.',
    'tip.drill_passing': 'Find your teammates under pressure. Through balls score extra!',
    'tip.shootout': 'Everything comes down to this kick. Take a deep breath.',
    'tag.lastgasp': 'LAST GASP!',
    'tag.followup': 'SET PIECE',
    'tag.shootout': 'SHOOTOUT',

    'ob.goal': 'GOAL!',
    'ob.assist': 'ASSIST!',
    'ob.chance_created': 'CHANCE CREATED',
    'ob.saved': 'SAVED!',
    'ob.missed': 'WIDE!',
    'ob.woodwork': 'WOODWORK!',
    'ob.blocked': 'BLOCKED!',
    'ob.lost_ball': 'POSSESSION LOST',
    'ob.offside': 'OFFSIDE!',
    'ob.foul_won': 'FOUL WON!',
    'ob.penalty_won': 'PENALTY!',
    'ob.tackle_won': 'BALL WON!',
    'ob.interception': 'INTERCEPTED!',
    'ob.tackle_lost': 'BEATEN',
    'ob.foul_conceded': 'FOUL',
    'ob.pass_completed': 'PASS COMPLETED',
    'ob.cleared': 'CLEARED',
    'ob.conceded': 'CONCEDED',
    'ob.timeout': 'MOVE OVER',
    'ob.drill_complete': 'DRILL COMPLETE',

    'period.pre': 'Pre-match',
    'period.first': '1st Half',
    'period.ht': 'Half-time',
    'period.second': '2nd Half',
    'period.et_break': 'Extra time',
    'period.et1': 'Extra time 1',
    'period.et2': 'Extra time 2',
    'period.pens': 'Penalties',
    'period.over': 'Full-time',

    'pre.title': 'Match Preview',
    'pre.stakes.derby': 'DERBY',
    'pre.stakes.final': 'FINAL',
    'pre.stakes.big': 'BIG GAME',
    'pre.stakes.knockout': 'KNOCKOUT',
    'pre.stakes.normal': 'LEAGUE GAME',
    'pre.attendance': '{n} fans',
    'pre.start': 'Kick Off',
    'pre.simulate': 'Simulate',
    'pre.role.starter': 'You’re in the starting XI. The stage is yours!',
    'pre.role.bench': 'You’re on the bench. Wait for the manager’s call.',
    'pre.role.none': 'You’re not in the squad today. You’ll watch from the stands.',
    'pre.lineups': 'Line-ups',
    'pre.bench': 'Substitutes',
    'pre.strength': 'Balance of Power',
    'pre.att': 'Attack',
    'pre.mid': 'Midfield',
    'pre.def': 'Defence',
    'pre.gk': 'Goalkeeper',
    'pre.weather': 'Weather',
    'pre.you': 'YOU',
    'pre.formation': 'Formation',
    'pre.neutral': 'Neutral venue',
    'w.clear': 'Clear',
    'w.cloudy': 'Cloudy',
    'w.rain': 'Rain',
    'w.snow': 'Snow',
    'w.fog': 'Fog',
    't.day': 'Day',
    't.dusk': 'Dusk',
    't.night': 'Night',
    'wind': 'Wind {n} m/s',

    'live.momentum': 'Momentum',
    'live.possession': 'Possession',
    'live.shots': 'Shots',
    'live.onTarget': 'On target',
    'live.xg': 'xG',
    'live.simToEnd': 'Simulate to End',
    'live.pause': 'Pause',
    'live.resume': 'Resume',
    'live.speed': 'Speed',
    'live.yourRating': 'Live Rating',
    'live.onBench': 'Warming up on the bench… one nod from the manager is all you need.',
    'live.offPitch': 'You’ve been substituted. Cheering the team on from the bench.',
    'live.notInSquad': 'You’re not playing in this match.',
    'live.moments': 'Moments',
    'live.minutes': 'min',
    'live.waiting': 'Kick-off is moments away…',
    'live.feed': 'Live Commentary',
    'live.shootout': 'Penalty Shootout',
    'live.extraTime': 'EXTRA TIME!',
    'live.agg': 'Agg. {score}',

    'ht.title': 'Half-time',
    'ht.continue': 'Start Second Half',
    'ht.talk.win': 'The manager is calm in the dressing room: “Keep doing exactly this. Stay focused.”',
    'ht.talk.draw': 'The manager sketches on the board: “We can win this. Be braver!”',
    'ht.talk.lose': 'A storm in the dressing room! The manager slams the table: “Earn that shirt!”',
    'ht.yourHalf': 'Your first-half rating',

    'mo.play': 'PLAY',
    'mo.simulate': 'Simulate',
    'mo.skip': 'Simulate',
    'mo.camera': 'Camera',
    'mo.replay': 'Replay (T)',
    'mo.continue': 'Continue',
    'mo.autostart': 'Starting automatically…',
    'mo.webglFallback': 'The 3D view could not start; the moment was simulated.',
    'mo.resolving': 'Playing the moment…',
    'mo.attempt': 'Attempt {n}/{m}',
    'mo.score': 'Score {n}',
    'cam.behind': 'Behind player',
    'cam.broadcast': 'Broadcast',
    'cam.top': 'Top-down',

    'ft.title': 'Full-time',
    'ft.pens': 'Penalties: {score}',
    'ft.yourRating': 'Your Rating',
    'ft.motm': 'MAN OF THE MATCH',
    'ft.motmOther': 'Man of the match: {name}',
    'ft.xp': 'Development',
    'ft.stats': 'Your Match',
    'ft.teamStats': 'Match Stats',
    'ft.notes': 'Fallout',
    'ft.applying': 'Processing the result…',
    'ft.continue': 'Continue',
    'ft.press': 'Press Conference',
    'ft.didNotPlay': 'You didn’t get on the pitch in this match.',
    'ft.minutesPlayed': '{n} minutes',
    'ft.win': 'VICTORY',
    'ft.draw': 'DRAW',
    'ft.loss': 'DEFEAT',
    'ft.applyError': 'The result could not be saved.',
    'grade.legend': 'Legendary',
    'grade.great': 'Superb',
    'grade.good': 'Good',
    'grade.ok': 'Decent',
    'grade.poor': 'Poor',
    'grade.awful': 'Awful',
    'st.goals': 'Goals',
    'st.assists': 'Assists',
    'st.shots': 'Shots (on target)',
    'st.passes': 'Passes',
    'st.keyPasses': 'Key passes',
    'st.dribbles': 'Dribbles',
    'st.tackles': 'Tackles',
    'st.interceptions': 'Interceptions',
    'st.moments': 'Moments played',
    'st.minutes': 'Minutes',

    'err.noMatch': 'Match not found.',
    'err.start': 'Could not start the match: {msg}',
    'err.back': 'Back to Hub',

    'drill.team.us': 'Training',
    'drill.team.them': 'Bibs',
    'drill.keeper': 'Keeper',
    'drill.defender': 'Defender',
    'drill.mate': 'Teammate',
    'drill.desc.drill_free_kick': 'Practise free kicks from outside the box against a wall and a keeper. Draw the curl line to bend it over the wall; the corners earn bonus points.',
    'drill.desc.drill_finishing': 'Finish the passes your teammate feeds you. Decide quickly and aim for the corners; first-time finishes score the most.',
    'drill.desc.drill_passing': 'Find your teammates despite the pressing defenders. Accuracy and tempo matter — through balls score extra!',
    'drill.attempts': '{n} attempts',
    'drill.start': 'Start Drill',
    'drill.back': 'Back to Training',
    'drill.result': 'Drill Result',
    'drill.score': 'Score',
    'drill.invalid': 'Unknown drill type.',
    'drill.controls': 'Controls',
    'drill.ctrl.aim': 'Drag out from the ball: length = power, bend = curl.',
    'drill.ctrl.move': 'Tap the pitch or use WASD/arrows to run.',
    'drill.ctrl.call': 'Space / PASS! to call for the ball.',
    'drill.noState': 'No active career.',
    'drill.rewards': 'Rewards',
  },
});
